### ISSUE TITLE
[Feature Request] mlx.core.radians and mlx.core.degrees

### ISSUE THREAD

**Issue by Crear12** [ml-explore/mlx#1008]
Hi,
Will MLX support similar operations like np.radians and np.degrees? I'm trying to lazy-migrate my current code to MLX by ```import mlx.core as np```. In geo-information, I used a lot of np.radians and np.degrees, which haven't been implemented in MLX yet. 

I checked developer documentation but it's a little bit too complicated for me to contribute (I'm civil engineering student and I barely have any experience in C++). The python version should be something like this:
```
import mlx.core as mx

def radians(degrees_array: mx.array) -> mx.array:
    return degrees_array*(mx.pi/180)

def degrees(radians_array: mx.array) -> mx.array:
    return radians_array*(180.0 / mx.pi)
```

Following the documentation, C++ version should be like this (but pi needs to be specified or called somewhere):
```
array radians(
    const array& degrees, // Input array degrees
    StreamOrDevice s /* = {} */ // Stream on which to schedule the operation
) {
    return multiply(array(pi/180), degrees, s);
   
}
```
and
```
array degrees(
    const array& radians, // Input array radians
    StreamOrDevice s /* = {} */ // Stream on which to schedule the operation
) {
    return multiply(array(180/pi), radians, s);
   
}
```

Starting from Primitives, I'm totally lost...I'd appreciate it if someone can help integrate radians and degrees to MLX.

Thanks in advance!

**Comment by awni** [comment]
You can easily patch MLX with whatever Python function you want:

```Python
import mlx.core as np

def degrees(radians_array: np.array) -> np.array:
    return radians_array*(180.0 / np.pi)

np.degrees = degrees

print(np.degrees(np.array(1.0)))
```

I'm not opposed to add this to MLX since NumPy supports it. You basically implemented it in your issue already.. just need the python bindings and it's done. Do you want to add it yourself?

**Comment by Crear12** [comment]
> You can easily patch MLX with whatever Python function you want:
> 
> ```python
> import mlx.core as np
> 
> def degrees(radians_array: np.array) -> np.array:
>     return radians_array*(180.0 / np.pi)
> 
> np.degrees = degrees
> 
> print(np.degrees(np.array(1.0)))
> ```
> 
> I'm not opposed to add this to MLX since NumPy supports it. You basically implemented it in your issue already.. just need the python bindings and it's done. Do you want to add it yourself?

Thank you for responding so quickly! I'm not sure how to add python bindings..is it through a .cpp file and nanobind or is it like adding the python snippet above to a class under mlx.core?

Unfortunately I'm not familiar with building and compiling, if it requires .cpp, please feel free to add it as I won't be able to master C++ in the next few weeks.

**Comment by emirakdere** [comment]
Want to start contributing in the repo, I can take this on since it's a good first issue

**Comment by Crear12** [comment]
> Want to start contributing in the repo, I can take this on since it's a good first issue

Thanks! If you can share the detailed steps (not just the code, but also snapshots of building, binding, and submission procedures, as detailed as possible) when you finished, this issue may become a good tutorial and noobs like me may be able to learn and contribute in the future. (No pressure at all, it's just a suggestion)

**Comment by awni** [comment]
This already has a nearly complete PR.

**Comment by angeloskath** [comment]
Closing as #1011 is merged.

**Comment by Crear12** [comment]
Glad to see the update! There seems to be an unexpected behavior when the input is not an array. For example, a number:

>>> import numpy as np
>>> np.radians(0)
0.0
>>> import mlx.core as mx
>>> mx.radians(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: radians(): incompatible function arguments. The following argument types are supported:
    1. radians(a: array, /, *, stream: Union[None, Stream, Device] = None) -> array

Invoked with types: int

**Comment by awni** [comment]
Do you mind opening an issue about it?

**Comment by Crear12** [comment]
> Do you mind opening a new issue about it?
> 
> Also, are you able to use `math.radians` for the scalar cases?

Just opened. numpy supports list+array+scalar. math only accepts scalar.
