### ISSUE TITLE
[BUG] ValueError with mx.array index

### ISSUE THREAD

**Issue by stockeh** [ml-explore/mlx#1015]
Array index update is unintuitive when setting lower dimensional array to a given index.

**To Reproduce**
```python
B, N, D = 16, 10, 3
a = mx.zeros((B, N, D))
b = mx.ones((B, D))

a[:, 0]   = b          # (1) ValueError: Cannot broadcast array of shape (16,3) into shape (16,1,3).
a[:, 0]   = b[:, None] # (2) ValueError: Cannot broadcast array of shape (16,1,1,3) into shape (16,1,3).
a[:, 0:1] = b[:, None] # (3) But this works...
```

**Expected behavior**
Update (1) should be the same as NumPy, this is:
 ```python
B, N, D = 16, 10, 3
a = np.zeros((B, N, D))
b = np.ones((B, D))

a[:, 0] = b
```

**Software Versions**
 - OS Version: MacOS 14.4.1 (23E224)
 - MLX Version: 0.11.0
 - NumPy Version: 1.26.4

**Comment by awni** [comment]
Looks like a bug.

**Comment by PRESIDENT810** [comment]
I guess it has nothing to do with indexing since the following code:
```
auto before = reshape(arange(16*3), {16, 3});
auto after = broadcast_to(before, {16, 1, 3});
```
aisle fails with `Cannot broadcast array of shape (16,3) into shape (16,1,3).` because somehow `broadcast_shapes` deduces the broadcast shape is (16, 16, 3) instead of (16, 1, 3)

I can take some time looking into this.

**Comment by awni** [comment]
No this is an indexing bug in `__setitem__`. The broadcast you mention above is not valid and should fail.

The issue above is that `a[:, 0]` should actually have shape `(16, 3)` which of course is broadcast compatible with `b` which has the same shape.

**Comment by PRESIDENT810** [comment]
Hummm I see

Is there any tricks to debug the nanobind part of C++ code? I tried to use lldb to debug python process, but it seems that I can't set breakpoint in C++ source files under `python/src` somehow (lldb can't resolve them). Kinda painful to inspect the problem without being able to debug it...

**Comment by PRESIDENT810** [comment]
Hmmmm I see.

Is there any tricks to debug the C++ nanobind code? I tried to debug `mlx_set_item` function by making lldb attach to the python process running mlx code, but my `core.cpython-39-darwin.so` doesn't have debug info so lldb can't resolve locations of breakpoints I set. I also tried to build a debug version of mlx library and add `NOSTRIP` to `nanobind_add_module` in CMakeLists.txt, but that doesn't do the trick somehow. 

Would really appreciate some hints, thanks!

**Comment by awni** [comment]
Did you try building in DEBUG mode? I think if you do `DEBUG=1` before the build call it should build in debug mode.

**Comment by PRESIDENT810** [comment]
Yep I tried:

<img width="856" alt="image" src="https://github.com/ml-explore/mlx/assets/44538064/24988ff5-820b-41be-a3dc-8a3ae12624ac">

The binary built with DEBUG=1 has significantly larger size than the one built with DEBUG=0 so I guess it's indeed DEBUG mode, but somehow dwarfdump says there's no debug info. 
I also tried to add NOSTRIP for [nanobind_add_module](https://nanobind.readthedocs.io/en/latest/api_cmake.html#command:nanobind_add_module) but ended up with the same result.

**Comment by adamsoliev** [comment]
I am also interested in this since I am having a similar issue

**Comment by PRESIDENT810** [comment]
Ah OK, I finally managed to figure out how to debug C++ nanobind code...

Turns out my C++ knowledge is a bit rusty and the actual debug info is stored in object files instead of the final binary product, and you can use `nm -pa <binary> | grep OSO` to view them. `pip install -e .` will clean the intermediate object files so you need to manually build `core.cpython-39-darwin.so` by yourself, and replace the mlx package under `site-packages` with the library you just built. In this way you can keep the intermediate object files and use them for debug later.

I compared code between `mlx_get_item` and `mlx_set_item` and I think we might need a `squeeze_needed` variable to squeeze the ndarray if we have some index being an integer and do a reshape at last. In this way a[:, 0] should be squeezed with shape (16, 3) instead of (16, 1, 3). Maybe I can take some time and try to fix this?

**Comment by awni** [comment]
Nice! 

And yes that sound correct to me. When you have an integer index it should squeeze the corresponding dimension. Regarding how to implement it, I'm not sure what's the cleanest way as I haven't looked at that code recently. But following how we do it in `mlx_get_item` seems pretty reasonable to me.
