### ISSUE TITLE
[BUG] AttributeError: type object 'QuantizedLinear' has no attribute 'quantize_module' when using whisper with mlx-community/whisper-large-v3-mlx-4bit hf

### ISSUE THREAD

**Issue by ahmetkca** [ml-explore/mlx#1017]
**Describe the bug**
I am trying to use mlx-community/whisper-large-v3-mlx-4bit quantized mlx whisper model for speech recognition. 

Include code snippet
```python
import whisper
whisper_model_hf_repos = [
    "mlx-community/whisper-large-v3-mlx-4bit",
]
text = whisper.transcribe(speech_file, verbose=True, path_or_hf_repo=whisper_model_hf_repos[0])
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: 14.4.1 (23E224)
 - Version mlx==0.11.0

**Additional context**

**Comment by Blaizzy** [comment]
update your quantization utils to use nn.quantize:

https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/utils.py#L337
https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/utils.py#L523

**Comment by awni** [comment]
It should work if you pull the latest mlx-examples from github. If it doesn't let us know and I will reopen.
