### ISSUE TITLE
[BUG] Cannot delete model from memory after using 'generate' from mlx_lm.utils

### ISSUE THREAD

**Issue by s-smits** [ml-explore/mlx#1023]
**Describe the bug**
The bug occurs when processing and deleting a model and tokenizer in Python using the mlx_lm library. After deleting the model and tokenizer, the memory usage remains at 11GB instead of being cleared to 0GB as expected.

**To Reproduce**
Run the provided Python script below, which includes the process_model() function to load, generate output, and delete the model and tokenizer. After deleting the model and tokenizer, the memory usage still remains at 11GB.

Include code snippet
```python
import gc
from mlx_lm.utils import load, generate

def process_model():
    # Load model and tokenizer
    model_name = "mlx-community/Meta-Llama-3-8B-Instruct-4bit"
    model, tokenizer = load(model_name)

    # Generate output
    system = "You are a helpful assistant."
    question = "What is the capital of The Netherlands?"
    prompt = f"<[begin_of_text|><|start_header_id|>system<|end_header_id|>{system}<|eot_id|><|start_header_id|>user<|end_header_id|>{question}<|eot_id|><|start_header_id|>assistant<|end_header_id|>"
    generate(model, tokenizer, prompt, temp=0.2, max_tokens=768, verbose=True)
    del model, tokenizer
    gc.collect()

def test_function(a, b):
    print(a + b)
    
process_model()
# Memory still here are after processing and deleting model and tokenizer
test_function(1, 2)
```

**Expected behavior**
The memory usage should be cleared to near 0GB after deleting the model and tokenizer.

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 14.6.6]
 - mlx version [e.g. 0.11.1]
 - mlx-lm version [e.g. 0.10.0]

**Additional context**
It is possible that there is a specific function to clear the memory used by the model, similar to K.clear_session() in Keras or torch.cuda.empty_cache() in PyTorch. However, I could not find such a function in the documentation for the libraries used in this script.

**Comment by awni** [comment]
We don't have a clear cache function but you can get the same behavior with something like the following:

```python
import mlx.core as mx

a = mx.zeros((4096,))
mx.eval(a)
print(mx.metal.get_cache_memory(), mx.metal.get_active_memory())
old_limit = mx.metal.set_cache_limit(0)
del a
mx.metal.set_cache_limit(old_limit)
print(mx.metal.get_cache_memory(), mx.metal.get_active_memory())
```

We could add a `clear_cache`, but so far there hasn't been a big need for it.

**Comment by awni** [comment]
I'm also curious though, why do you want to clear the cache? Depending on your use case there may be a better option than wiping it clean slate after unloading the model.
