### ISSUE TITLE
[BUG] raise ValueError(f"Received parameters not in model: {extras}

### ISSUE THREAD

**Issue by IzzyHibbert** [ml-explore/mlx#1024]
**Describe the bug**
While converting the model **stabilityai/stablelm-2-12b**, it goes to the end and after it throws an error with syntax :
**_raise ValueError(f"Received parameters not in model: {extras}_**
See screnshot here..

Include code snippet
```
! python -m mlx_lm.convert \
--hf-path "stabilityai/stablelm-2-12b" \
--mlx-path "/huggingface/hub/models" \
--q-bits 8

```

**Expected behavior**
Complete conversion and creates gguf

**Desktop (please complete the following information):**
 - OS Version: Sonoma
 - Version : 14.1

**Additional context**
![Screenshot 2024-04-22 alle 12 41 13](https://github.com/ml-explore/mlx/assets/45388237/1fa9cae4-37d2-4074-8b11-e7c238eac93a)

**Comment by s-smits** [comment]
Same problem, but with loading a local model (QLoRA):
![image](https://github.com/ml-explore/mlx/assets/167638923/f7dbaa0d-56c4-4652-90ef-044538f1ea2e)
```
qlora_folder = 'qlora'
model, tokenizer = load(qlora_folder)
```

**Comment by awni** [comment]
@IzzyHibbert I just tried that model and it worked fine.. my guess is you are using an outdated MLX LM. Try `pip install -U mlx-lm`.

**Comment by awni** [comment]
@s-smits please start a separate issue and include steps to reproduce the problem and we can help debug.

**Comment by ivanfioravanti** [comment]
> @IzzyHibbert I just tried that model and it worked fine.. my guess is you are using an outdated MLX LM. Try `pip install -U mlx-lm`.

I had same issue and I was using old pip packages.
