### ISSUE TITLE
Building from source requires Xcode (not only Xcode command-line tools)

### ISSUE THREAD

**Issue by jbarrow** [ml-explore/mlx#103]
In case anyone runs into the following error when installing from source:

```
xcrun: error: unable to find utility "metal", not a developer tool or in PATH
```

It's solvable with instructions from here: https://github.com/gfx-rs/gfx/issues/2309

I had previously only installed Xcode command-line tools (`xcode-select --install`), but was running into the above error. Installing full Xcode and running:

```
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
```

Allowed me to install from source (`env CMAKE_BUILD_PARALLEL_LEVEL="" pip install -e .`)

**Comment by awni** [comment]
Maybe we should be more explicit with this in [install docs](https://ml-explore.github.io/mlx/build/html/install.html)

**Comment by awni** [comment]
Updated the docs and pinned #200
