### ISSUE TITLE
Pip install does not recognize mlx

### ISSUE THREAD

**Issue by dshieble** [ml-explore/mlx#105]
This is the first time I've seen this, 
```
MacBook-Pro:mistral danshiebler$ python3 --version
Python 3.11.6
MacBook-Pro:mistral danshiebler$ pip3 install mlx
ERROR: Could not find a version that satisfies the requirement mlx (from versions: none)
ERROR: No matching distribution found for mlx
MacBook-Pro:mistral danshiebler$ pip3  install -i https://pypi.org/simple mlx
ERROR: Could not find a version that satisfies the requirement mlx (from versions: none)
ERROR: No matching distribution found for mlx
```
Has the package been removed?

Environment: virtualenv, Apple M2 Pro

**Comment by awni** [comment]
Checkout the install docs: https://ml-explore.github.io/mlx/build/html/install.html

Probably you are using a non-native python. There is a troubleshooting section on that. If that is not the problem, please comment here and I will reopen.

**Comment by dshieble** [comment]
thanks, this solved it
