### ISSUE TITLE
[BUG] EOS terminator for mlx_lm generate function

### ISSUE THREAD

**Issue by caseybasichis** [ml-explore/mlx#1062]
Attempting to use mlx with Llama3 via mlx_lm and the generate util.
It doesn't seem to respond to Llama's terminator.

**Comment by awni** [comment]
For the original instruct models they seem to have the wrong end of sentence token specified. You can run mlx lm with the flag `--eos-token <|eot_id|>`. Or you can use the quantized models in the [HF MLX Community](https://huggingface.co/collections/mlx-community/llama-3-662156b069a5d33b3328603c). Those should have the right end of sentence token. If they don't let us know and we will fix.
