### ISSUE TITLE
No module named 'mlx.core'; 'mlx' is not a package

### ISSUE THREAD

**Issue by hawkheimmer** [ml-explore/mlx#1069]
**Describe the bug**
I used `pip install mlx` to install mlx in a new conda environment, and I had problem with `import mlx.core as mx`

Include code snippet
```python-traceback
Traceback (most recent call last):
  File "/Users/cc/Documents/uvm/mlx.py", line 1, in <module>
    import mlx.core as mx
  File "/Users/cc/Documents/uvm/mlx.py", line 1, in <module>
    import mlx.core as mx
ModuleNotFoundError: No module named 'mlx.core'; 'mlx' is not a package
```

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.4.1
 - Version:0.12.2
 - Python:3.11.9

**Additional context**
I tried `python -c "import platform; print(platform.processor())"` in my conda environment as well, and it returned `arm`.

**Comment by awni** [comment]
You can't name the file with your source code the same name as a package. You should change `/Users/cc/Documents/uvm/mlx.py` to something else.

**Comment by hawkheimmer** [comment]
oh thank you, the problem was fixed.
