### ISSUE TITLE
0.12.2 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [ml-explore/mlx#1071]
👋 it looks like 0.12.2 release was not completed, ie the github release did not get created as 0.12.0, raise this issue for some awareness. Thanks! 🙏 

relates to https://github.com/Homebrew/homebrew-core/pull/170675

**Comment by awni** [comment]
Sorry, not following, did the brew release not complete because 0.12.2 is a "pre-release"?

**Comment by chenrui333** [comment]
@awni some tag issue

![image](https://github.com/ml-explore/mlx/assets/1580956/bf8061fc-e78b-44cb-97a9-8e51831b4681)

Also looks like 0.12.1 tag is gone, any thoughts?

**Comment by awni** [comment]
Hmm, the 0.12.1 tag is still there https://github.com/ml-explore/mlx/releases/tag/v0.12.1

I'm still not really following the problem. Anything we can do on our side to fix?

**Comment by chenrui333** [comment]
oh, just need to mark 0.12.2 release as latest release? (oh, can you point me to the doc about the pre-release -> latest release process)? Thanks!

**Comment by awni** [comment]
> oh, just need to mark 0.12.2 release as latest release? 

How does the brew update work? If we do a new tag on MLX github does it try to do an auto release?

> (oh, can you point me to the doc about the pre-release -> latest release process)?

There is no doc on that :(

**Comment by chenrui333** [comment]
we track the latest release and autobump it as batch processing.

**Comment by chenrui333** [comment]
yeah, for now, I probably just need a latest tag (if I do a livecheck update, it would ask me to downgrade to 0.12.0)

left a comment about that too, https://github.com/Homebrew/homebrew-core/pull/170675#issuecomment-2095018955

**Comment by awni** [comment]
Ok I set 0.12.2 as the latest release. Let me know if that doesn't unblock the brew build and I will reopen this!
