### ISSUE TITLE
Is dlpack supported?

### ISSUE THREAD

**Issue by justinchuby** [ml-explore/mlx#1080]
We are looking to support mlx arrays in the ONNX in memory IR: https://onnxscript.ai/intermediate_representation/tensors.html

To create interoperability support we implement the `__dlpack__` protocol (https://dmlc.github.io/dlpack/latest/) on the tensor adapters (https://onnxscript.ai/intermediate_representation/tensors.html#computation-with-different-frameworks). 

I read https://ml-explore.github.io/mlx/build/html/usage/numpy.html and did a quick search but it doesn't seem mlx supports dlpack. Just wondering if there are any plans for it?

**Comment by awni** [comment]
MLX doesn't support the dlpack protocol yet.  It does support the Python buffer protocol, could that work for you?

We could add dlpack support, I do not think it would be too difficult given that [nanobind's `nd::array` supports it](https://nanobind.readthedocs.io/en/latest/ndarray.html#the-nb-ndarray-class).

**Comment by justinchuby** [comment]
I think we can just wait for dlpack support, since it should be simpler to use. The tensor objects we create are simply wrappers around arrays from different frameworks, so it matters any target framework also needs to support the protocol.

**Comment by awni** [comment]
Do you need both support from dlpack and to dlpack? `__dlpack__` gets you the capsule. But how do you go from dlpack to other framework? Or is that not needed?

**Comment by awni** [comment]
How is this going? DId you need any additional dlpack support in `mx.array`?

**Comment by justinchuby** [comment]
For some reason this code fails for me:

```python
import torch
import mlx.core as mx
import numpy as np

np.from_dlpack(mx.array([42]))
```

->

```
AttributeError                            Traceback (most recent call last)
[<ipython-input-18-26021316f7b0>](https://localhost:8080/#) in <cell line: 1>()
----> 1 np.from_dlpack(mx.array([42]))

AttributeError: type object 'mlx.core.array' has no attribute '__dlpack__'
```

`mx.__version__=='0.2.0'`

**Comment by justinchuby** [comment]
When running on a Mac machine, I get

```
In [4]: tensor = torch.from_dlpack(mx.array([42]))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 tensor = torch.from_dlpack(mx.array([42]))

File /opt/homebrew/lib/python3.10/site-packages/torch/utils/dlpack.py:101, in from_dlpack(ext_tensor)
     50 """from_dlpack(ext_tensor) -> Tensor
     51
     52 Converts a tensor from an external library into a ``torch.Tensor``.
   (...)
     98
     99 """
    100 if hasattr(ext_tensor, '__dlpack__'):
--> 101     device = ext_tensor.__dlpack_device__()
    102     # device is either CUDA or ROCm, we need to pass the current
    103     # stream
    104     if device[0] in (DLDeviceType.kDLGPU, DLDeviceType.kDLROCM):

AttributeError: 'array' object has no attribute '__dlpack_device__'

In [5]: np.from_dlpack(mx.array([42]))
Out[5]: array([42], dtype=int32)
```

showing numpy works but torch fails.

**Comment by awni** [comment]
- The linux distribution is an old version. You can try installing with Conda to get a new release for linux (we'll update the pypi one)
- Ok looks like we need a `__dlpack_device__`

**Comment by justinchuby** [comment]
Just checking if it's implemented now?

**Comment by justinchuby** [comment]
Just saw it. Thanks!

**Comment by awni** [comment]
Let us know if you have any trouble with that.
