### ISSUE TITLE
Enhancement - Use M series iPads as extra GPU power

### ISSUE THREAD

**Issue by petergreis** [ml-explore/mlx#1089]
Now that we have this most awesome framework, I have a suggestion for an enhancement. iPads since 2021 are using the same Apple Silicon as MacBooks. It would be really useful to be able to plug in an iPad directly and use the GPU resources there in addition to those resident on the PC. An extra 8-10 cores wouldn't hurt....

**Comment by awni** [comment]
We plan  to do distributed, see #1046. Beyond that we don't have plans to connect machines, but that may end up addressing this case.
