### ISSUE TITLE
[Feature] something like `mlx.scipy.stats`

### ISSUE THREAD

**Issue by PaulScemama** [ml-explore/mlx#1107]
Thanks for the wonderful library!

I was wondering if there was any plan to implement/expose functions that evaluate e.g. logpdfs of various common distributions. Something similar to what JAX is doing with `scipy.stats`.

**Comment by awni** [comment]
We don't have a plan for that and its unlikely to be something we get to in the near future. A Scipy-like package built on top of MLX would be very cool to see though!

**Comment by PaulScemama** [comment]
Okay great thanks @awni!
