### ISSUE TITLE
[BUG] AttributeError in mlx.core.conj and mlx.core.conjugate functions

### ISSUE THREAD

**Issue by profConradi** [ml-explore/mlx#1127]
**Describe the bug**
While using the mlx.core.conj and mlx.core.conjugate functions, I encountered the following errors:
AttributeError: module 'mlx.core' has no attribute 'conj'
AttributeError: module 'mlx.core' has no attribute 'conjugate'

**To Reproduce**

Include code snippet
```
import mlx.core as mx
result = mx.conjugate(mx.array([1j,2j,3]))
```

**Expected behavior**
The function should return the conjugate of the given input without any errors.

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 14.4]
 - Version [e.g. 0.13.0]

**Additional context**
I have verified that I have the latest version of the mlx package installed. Please let me know if there are any information I can provide to help diagnose the issue.

**Comment by awni** [comment]
The conjugate function is in main but not distributed in the latext MLX PyPI version (0.13.0). It will be in 0.14.0,  but if you need it sooner you can [build from source](https://ml-explore.github.io/mlx/build/html/install.html)

**Comment by awni** [comment]
Note we'll probably do a 0.14 (or maybe 0.13.1) tomorrow, so it won't be too long.

**Comment by profConradi** [comment]
Thanks!
