### ISSUE TITLE
[BUG] mlx gets stuck with high-dimensional array on Linux

### ISSUE THREAD

**Issue by cccyf** [ml-explore/mlx#1134]
**Describe the bug**
mlx gets stuck when values are assigned to high-dimensional array on Linux.

**To Reproduce**

```python
import mlx.core as mx
a = mx.ones([2,2,2,2,2,2])
a[0,0] = 0
mx.eval(a) # stuck here
```

**Expected behavior**
1. On MacOS, the code gets executed successfully without noticeable latency. 
2. With low-dimensional data, e.g. `num_dims = 5`, the code doesn't have any issue. For example

```
a = mx.ones([2,2,2,2,2])
a[0,0] = 0
mx.eval(a) # can be done very fast
```

**Desktop (please complete the following information):**
 - OS Version: Ubuntu 18.04.6 LTS

**Additional context**
N/A

**Comment by awni** [comment]
Actually broken on MacOS as well when building without the Metal back-end:

```
env CMAKE_ARGS="-DMLX_METAL_DEBUG=OFF -DMLX_BUILD_METAL=OFF" CMAKE_BUILD_PARALLEL_LEVEL="" python setup.py develop
```
