### ISSUE TITLE
Question about supporting slices of the type a[:, [0]]

### ISSUE THREAD

**Issue by JoeJoe1313** [ml-explore/mlx#1148]
In `numpy` we can do the following thing:

```
import numpy as np

r = 6
n = 750

Xtr = 0.01 * np.random.randn(r, n)

Xtr[:, [0]]
```

and this would result in an array with shape `(6, 1)`:

```
array([[ 0.0006071 ],
       [-0.01492713],
       [ 0.00182182],
       [-0.01278564],
       [-0.01243541],
       [ 0.01651941]])
```

However, in `mlx` I get the following error

```
ValueError: Cannot index mlx array using the given type yet
```

Are you planning on supporting this in the future? Currently, I am just using `a[:, 0]` with `reshape` but it gets quite heavy having this numerous times in the code.

**Comment by awni** [comment]
We do intend to support indexing with lists. There is an open issue for it #908 so I will close this as a dup of that. Currently it's not being worked on but it should not be too difficult to add.

**Comment by awni** [comment]
This should work in the latest release (`pip install -U mlx`)
