### ISSUE TITLE
[BUG] mlx.core.topk throws segmentation fault for large dimension

### ISSUE THREAD

**Issue by cccyf** [ml-explore/mlx#1156]
**Describe the bug**
`mlx.core.topk` returns segmentation fault when the dimension on which to perform the topk is large.

**To Reproduce**

On MacOS
```python     
Python 3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mlx.core as mx
>>> mx.__version__
'0.14.0'
>>> mx.default_device()
Device(gpu, 0)
>>> x = mx.random.uniform(shape=(1, 45, 32000))
>>> mx.eval(x)
>>> mx.topk(x, 50)
[1]    2561 segmentation fault  python
```

**Expected behavior**
mlx.core.topk returns the top k elements in the specified dimension.

**Desktop (please complete the following information):**
 - OS Version: MacOS 13.6.6
 - Version 0.14.0

**Comment by awni** [comment]
@jagrit06 looks like there is a logic error in the gpu partition for ndim > 2. Do you mind taking a look at this?

These [temporary arrays are 2D](https://github.com/ml-explore/mlx/blob/main/mlx/backend/metal/sort.cpp#L113-L117) but the axis is `2` (for a 3D array) and it segfaults when accessing the strides / shape of the [2D temporaries](https://github.com/ml-explore/mlx/blob/main/mlx/backend/metal/sort.cpp#L231-L232).
