### ISSUE TITLE
[Feature] dlpack device

### ISSUE THREAD

**Issue by awni** [ml-explore/mlx#1159]
Add `__dlpack_device__` to MLX array for full dlpack support. Since arrays don't have devices, we could return the Metal device if it's enabled and CPU otherwise.

**Comment by venkatramnank** [comment]
Hello. Beginner here. While going through some docs, I understand that we will need to include <dlpack.h> and use `DLDeviceType{kDLMetal}` or the equivalent for cpu in `array.cpp` (I might be wrong, please correct me). But I am a bit lost on the conditional statement to decide if the device is Metal or CPU. Thank you!!

**Comment by awni** [comment]
`if (metal::is_available())` return the dlpack metal device, otherwise return the. dlpack CPU device.

> While going through some docs, I understand that we will need to include <dlpack.h> and use DLDeviceType{kDLMetal}

I'm not sure we need to include `dlpack.h`. The device is a simple enumeration so I would probably just hard code the values and point to the dlpack docs: https://data-apis.org/array-api/latest/API_specification/generated/array_api.array.__dlpack_device__.html#array_api.array.__dlpack_device__

**Comment by venkatramnank** [comment]
I have created a PR, however two things are still missing/confusion for me:
1. Device_id, I am not sure about that as per docs
2. Should I update documentation for this feature?

**Comment by awni** [comment]
> Device_id, I am not sure about that as per docs


For the device id, that is implementation specific: 

<img width="761" alt="Screenshot 2024-05-29 at 11 29 03 AM" src="https://github.com/ml-explore/mlx/assets/1542805/fb0929cc-0323-450f-8298-f910fdf1b490">

For MLX you can return either 0 or the given device's index (which should be 0 since we don't do multiple device for a given type yet): https://github.com/ml-explore/mlx/blob/main/mlx/device.h#L19

> Should I update documentation for this feature?

I don't think we need an update for this feature speicifcally. Though maybe worth mentioning in the [conversion docs](https://github.com/ml-explore/mlx/blob/main/docs/src/usage/numpy.rst) that the `mx.array` supports dlpack as well.

**Comment by venkatramnank** [comment]
Understood!!
I have made the changes and thus the PR has been updated.
