### ISSUE TITLE
[BUG] Compiled mx.eval(model.state) raises “Attempting to eval an array without a primitive” with mlx.optimizers.Adam

### ISSUE THREAD

**Issue by igor-pechersky** [ml-explore/mlx#1160]
**Describe the bug**
Compiled mx.eval(model.state) raises “Attempting to eval an array without a primitive” in MNIST example with mlx.optimizers.Adam 

**To Reproduce**

in the code of https://github.com/ml-explore/mlx-examples/tree/main/mnist
replace in  https://github.com/ml-explore/mlx-examples/blob/ca7ce60c911c107d0ffa34554f5ca41a81e0fdc6/mnist/main.py#L65C5-L65C55

```python
optimizer = optim.SGD(learning_rate=learning_rate)
```
by
```python
optimizer = optim.Adam(learning_rate=learning_rate)
```

**Expected behavior**
Error raised
```
mx.eval(model.state)
RuntimeError: [eval] Attempting to eval an array without a primitive. This may be a bug, please file an issue here:  https://github.com/ml-explore/mlx/issues.
```

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.5, Apple M3 Max (64 GB)
 - MLX Version 0.14.0

**Additional context**
1. Error does **not** occur if MLX compilation is disabled (`mx.disable_compile()`)
2. Error occurs with MLX versions 0.10.0 - 0.14.0
3. Error occurs on the **last** minibatch (for MNIST with batchsize=256 - it occurs with minibatch 234)
4. Error occurs when optimizer is set to  mlx.optimizers.{Adam, AdamW, RMSprop, Adagrad} , but not mlx.optimizers.SGD
5. Error does **not** occur if each epoch runs as single batch
```python
    for e in range(num_epochs):
        tic = time.perf_counter()
        loss=step(train_images, train_labels)
        mx.eval(model.state)
        accuracy = eval_fn(test_images, test_labels)
        toc = time.perf_counter()
        print(
            f"Epoch {e}: Test accuracy {accuracy.item():.3f},"
            f" Time {toc - tic:.3f} (s)"
        )
```

**Comment by awni** [comment]
In this case it's not a bug..though I don't know why the error message makes it seem so. That's something to fix.

For optimizers with state, the state has to be captured in the inputs/outputs of `compile` as well, like so:


```python
    state = [model.state, optimizer.state]
    
    @partial(mx.compile, inputs=state, outputs=state)
    def step(X, y):
      ...
```

And then evaluate the full state after each iteration:
```python
mx.eval(state)
```

**Comment by igor-pechersky** [comment]
@awni 
that's exactly the flow in my example
see https://github.com/ml-explore/mlx-examples/blob/main/mnist/main.py#L68C1-L72C20

```
    @partial(mx.compile, inputs=model.state, outputs=model.state)
    def step(X, y):
        loss, grads = loss_and_grad_fn(model, X, y)
        optimizer.update(model, grads)
        return loss
```
so, why nn this case it's not a bug?

**Comment by awni** [comment]
It's not the same, look closely:

```
    state = [model.state, optimizer.state]
    
    @partial(mx.compile, inputs=state, outputs=state)
```

**Comment by igor-pechersky** [comment]
thank you @awni !
the error message deserves fixing though
