### ISSUE TITLE
Potential mx.load() issue with quantized GGUF's

### ISSUE THREAD

**Issue by rshah918** [ml-explore/mlx#1173]
**Describe the bug**
I am trying to implement Mistral 7B, and load it with pretrained quantized weights. However, the actual weight values seem to be giant integers, indicating that there is a data loading error. I'm probably doing something wrong, I'd appreciate any pointers. Seems like the size of the loaded weights is in the kilobytes range, which doesn't seem right either...

**To Reproduce**

Include code snippet
```
file_path = "mistral.gguf" # q4_0 quantization
weights, metadata = mx.load(file_path, return_metadata=True)
print(np.array(weights["blk."+str(0)+".attn_q.weight"]))
print("Loaded weights size: ", sys.getsizeof(weights), " bytes")
```
<img width="757" alt="Screenshot 2024-06-02 at 12 04 00 PM" src="https://github.com/ml-explore/mlx/assets/20956909/abde3f24-3c5b-47b8-a46a-f1d437bb9350">

**Expected behavior**
Accurate values for the weights, and total size in the <5GB range

**Desktop (please complete the following information):**
 - OS Version: macOS Sonoma 14.4
 - Version 0.14.0

**Additional context**
Maybe I'm loading it as the wrong data type? I am not sure what's causing this.

**Comment by awni** [comment]
This is not a bug, the weights are quantized. Quantization represents each weight with 4 bits (typically). Since there is no 4-bit type (and for other reasons) the weights are packed into 32-bit unsigned integers. So the weight dtype should be uint32.
