### ISSUE TITLE
Potential Bug in Distributed Communication

### ISSUE THREAD

**Issue by sck-at-ucy** [ml-explore/mlx#1196]
I am experimenting with MLX Distributed communication between 2 Mac Studios connected via a Thunderbolt bridge. It took me a while to debug the connection but now everything works. However, the basic example of using `mx.distributed.all_sum` does not behave as expected. On the other hand, a python script using mpi4py (doing essentially the same thing) works fine. Here are the two scripts and the respective outputs.

### MLX Script 
```
import mlx.core as mx
import os
import socket

hostname = socket.gethostname()

world = mx.distributed.init()
x = mx.distributed.all_sum(mx.ones(10))
print(f"Hostname: {hostname}: {world.rank()}, {x}")
```

### mpi2py Script 

```
from mpi4py import MPI
import numpy as np

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

# Get the hostname
hostname = MPI.Get_processor_name()

# Create an array of ones of size 10
x = np.ones(10)

# Perform all-reduce sum operation
result = np.zeros_like(x)
comm.Allreduce(x, result, op=MPI.SUM)

# Print the rank, hostname, and result
print(f"Rank: {rank}, Hostname: {hostname}, Sum: {result}")
```

 /opt/homebrew/bin/mpirun  -np 2  --hostfile ~/mpi_hostsfile /Users/m2/anaconda3/envs/pythonProject_StreamLit/bin/python  /Users/m2/PycharmProjects/pythonProject_StreamLit/MX_mpi.py
Hostname: StudioA: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
Hostname: StudioB: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)

/opt/homebrew/bin/mpirun  -np 2  --hostfile ~/mpi_hostsfile /Users/m2/anaconda3/envs/pythonProject_StreamLit/bin/python  /Users/m2/PycharmProjects/pythonProject_StreamLit/MPI_test.py
Rank: 0, Hostname: StudioB, Sum: [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
Rank: 1, Hostname: StudioA, Sum: [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]

**Comment by awni** [comment]
Could you run the same test and include a print for `mx.distributed.is_available()`?

```python
import mlx.core as mx
import os
import socket

hostname = socket.gethostname()

world = mx.distributed.init()
x = mx.distributed.all_sum(mx.ones(10))
print("Distributed available: {mx.distributed.is_available()}")
print(f"Hostname: {hostname}: {world.rank()}, {x}")
```

**Comment by awni** [comment]
Also maybe check `/Users/m2/anaconda3/envs/pythonProject_StreamLit/bin/python -c "import mlx.core as mx; print(mx.__version__)"`

**Comment by sck-at-ucy** [comment]
/opt/homebrew/bin/mpirun  -np 2  --hostfile ~/mpi_hostsfile /Users/m2/anaconda3/envs/pythonProject_StreamLit/bin/python  /Users/m2/PycharmProjects/pythonProject_StreamLit/MX_mpi.py
Distributed available: {mx.distributed.is_available()}
Hostname: StudioA: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
Distributed available: {mx.distributed.is_available()}
Hostname: StudioB: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
(pythonProject_StreamLit) 16:16:12 ~ $>

**Comment by sck-at-ucy** [comment]
Have to run to the airport... will continue in a few hours with the rest of the test :)

**Comment by awni** [comment]
Sounds good, also please rerun the first one when you have time, I forgot to include the format specifier.

**Comment by sck-at-ucy** [comment]
Version is 0.15.0 on both machines 

```
/Users/m2/anaconda3/envs/pythonProject_StreamLit/bin/python -c "import mlx.core as mx; print(mx.__version__)" 
0.15.0
```

Also the other test with the local machine runs, produces the same output on both as well:

```
/opt/homebrew/bin/mpirun -np 2 /Users/m2/anaconda3/envs/pythonProject_StreamLit/bin/python /Users/m2/PycharmProjects/pythonProject_StreamLit/MX_mpi.py
Distributed available: {mx.distributed.is_available()}
Distributed available: {mx.distributed.is_available()}
Hostname: StudioA: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
Hostname: StudioA: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
```

```
/opt/homebrew/bin/mpirun -np 2 /Users/m2/anaconda3/envs/pythonProject_StreamLit/bin/python /Users/m2/PycharmProjects/pythonProject_StreamLit/MX_mpi.py 
Distributed available: {mx.distributed.is_available()}
Distributed available: {mx.distributed.is_available()}
Hostname: StudioB: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
Hostname: StudioB: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
```

**Comment by awni** [comment]
Can you rerun it so it actually prints the result of `mx.distributed.is_available()`? E.g. use this line instead:

`print(f"Distributed available: {mx.distributed.is_available()}")`

**Comment by sck-at-ucy** [comment]
Whether locally or distributed, it seems is not available.

```
/opt/homebrew/bin/mpirun  -np 2  --hostfile ~/mpi_hostsfile /Users/m2/anaconda3/envs/pythonProject_StreamLit/bin/python  /Users/m2/PycharmProjects/pythonProject_StreamLit/MX_mpi.py
Distributed available: False
Hostname: StudioA: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
Distributed available: False
Hostname: StudioB: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
```

**Comment by sck-at-ucy** [comment]
This has not helped, I will need to experiment some more: 

```
/opt/homebrew/bin/mpirun -np 2 -x DYLD_LIBRARY_PATH=/opt/homebrew/Cellar/open-mpi/5.0.3_1/lib/  /Users/m2/anaconda3/envs/pythonProject_StreamLit/bin/python /Users/m2/PycharmProjects/pythonProject_StreamLit/MX_mpi.py
Distributed available: False
Distributed available: False
Hostname: StudioB: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
Hostname: StudioB: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
```
and with the symbolic link for lib location 

```
/opt/homebrew/bin/mpirun -np 2 -x DYLD_LIBRARY_PATH=/opt/homebrew/lib/  /Users/m2/anaconda3/envs/pythonProject_StreamLit/bin/python /Users/m2/PycharmProjects/pythonProject_StreamLit/MX_mpi.py
Distributed available: False
Distributed available: False
Hostname: StudioB: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
Hostname: StudioB: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
```

**Comment by awni** [comment]
Another option is to install mpi with conda: `conda install openmpi` which should work without needing to specify a path.

Also you can check that libmpi is present:

```
find /opt/homebrew/lib/ -name "libmpi.dylib" 
```

**Comment by sck-at-ucy** [comment]
```
find /opt/homebrew/lib/ -name "libmpi.dylib"  
/opt/homebrew/lib//libmpi.dylib
```

```
/Users/m2/anaconda3/envs/pythonProject_StreamLit/bin/mpirun -np 2 
/Users/m2/anaconda3/envs/pythonProject_StreamLit/bin/python /Users/m2/PycharmProjects/pythonProject_StreamLit/MX_mpi.py
Distributed available: False
Distributed available: False
Hostname: StudioB: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
Hostname: StudioB: 0, array([1, 1, 1, ..., 1, 1, 1], dtype=float32)
```

**Comment by awni** [comment]
That is super strange. How did you install MLX? Is the Metal backend available?

`python -c "import mlx.core as mx; print(mx.metal.is_available())"`

**Comment by sck-at-ucy** [comment]
```
(pythonProject_StreamLit) 19:28:06 ~ $> python -c "import mlx.core as mx; print(mx.metal.is_available())"
True
```

```
conda list
mlx                       0.15.0                   pypi_0    pypi
mlx-lm                    0.14.3                   pypi_0    pypi
mpi                       1.0                     openmpi    conda-forge
```

**Comment by sck-at-ucy** [comment]
Could it be because I used conda-forge for openmpi?

**Comment by awni** [comment]
> Could it be because I used conda-forge for openmpi?

What command did you use to install it? I don't think so, it should work to install mpi with conda.  Could you check the MPI version?

```
 mpirun --version
mpirun (Open MPI) 5.0.3

Report bugs to https://www.open-mpi.org/community/help/
```

**Comment by sck-at-ucy** [comment]
same here 

```
(pythonProject_StreamLit) 19:29:55 ~ $> mpirun --version 
mpirun (Open MPI) 5.0.3

Report bugs to https://www.open-mpi.org/community/help/
```

**Comment by awni** [comment]
Ok it looks like a problem with our 15.0 distribution. I can reproduce this issue if I use the pypi package.

**Comment by awni** [comment]
Thanks for flagging this @sck-at-ucy , I think the fix in 1199 should work. We can do a patch release to get it out soon.

**Comment by sck-at-ucy** [comment]
BTW, this is opening so many possibilities, really exciting direction 🚀
