### ISSUE TITLE
[BUG] iOS builds fail with float16 issue

### ISSUE THREAD

**Issue by davidkoski** [ml-explore/mlx#1217]
**Describe the bug**

**To Reproduce**

Build mlx for iOS (I am using Xcode 15.3) and you will run into something like this:

```
/Users/dkoski/Developer/mlx-swift/Source/Cmlx/mlx-conditional/../mlx/mlx/backend/accelerate/softmax.cpp:61:22: error: non-constant-expression cannot be narrowed from type 'float' to 'float16_t' (aka '__fp16') in initializer list [-Wc++11-narrowing]
    x = vmulq_f16(x, vdupq_n_f16(1.442695)); // multiply with log_2(e)
                     ^~~~~~~~~~~~~~~~~~~~~
In file included from /Users/dkoski/Developer/mlx-swift/Source/Cmlx/mlx-conditional/accelerate-softmax.cpp:7:
In file included from /Users/dkoski/Developer/mlx-swift/Source/Cmlx/mlx-conditional/../mlx/mlx/backend/accelerate/softmax.cpp:6:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include/arm_neon.h:6501:26: note: expanded from macro 'vdupq_n_f16'
  __ret = (float16x8_t) {__s0, __s0, __s0, __s0, __s0, __s0, __s0, __s0}; 
```

This is on lines like this:

```
    x = vmulq_f16(x, vdupq_n_f16(1.442695F16)); // multiply with log_2(e)
```

The macro expands like:

```
x = vmulq_f16(x, __extension__ ({
    float16x8_t __ret;
    float16_t __s0 = 1.442695;
    __ret = (float16x8_t) {__s0, __s0, __s0, __s0, __s0, __s0, __s0, __s0};
    __ret;
}));
```

which looks ok, but the problem is that `float16_t` isn't the type we are looking for:

```
#define ADD_HALF_BINOPS
#include "mlx/types/fp16.h"
namespace mlx::core {
typedef struct _MLX_Float16 float16_t;
} // namespace mlx::core
```

You can see this by changing the macro to use `::float16_t` or add this to the top of softmax.cpp:

```
#define __ARM_FEATURE_FP16_SCALAR_ARITHMETIC 1
```

I am not sure all the intricacies here, but this is interfering with the float16 code in softmax.cpp on iOS.

Currently blocking https://github.com/ml-explore/mlx-swift/pull/101

**Expected behavior**
This would compile.

**Desktop (please complete the following information):**
 - OS Version: macOS 14.4 (23E200), Xcode 15.3

**Additional context**

**Comment by awni** [comment]
@davidkoski can you share some steps for how to reproduce this? I'm building mlx-swift main using Xcode 15.3 and macOS 14.5 and the build is fine. Do you only get the error on 14.4? Or do I need to build something specific to see the issue?

**Comment by davidkoski** [comment]
The easiest is to try building this branch for iOS:

- https://github.com/davidkoski/mlx-swift/tree/v0.14.0

You will to change various `vecLib` includes:

```
- #include <vecLib/vDSP.h>
+ #include <Accelerate.h>
```

but those are trivial

**Comment by davidkoski** [comment]
I am using Xcode 15.3 on macOS 14.4 but I don't think it is environment dependent -- the key is building for iOS.

**Comment by awni** [comment]
Thanks I can reproduce it now. I'm a little confused by what's going on here. The code that is failing has been there for a while now.. so any idea what changed that broke the compilation?

**Comment by davidkoski** [comment]
Yeah, I think previously the mlx-swift side _didn't_ include the accelerate back end:

https://github.com/ml-explore/mlx-swift/blob/main/Package.swift#L78

(these are files _not_ to build)

```
                // opt-out of these backends (using metal)
                "mlx/mlx/backend/no_metal",
                "mlx/mlx/backend/accelerate",
```

When I prepared the build for v0.14.0 I had to revamp the build quite a bit to deal with the JIT and I reconciled what CMake does with the swiftpm build.

So you are right, it has probably been like this for a while but we were not using it and so had not seen this.

**Comment by awni** [comment]
This is safe to close I believe.
