### ISSUE TITLE
[BUG] python setup.py generate_stubs fails with "No module named 'setuptools'"

### ISSUE THREAD

**Issue by rudkx** [ml-explore/mlx#1225]
**Describe the bug**
I'm following the instructions from [Build from source](https://ml-explore.github.io/mlx/build/html/install.html#build-from-source) and when I hit the step for Python API where I run `python setup.py generate_stubs` I hit this:

```
% python setup.py generate_stubs
Traceback (most recent call last):
  File "/Users/rudkx/repo/mlx/setup.py", line 11, in <module>
    from setuptools import Command, Extension, find_namespace_packages, setup
ModuleNotFoundError: No module named 'setuptools'
```

**To Reproduce**

Follow all the steps in [Build from source](https://ml-explore.github.io/mlx/build/html/install.html#build-from-source) up to the `python setup.py generate_stubs`.

**Expected behavior**
Successful installation.

**Desktop (please complete the following information):**
 - OS Version: macOS 14.5

**Additional context**

My repo was forked earlier today with top-of-tree at `95d11bd`.

**Comment by awni** [comment]
Looks like you need to install `setuptools`, e.g.  `pip install setuptools`
