### ISSUE TITLE
[Feature] cross product

### ISSUE THREAD

**Issue by petertsoi** [ml-explore/mlx#1244]
It would be nice to have a `mx.cross`/`mx.linalg.cross` that works like `np.cross`/`np.linalg.cross`.

**Comment by awni** [comment]
I think we don't need a primitive for this since it's just a handful of ops. If it's too slow the naive way we can re-evaluate.

I would do it with a split -> adds + multiplies -> concat.

**Comment by Saanidhyavats** [comment]
@awni PR related to this issue was updated 2 weeks back. Is it still under process or can I start working on it?

**Comment by awni** [comment]
I would pick a different open issue. That PR needs to be reviewed and I think it is almost done.
