### ISSUE TITLE
Sample packing using mx.fast.scaled_dot_product_attention?

### ISSUE THREAD

**Issue by vgoklani** [ml-explore/mlx#1248]
Flash Attention (Tri Dao) has convenience functions for constructing attention masks for sample-packed sequences. 

i.e. 

https://github.com/Dao-AILab/flash-attention/issues/432#issuecomment-1698610752

Wondering if there is something equivalent here for MLX, or should we just roll our own.

thanks!

**Comment by awni** [comment]
There is no equivalent in MLX and unlikely we will add it for the time being.
