### ISSUE TITLE
[BUG]  Cannot convert a list with `None` to `mx.array`

### ISSUE THREAD

**Issue by amirhossein-razlighi** [ml-explore/mlx#1288]
Here's a simple example:
```
import numpy as np
import mlx.core as mx

test_list = [1, 2, 3, None, 4]
numpy_array = np.array(test_list) # output:  array([1, 2, 3, None, 4], dtype=object)
mx_array = mx.array(test_list)  # output: ValueError: Invalid type  NoneType received in array initialization.
```

The same behaviour as numpy is expected regarding `None` values, but an exception is thrown.

**Comment by awni** [comment]
That is not supported and unlikely to be supported for the foreseeable future. As you can see the type of the `np.array` is `object` which is not a type that `mx.array` supports.
