### ISSUE TITLE
[BUG] Docs not building

### ISSUE THREAD

**Issue by yaroslavyaroslav** [ml-explore/mlx#1290]
**Describe the bug**
I'm unable to build docs by following the readme in `./docs/readme.md`. It falls with the following error:

```bash
(mlx_build) ➜  docs git:(main) ✗ doxygen && make html
Running Sphinx v7.4.7

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/user/.venv/mlx_build/lib/python3.12/site-packages/sphinx/config.py", line 529, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Development/git/mlx/docs/src/conf.py", line 8, in <module>
    import mlx.core as mx
ModuleNotFoundError: No module named 'mlx'

make: *** [html] Error 2
```

**To Reproduce**

1. `brew install doxygen`
2. `cd docs/ && pip install -r requirements.txt`
3. `doxygen && make html`

**Expected behavior**
To docs being built successfully.

**Desktop (please complete the following information):**
 - OS Version: 14.5 (23F79)
 - ebd7135b50ed87dcb78bff011519d1ee8c0ae749

**Additional context**
Installing mlx through `pip` fixes the issue.

**Comment by awni** [comment]
You need to have MLX installed to build the docs

**Comment by yaroslavyaroslav** [comment]
Maybe it's worth to mention this in the readme at least, if not to include into `requirements.txt`?

**Comment by awni** [comment]
Yea good idea, requirements.txt seems like a good place. Do you want to send a PR?

**Comment by yaroslavyaroslav** [comment]
Yeah, sure, sent one.
