### ISSUE TITLE
How can we enable w4a8 GEMM in MLX?

### ISSUE THREAD

**Issue by NicoNico6** [ml-explore/mlx#1293]
**Describe the bug**
The current MLX quantize function only support w4a16 computatiion, how can enable w4a8 computation in MLX library?

**Comment by awni** [comment]
There is no fp8 on macos yet. If / when there is we will consider adding it as a type to MLX at which point you could use it for the scales and biases in quantization.

**Comment by NicoNico6** [comment]
No, I mean the INT8 GEMM, not FP8. For example, MLX has supported INT4/2 weight quantization and dequantization, but the final computation is FP16 GEMM. Will there be any plan for the INT8 activation dynamic quantization (almost lossless) and corresponding GEMM support? Or will this be possible to implement this on Apple sillicon device using metal?

**Comment by angeloskath** [comment]
A matmul kernel where both matrices are quantized is not currently implemented in MLX. It is not too difficult to implement given the building blocks that we have created in `mlx/backend/metal/kernels/quantized.h`. Having said that I don't think we plan to implement this in the near future.

If you want to experiment with w4a8 I think there are two options one being significantly simpler than the other:
- Dequantize the activations just before the matmul. It will be much slower but it will save memory and it will allow you to experiment with w4a8 to see if there is a quality degradation or some other issue before committing to the next step
- Implement an op extension similar to the example in `mlx/examples/extensions` where you utilize the `QuantizedBlockLoader` from `mlx/backend/metal/kernels/quantized.h` to load both `x` and `w`.

Note that a kernel for dequantization will be merged shortly ( #1282 )which will probably make the first option fast enough for experimentation.

**Comment by NicoNico6** [comment]
Thanks for your kind reply. I see the acceleration research community has made impressive LLM acceleration by utilizing the GPU tensorcore INT8/4 GEMM kernels. Therefore I also wanna extend MLX to INT GEMM, but I am not quiet familar with the metal library. For example, does metal has simmilar kernels like the low-precision matmul in tensorcore? Or the speed will not be different to current w4a16 matmul. Many thanks.

**Comment by angeloskath** [comment]
The speed is likely to be slower because we also need to dequantize the second matrix on the fly.

**Comment by NicoNico6** [comment]
I dont see the reason of dequantize and slower computation here. 

Usually, when the weight are quantized into 4-bit offline (start from a simple case, channel-wise symmetric quant, which can be merged after the GEMM ), and the activation are online per-token symmetric quantized into 8-bit (per-token means it can be merged post-GEMM). 

Theoretically, we can do the INT8 matmul computation directlly (without dequantization), which should be faster than fp16, and then merge the scales back into the INT8 matmul computation results. If we have a customied INT8 matrix matmul kernel in MLX, the overall speed would be faster, just like the existing research using CUDA Tensorcore INT8 GEMM (https://arxiv.org/abs/2406.09904).
