### ISSUE TITLE
Missing pyi file for mlx.core

### ISSUE THREAD

**Issue by XXXXRT666** [ml-explore/mlx#1294]
**Describe the bug**
When I install mlx from pip, the latest version 0.16.1 for python39 does not have pyi files for mlx.core, thus there is no type hint in VS Code, There is no folder named `core` in `mlx-0.16.1-cp39-cp39-macosx_14_0_arm64` but the folder with same name is found in `mlx-0.16.1-cp312-cp312-macosx_14_0_arm64`.

Desktop:

OS Version: macOS 15 beta3
Version 0.16.1

**Comment by awni** [comment]
Dup of #1261. Will try and get a fix out for the next release.

**Comment by yuanshanxiaoni** [comment]
There is no folder named `core` in `mlx-0.1x.x-cp310-cp310-macosx_14_0_arm64`.

**Comment by awni** [comment]
Should be there in the latest MLX (pip install -U mlx)
