### ISSUE TITLE
How to mask out padding tokens when calculating the cross-entropy?

### ISSUE THREAD

**Issue by vgoklani** [ml-explore/mlx#1311]
We need to mask out the padding tokens when calculating the cross-entropy.

What's the best way to do this?

```python
x = mx.array([1, 2, 3, 2, 2, 5])
mask = (x == 2)

x[mask]
```

> ValueError: boolean indices are not yet supported

Could you please recommend a work-around. Thanks!

**Comment by angeloskath** [comment]
The best way is to multiply and adjust the mean.

```python
loss_per_token = nn.losses.cross_entropy(logits, labels)
mask = get_padding_mask(...)  # assumes true for the values to keep

loss = (loss_per_token * mask).mean() / mask.mean()
also_loss = (loss_per_token * mask).sum() / mask.sum()
```

**Comment by angeloskath** [comment]
An example of the above pattern can be found at the finetuning code in `mlx_lm` https://github.com/ml-explore/mlx-examples/blob/df744c98e67f94fba8a893cb5aba4fdb735f5f4a/llms/mlx_lm/tuner/trainer.py#L63 .

I will close the issue but feel free to re-open if there is anything I didn't cover.
