### ISSUE TITLE
使用exo+mlx多台mac运行llama-3.1-70b,返现量化时报错[BUG] 

### ISSUE THREAD

**Issue by wjwc** [ml-explore/mlx#1312]
使用exo+mlx多台mac运行llama-3.1-70b,返现量化时报错
报错的位置:
quantized.py文件
代码:
def __call__(self, x):
        s = x.shape
        x = x.flatten()
        out = mx.dequantize(
            self["weight"][x],
            scales=self["scales"][x],
            biases=self["biases"][x],
            group_size=self.group_size,
            bits=self.bits,
        )
        return out.reshape(*s, -1)

x打印的值为:
x is array([[[[0.534668, -0.012146, 0.0141449, ..., 0.0268707, 0.143066, 0.124268],
         [-0.395752, 0.266846, 0.144653, ..., -0.00493622, 0.220337, 0.483398],
         [-0.0620728, 0.0823975, -0.101807, ..., 0.183838, 0.0869141, 0.0322876],
         ...,
         [-0.15918, 0.0597534, -0.110474, ..., 0.102905, 0.00811768, 0.0138779],
         [-0.203369, 0.0515747, -0.0604248, ..., 0.0429993, 0.038208, 0.074707],
         [-0.129517, 0.0895386, -0.138306, ..., -0.0203552, -0.0138397, 0.00897217]]]], dtype=float16)
         
报错:
Error processing tensor for shard Shard(model_id='mlx-community/Meta-Llama-3-70B-Instruct-4bit', start_layer=0, end_layer=52, n_layers=80): [gather] Got indices with invalid dtype. Indices must be integral.
Traceback (most recent call last):
  File "/Users/liushaoping/exo/exo/orchestration/standard_node.py", line 217, in _process_tensor
    result, inference_state, is_finished = await self.inference_engine.infer_tensor(request_id, shard, tensor, inference_state=inference_state)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liushaoping/exo/exo/inference/mlx/sharded_inference_engine.py", line 29, in infer_tensor
    output_data: np.ndarray = np.array(self.stateful_sharded_model.step(request_id, mx.array(input_data)))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liushaoping/exo/exo/inference/mlx/sharded_model.py", line 48, in step
    output = self.model(y[None] if self.shard.is_first_layer() else y, cache=self.request_cache[request_id])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liushaoping/exo/exo/inference/mlx/models/llama.py", line 89, in __call__
    out = self.model(inputs, cache)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liushaoping/exo/exo/inference/mlx/models/llama.py", line 53, in __call__
    h = self.embed_tokens(inputs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liushaoping/exo/.venv/lib/python3.12/site-packages/mlx/nn/layers/quantized.py", line 103, in __call__
    self["weight"][x],
    ~~~~~~~~~~~~~~^^^
ValueError: [gather] Got indices with invalid dtype. Indices must be integral.

有人知道为啥子嘛?

**Comment by angeloskath** [comment]
It seems that you are using the intermediate features as embeddings. Namely `x` contains features and not tokens.

This would be better answered at the exo repository as it is likely a misconfiguration rather than an MLX bug.

I will close this but feel free to reopen it if you think that this is somehow an MLX bug.
