### ISSUE TITLE
[BUG] METALCommand buffer execution failed: Internal Error (0000000e:Internal Error)

### ISSUE THREAD

**Issue by sck-at-ucy** [ml-explore/mlx#1335]
**Describe the bug**
I am running my physics transformer model. With a `batch_size=4 `it trains without any issues. If I increase `batch_size=6` then it seems to crash at random times. Increasing to `batch_size=8` the crash happens frequently. The error message is 

`libc++abi: terminating due to uncaught exception of type std::runtime_error: [METAL] Command buffer execution failed: Internal Error (0000000e:Internal Error)`

What puzzles me is that the memory usage does not seem to excessive: Right before the crash I was clocking the following: 

Physical Memory: 128 GB
Memory Used: 49.30 GB
Cached Files: 15.89 GB
App Memory: 16.75 GB
Wired Memory: 30.96 GB 

Setting the option `checkpoint=True` for the transformer encoder does not seem to have any effect. I guess am exceeding some memory buffer size? But what is that and do I have any control over it?  

**To Reproduce**

Include code snippet
```python
# Configuration parameters
config = {
    "geometry": {
        "rod_length": 1.0,
        "rod_width": 1.0,
        "dx": 0.04,
        "dy": 0.04,
    },
    "boundary_conditions": {
        "left_limits": (0, 1),
        "right_limits": (0, 1),
        "top_limits": (0, 1),
        "bottom_limits": (0, 0.1),
    },
    "thermal_diffusivity": {
        "alpha_limits": (0.01, 0.1)
    },
    "model_params": {
        "start_predicting_from": 5,
        "batch_size": 8,
        "epochs": 1500,
        "time_steps": 401,
        "num_heads": 16, 
        "num_encoder_layers": 24, 
        "mlp_dim": 256, 
        "embed_dim": 512, #512,
        "mask_type": 'block'
    },
    "training_samples": 24_000,  
    "start_from_scratch": False,  
    "checkpoint_epoch": 1488,  
    "current_epoch": None 
}
```

**Expected behavior**
If I am indeed exceeding some buffer size, a more graceful fail with some kind of message to help pinpoint the source of the error. 

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 14.6.2]
 - MLX Version [e.g. 0.16.3]

**Additional context**
I tried running in a minimal environment to eliminate some the chance that some rogue app is causing memory spikes but I still get these crashes that seem to be a bit random. With batch_size=8, some times it can happen in 1 training epoch, but other times it can take 8 or more epochs before it happens.

**Comment by awni** [comment]
This is a dup of https://github.com/ml-explore/mlx/issues/1231

Unfortunately there isn't a silver bullet to fix this one and it's not related to RAM. It's related to some operations timing out (which ideally shouldn't happen but there can be some low level issues which cause that).

The one easy thing to try that may fix it is is using `MLX_MAX_OPS_PER_BUFFER=1  python train.py` but it's not guaranteed.
