### ISSUE TITLE
Looking to add `scan` function to `mlx.transforms`.

### ISSUE THREAD

**Issue by cyrilzakka** [ml-explore/mlx#134]
Planning on adding the `scan` function to `mlx.transforms` similar to the [jax implementation](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scan.html). Would this be of use? For background, I'm working on adding a structured state space [Structured State Spaces](https://arxiv.org/abs/2111.00396) model to mlx examples but some functions are still missing.

**Comment by awni** [comment]
Definiitely, we'd be happy to take a PR for this! Also I'd really love to see an implementation of an SSM in MLX.

**Comment by awni** [comment]
Btw I was wondering why you need a `scan` transform as opposed to a loop or maybe using `vmap`? 

I don't know the implementation details of the models you are looking at but as a general comment, I would recommend you try the naive solution first -> measure perf / find bottlenecks -> implement the transform / op if its needed. The performance of MLX can be quite different than Jax (faster in some parts, slower in others, etc) which is good to be aware of when translating the Jax implementation.

**Comment by awni** [comment]
Are you still working on the port or is it too difficult given missing features in MLX? I'd love to know more about what's missing from MLX / what you've found challenging in porting the SSMs.
