### ISSUE TITLE
[BUG] Metal extensions still use old nanobind version

### ISSUE THREAD

**Issue by tobiaskatsch** [ml-explore/mlx#1342]
**Describe the bug**

In the example extension it still uses the old nanobind version (pre 2.0 upgrade). See: `mlx/examples/extensions/pyproject.toml`. Using nanobind==2.0 in the pyproject.toml leads to segmentation fault. While this does not lead to immediate errors for the example extension, this prevents me from upgrading my own mlx extensions from mlx 0.16.1 to 0.16.2 due to incompatibilities and unexpected errors such as `libc++abi: terminating due to uncaught exception of type std::runtime_error: library not found. Failed to load device library from...`

**Comment by tobiaskatsch** [comment]
just a guess but I suspect the resulting errors have to do with the change to `d.register_library("mlx_ext", metal::get_colocated_mtllib_path);`

**Comment by tobiaskatsch** [comment]
would be great if you could give any hints to how we can run the metal extension fully in nanobind==2.0

**Comment by awni** [comment]
Sorry there were some inconsistencies in how we were setting the nanobind version. For the current MLX you should still use 

`nanobind@git+https://github.com/wjakob/nanobind.git@2f04eac452a6d9142dedb957701bdb20125561e4`

Starting with the next release you will want to use `nanobind==2.1.0` across the board.

**Comment by tobiaskatsch** [comment]
thank you!
