### ISSUE TITLE
[BUG] Missing type stubs in conda install for python 3.11

### ISSUE THREAD

**Issue by jbcoe** [ml-explore/mlx#1345]
**Describe the bug**
No type stubs are provided for mlx/core in pip or conda installs of mlx.

**To Reproduce**

`conda install conda-forge::mlx` # Updated

`ls SOME_PYTHON_PATH/site-packages/mlx/`

has no core directory and no typestubs for core (`site-packages/mlx/core/__init__.pyi`)

**Expected behavior**

Type stubs provided as part of pip install.

**Computer:**

MacOS 14.5 (23F79)
mlx-0.16.3

**Comment by awni** [comment]
Sorry though this was fixed but it wasn't. You can use Python 3.11 and they should be available. https://github.com/ml-explore/mlx/pull/1346 will also fix this for older Python version.

**Comment by jbcoe** [comment]
What's needed to fix this in Python 3.12? I'm willing to learn how to help.

**Comment by jbcoe** [comment]
Using python 3.12 from conda, I see type hints as expected. That's me unblocked.

**Comment by awni** [comment]
Yes the type stubs should be there for 3.11 and up. If you do `pip install -U mlx`. For <=3.10 #1346 should fix them.

**Comment by jbcoe** [comment]
They were missing on 3.11. I'm happy to work with you to debug this but am not blocked any more.

**Comment by awni** [comment]
They are definitely in the latest [release for 3.11](https://pypi.org/project/mlx/0.16.3/#files).

I just downloaded the `.whl` files to double check:

```
curl -O https://files.pythonhosted.org/packages/ec/63/91a8bf8a8c6ed72b8c20e75d481873553935204cba433d479981a1b6acaa/mlx-0.16.3-cp311-cp311-macosx_14_0_arm64.whl
unzip mlx-0.16.3-cp311-cp311-macosx_14_0_arm64.whl | grep "mlx/core/__init__.pyi" 
```

Maybe you had an older version installed? Or installed from somewhere else?

**Comment by jbcoe** [comment]
`conda create -n py311env python=3.11`
`conda activate py311env`
`conda install conda-forge::mlx` 

Gives me an install with no type stubs.

`pip install mlx` 

Gives me an install with type stubs.

**Comment by awni** [comment]
That makes sense. We don't directly control the conda build. This is the repo: https://github.com/conda-forge/mlx-feedstock. We should work with the maintainers there to get the stubs included in the conda distribution.

**Comment by jbcoe** [comment]
I raised https://github.com/conda-forge/mlx-feedstock/issues/51
