### ISSUE TITLE
[BUG] #import in custom kernels doesn't support relative paths

### ISSUE THREAD

**Issue by dsedov** [ml-explore/mlx#1378]
When I describe an include header for a custom kernel, I must provide full path. I.e. if I place the .metal file in the same folder as my python file it cannot find it. I assume the path at which the compile is executed must be different from where my python file is. 

This is what my header looks like in order for it to work:
`
 header = '#import  "/Users/username/Dev/mlxray/loki.metal"'
`
I expect this to work given that I'm running it from a python file that's in the same folder as the loki.metal:
`
 header = '#import  "loki.metal"'
`

**Comment by awni** [comment]
Getting paths working is a bit messy and I don't really advise doing it this way.  Instead you can have a lot more flexibility on where you put the header if you pass the `custom_kernel` the header source code directly. Concretely that would just be:

```python
with open("loki.metal", 'r') as f:
  header = f.read()

## And then pass it to custom kernel
mx.custom_kernel(..., header=header, ...)
```

**Comment by awni** [comment]
> But I can in fact just write tooling around it that concatenates everything into one big header.

Exactly! We may add an includes argument in the future which would basically do exactly that. But it is tricky to get paths working correctly especially if you plan to distributed what you are building as a package.. so I think it's better to encourage the approach of putting it all in one big header.
