### ISSUE TITLE
mx.std() doesn't exist?   [BUG] 

### ISSUE THREAD

**Issue by mode80** [ml-explore/mlx#1386]
**Describe the bug**
mx.std() doesn't exist?

**To Reproduce**
```python
import mlx.core as mx
mx.array([1,2,3]).std()
```
AttributeError: 'array' object has no attribute 'std'

**Expected behavior**
https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.core.std.html

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.1.2
 - Version 0.17.2

**Additional context**
```python
mx.array([1,2,3]).var().sqrt() # works for now
```

**Comment by bhargavyagnik** [comment]
mx.std(x) should also work
