### ISSUE TITLE
[BUG] pad with constant value fails in cpp

### ISSUE THREAD

**Issue by AaronGe88inTHU** [ml-explore/mlx#1398]
**Describe the bug**
pad with constant value always fails by `Assertion failed: (in.shape() == out.shape()), function copy_gpu_inplace, file copy.cpp, line 159.`

**To Reproduce**
```
 auto x = array({1.0f, 2.0f, 3.0f, 4.0f}, {2, 2});
 std::vector<int> axes = {0,1};
 std::vector<int> lower_padded = {1,1};
 std::vector<int>  higer_padded = {1,1};
 auto value = array(0);
 std::string mode = "constant";
 auto padded_x = pad(x, axes, lower_padded, higer_padded, value, mode);
 std::cout << padded_x << std::endl;
```
Include code snippet
```python
python works well
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 15.0.0]
 - Version [branch main]

**Additional context**
it may led by #1383 added `assert(in.shape() == out.shape());`

**Comment by awni** [comment]
Oh that's good.. the assert worked! The Python code is built in release mode which strips asserts so that would explain why it fails in C++ and not in Python (presumably you build in debug mode).
