### ISSUE TITLE
argSort fails by _LIBCPP_ASSERT_VALID_ELEMENT_ACCESS(__n < size(), "vector[] index out of bounds"); 

### ISSUE THREAD

**Issue by AaronGe88inTHU** [ml-explore/mlx#1400]
**Describe the bug**
argSort to the  arrays that have size greater than 4096   fails by _LIBCPP_ASSERT_VALID_ELEMENT_ACCESS(__n < size(), "vector[] index out of bounds"); 
auto x = random::truncated_normal(array(0), array(1), std::vector<int>{4096}) works
auto x = random::truncated_normal(array(0), array(1), std::vector<int>{64, 64}) works
auto x = random::truncated_normal(array(0), array(1), std::vector<int>{8,8,8,8}) works
but 
**To Reproduce**

```  
auto x = random::truncated_normal(array(0), array(1), std::vector<int>{4097});
//auto x = random::truncated_normal(array(0), array(1), std::vector<int>{64, 65});
//auto x = random::truncated_normal(array(0), array(1), std::vector<int>{8,8,8,9});
//auto x = random::truncated_normal(array(0), array(1), std::vector<int>{100,100});
 auto sorted_index = argsort(x);
 std::cout << sorted_index << std::endl;
```

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 15.0.0]
 - Version [e.g. 0.17.2]

**Comment by angeloskath** [comment]
This is fixed in https://github.com/ml-explore/mlx/pull/1383. It will be released this week when we do a patch release, on Thursday at the latest but likely sooner.

**Comment by AaronGe88inTHU** [comment]
Thank you. The new main branch works
