### ISSUE TITLE
[BUG] Why there is no `mx.unique` function

### ISSUE THREAD

**Issue by frank-miao** [ml-explore/mlx#1433]
**Describe the bug**
Very weird that mlx miss such a basic function `mx.unique`, since I just want to check out how many different numbers contained in an array. Then, I have to check it out using numpy 😢 

**To Reproduce**

Include code snippet
```python
>>> import mlx.core as mx
>>> a = mx.random.randint(0,5,(100,))
>>> mx.unique(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mlx.core' has no attribute 'unique'
>>>

```

**Expected behavior**
Return a desired and unique array

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 14.5.0]
 - Version [e.g. 0.17.2]

**Additional context**

**Comment by awni** [comment]
This is a known issue see e.g. https://github.com/ml-explore/mlx/issues/856

Also see this [short note on it](https://gist.github.com/awni/e20a288011adac0d0bdaf73e5296ca4f) for more details.
