### ISSUE TITLE
[BUG] mlx 0.17.3 crashes when converting certain models with mlx-lm

### ISSUE THREAD

**Issue by M-I** [ml-explore/mlx#1438]
**Describe the bug**

Trying to convert  deepseek-ai/DeepSeek-V2.5 and Qwen/Qwen2.5-72B-Instruct ends with failure, when deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct succeeds.  Reverting to 0.17.1 with pip install mlx==0.17.1 fixed it.

**To Reproduce**

Include code snippet
```python
from mlx_lm import load, generate, convert
convert("deepseek-ai/DeepSeek-V2.5", q_bits=2, quantie=true)
```
or  `mlx_lm.convert --hf-path deepseek-ai/DeepSeek-V2.5 -q --q-bits 2`

With mlx 0.17.3, the output is:
```
[INFO] Loading 
Fetching 62 files: 100%|______________________________________________________________________________| 62/62 [00:00<00:00, 14207.10it/s
[INFO] Quantizing
libc++abi: terminating due to uncaught exception of type std::runtime_error: [METAL] Command buffer execution failed: Caused GPU Timeout Error (00000002:kIOGPUCommandBufferCallbackErrorTimeout)
 zsh: abort      HF_HOME=/Volumes/barr_1TB_1/huggingface python3
```
Then back in zsh it ouputs:
```
m-i@MBP  :$> /Users/m-i/miniconda3/envs/mlx/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1
leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: MacOS 15.0
 - Version 0.17.3

**Comment by awni** [comment]
What hardware are you running this on?

**Comment by M-I** [comment]
MBP M3 Max 128GB

**Comment by M-I** [comment]
@awni Since you uploaded https://huggingface.co/mlx-community/DeepSeek-V2.5-MLX-AQ4_1_64 on the 7/09/2024, I suppose it was with mlx 0.17.2 at most? I can try 0.17.2 if you want, but since 0.17.1 works for me, maybe it happened between 0.17.2 and 0.17.3?

**Comment by awni** [comment]
Hi @M-I I'm having no trouble quantizing the Qwen 2 72B model this on my M1 Max with 32GB:

```
mlx_lm.convert --hf-path Qwen/Qwen2.5-72B-Instruct -q
```

So I'm wondering why you are having this issue and how to reproduce it. 
- Is your disk very full?
- Are you using the latest MLX LM?
- Do you have a lot of other stuff happening on your machine reading / writing to disk?

**Comment by M-I** [comment]
> Do you have a lot of other stuff happening on your machine reading / writing to disk?

Might be the issue. I had bought on an 1TB HDD specifically for this, Trying to convert Deepseek-V2.5 is the first thing I did on it. Maybe at some point there's a lot of random Read/Writes during conversion. This HDD doesn't handle that well at all (from 130MB/s sequential to ~10MB/s random, should have read the specs before buying it). 

I'll rerun it with a SSD and a HDD with better random R/W, see if it that was the issue.

right now, my working combo (pip freeze | grep mlx):
mlx==0.17.1
mlx-lm==0.18.2

**Comment by awni** [comment]
That makes sense now. Yea the HDD will be way slower :\ and is probably what's causing the timeout. If you have the space.. you could temporarily copy the model to your native SSD, quantize from there and then delete it.

**Comment by M-I** [comment]
The change in 0.18.0 fixed it. Thanks.
