### ISSUE TITLE
[Feature] Adding Truncated Normal

### ISSUE THREAD

**Issue by cvnad1** [ml-explore/mlx#1457]
I would like to add Trunc Normal similar to the implementation of [https://pytorch.org/docs/stable/_modules/torch/nn/init.html#trunc_normal_]

**Comment by awni** [comment]
There is a [truncated normal](https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.core.random.truncated_normal.html#mlx.core.random.truncated_normal) in MLX already.
