### ISSUE TITLE
[Feature] Sparse_ init

### ISSUE THREAD

**Issue by cvnad1** [ml-explore/mlx#1459]
Request to add Sparse_ initialization similar tohttps://pytorch.org/docs/stable/nn.init.html#torch.nn.init.sparse_. I have gone through the official documentation of MLX but couldn't find the above initialization method. I think it would be a good addition to MLX.

**Comment by cvnad1** [comment]
@awni May I know if the above has an update?

**Comment by awni** [comment]
We could put that initialization in our init package. I'll mark this as a feature request. Just curious, what do you intend to use it for?

**Comment by Saanidhyavats** [comment]
@awni We were experimenting with different initialization techniques and figured out that sparse init is not implemented. I think it  can be a good enhancement feature.

**Comment by cvnad1** [comment]
The PR is merged and hence closing the issue.
