### ISSUE TITLE
[BUG] Inconsistent softmax behavior with -inf inputs

### ISSUE THREAD

**Issue by JosefAlbers** [ml-explore/mlx#1467]
**Describe the bug**

There appears to be an inconsistency in the behavior of `mx.softmax()` when applied to arrays of zeros subtracted by infinity, depending on the array size.

**To Reproduce**

```python
>>> mx.softmax(mx.zeros((128,))-mx.inf)
array([nan, nan, nan, ..., nan, nan, nan], dtype=float32)

>>> mx.softmax(mx.zeros((127,))-mx.inf)
array([0, 0, 0, ..., 0, 0, 0], dtype=float32)
```

**Expected behavior**

The softmax function should handle -inf inputs consistently, regardless of the input array size. Both cases should ideally return an array of zeros, as e^(-inf) = 0 for all elements.

**Desktop**

 - OS Version: Sonoma 14.5 (2022 MacStudio 64GB M1 Max)
 - Version:  0.17.3 and 0.18.0

**Comment by awni** [comment]
Looks like a bug 👀
