### ISSUE TITLE
Best way to replace np.random.shuffle in MLX [FEATURE]

### ISSUE THREAD

**Issue by sck-at-ucy** [ml-explore/mlx#1469]
### Discussed in https://github.com/ml-explore/mlx/discussions/1466

<div type='discussions-op-text'>

<sup>Originally posted by **sck-at-ucy** October  7, 2024</sup>
I have been trying to refactor my physics-based Transformer code so that it all calls to numpy are removed and everything is implemented in MLX. I am almost there, a pure MLX implementation.  😀

In several places in the code I have been using np.random.shuffle() to randomize the generation of datasets (boundary conditions) and also during the loading of batches. My MLX solution has been the following , but I am wondering if this is the most efficient option or if I am missing a built-in option. Any insights from @awni would be appreciated. 

**Numpy implementation** 

```
    if synchronized_shuffling:
        combined = np.array(list(zip(left_bcs, right_bcs, top_bcs, bottom_bcs, alphas)))
        np.random.shuffle(combined)
        left_bcs, right_bcs, top_bcs, bottom_bcs, alphas = zip(*combined)
        left_bcs = np.array(left_bcs)
        right_bcs = np.array(right_bcs)
        top_bcs = np.array(top_bcs)
        bottom_bcs = np.array(bottom_bcs)
        alphas = np.array(alphas)
    else:
        np.random.shuffle(left_bcs)
        np.random.shuffle(right_bcs)
        np.random.shuffle(top_bcs)
        np.random.shuffle(bottom_bcs)
        np.random.shuffle(alphas)
```

**MLX Refactoring** 

 ```
   if synchronized_shuffling:
        # Stack the arrays along axis 1 (side by side, as columns)
        combined = mx.stack([left_bcs, right_bcs, top_bcs, bottom_bcs, alphas], axis=1)

        # Generate random indices for shuffling the samples
        num_samples_comb = combined.shape[0]  # Number of samples along the first axis
        indices = mx.random.randint(low=0, high=num_samples_comb, shape=(num_samples_comb,))

        # Reorder the combined array based on shuffled indices
        combined = combined[indices, :]  # Shuffle the rows (samples)

        # Use split to "unstack" the combined array (5 arrays, one for each boundary condition)
        left_bcs, right_bcs, top_bcs, bottom_bcs, alphas = mx.split(combined, 5, axis=1)

        # Squeeze to remove the extra dimension
        left_bcs = left_bcs.squeeze()
        right_bcs = right_bcs.squeeze()
        top_bcs = top_bcs.squeeze()
        bottom_bcs = bottom_bcs.squeeze()
        alphas = alphas.squeeze()

    else:
        # Generate random indices for shuffling each array independently
        indicesL = mx.random.randint(low=0, high=num_samples, shape=(num_samples,))
        indicesR = mx.random.randint(low=0, high=num_samples, shape=(num_samples,))
        indicesT = mx.random.randint(low=0, high=num_samples, shape=(num_samples,))
        indicesB = mx.random.randint(low=0, high=num_samples, shape=(num_samples,))
        indicesA = mx.random.randint(low=0, high=num_samples, shape=(num_samples,))

        # Reorder arrays based on the shuffled indices
        left_bcs = left_bcs[indicesL]
        right_bcs = right_bcs[indicesR]
        top_bcs = top_bcs[indicesT]
        bottom_bcs = bottom_bcs[indicesB]
        alphas = alphas[indicesA]
```</div>

**Comment by awni** [comment]
I'm not sure the MLX implementation is doing the same thing as the NumPy implementation. `np.random.shuffle` is like a random selection without replacement while the way you use `mx.random.randint` it is like a random selection with replacement. Could you clarify that?

I think we could implement a permutation fully in MLX using something like an argsort on uniform random numbers. If that's what you are looking for let us know.

**Comment by sck-at-ucy** [comment]
Thank you, now I can see that indeed my attempt at the MLX version is flawed. 

Want I am trying to achieve is to generate a number of arrays each created with  mx.linspace(0,1, num_samples) and then shuffle the order of the elements within the arrays randomly without replacement, either independently for each of the generated arrays or by using the same shuffling order in all arrays. The most interesting scenario for me is the one when each of the generated arrays is shuffled independently from the others, since this generates higher randomness in the datasets.

**Comment by sck-at-ucy** [comment]
I think this might work (based on your hints):

```
if synchronized_shuffling:
    # Generate random floating-point numbers uniformly distributed between 0 and 1
    random_floats = mx.random.uniform(low=0, high=1, shape=(left_bcs.shape[0],))
    
    # Use argsort to get a random permutation of indices based on the random floats
    indices = mx.argsort(random_floats)
    
    # Apply this random permutation to all the arrays in sync
    left_bcs, right_bcs, top_bcs, bottom_bcs, alphas = [array[indices] for array in [left_bcs, right_bcs, top_bcs, bottom_bcs, alphas]]
else:
    # Independent random shuffles (with different random permutations for each array)
    indicesL = mx.argsort(mx.random.uniform(low=0, high=1, shape=(left_bcs.shape[0],)))
    indicesR = mx.argsort(mx.random.uniform(low=0, high=1, shape=(right_bcs.shape[0],)))
    indicesT = mx.argsort(mx.random.uniform(low=0, high=1, shape=(top_bcs.shape[0],)))
    indicesB = mx.argsort(mx.random.uniform(low=0, high=1, shape=(bottom_bcs.shape[0],)))
    indicesA = mx.argsort(mx.random.uniform(low=0, high=1, shape=(alphas.shape[0],)))

    # Apply the independent random permutations to each array
    left_bcs = left_bcs[indicesL]
    right_bcs = right_bcs[indicesR]
    top_bcs = top_bcs[indicesT]
    bottom_bcs = bottom_bcs[indicesB]
    alphas = alphas[indicesA]
```

**Comment by awni** [comment]
@sck-at-ucy we added `mx.random.permutation` in the latest MLX. You can use that directly (it will be faster) than sorting uniform random numbers. Concretely:

```python
arrs = [left_bcs, right_bcs, top_bcs, bottom_bcs, alphas]
if synchronized_shuffling:
    indices = mx.random.permutation(left_bcs.shape[0])
    arrs = [a[indices] for a  in arrs]
else:
   arrs = map(mx.random.permutation, arrs)

left_bcs, right_bcs, top_bcs, bottom_bcs, alphas = arrs
```

**Comment by awni** [comment]
I think it's safe to close this, but let us know if you have any issues!

**Comment by sck-at-ucy** [comment]
This looks really good. I will try it. 

I guess my other wish list item would be boolean indexing, but I know that might be low priority in the scheme of things.

**Comment by awni** [comment]
It's not so much that it's low priority as that it's difficult to do in a general way in the asynchronous programming model. Have a [look at this doc](https://gist.github.com/awni/e20a288011adac0d0bdaf73e5296ca4f) on it if you haven't seen it. 

In my experience I've found for almost all use cases there is a good workaround that does not require it. There are some exceptions of course.

**Comment by sck-at-ucy** [comment]
Your code snippet looks so elegant, you have replaced 22 lines of my code with 7 lines 😀😀

**Comment by sck-at-ucy** [comment]
Tried it, works beautifully. Read the doc, makes perfect sense now.
