### ISSUE TITLE
SinusoidalPositionalEncoding has problem

### ISSUE THREAD

**Issue by Jyun1998** [ml-explore/mlx#147]
I am investigating transformer based architectures and SinusoidalPositionalEncoding in nn.layers.positioning_encoders have problem.

If you use rope on  [2, 16, 1024, 64] shape query, it well returns  [2, 16, 1024, 64]. 

However, using SinusoidalPositionalEncoding returns [2, 16, 1024, 64, 64].

This is due to concatenating not adding, so I will upload the fix mr!

By the way, do you want me to put fixed SinusoidalPositionalEncoding to MultiheadedAttention as well at the same PR?

I tested my fixed pos_encoder on mlx.nn.layer.transformer.MultiHeadAttention, and it's well working.

Thanks,

**Comment by angeloskath** [comment]
Hm, `SinusoidalPositionalEncoding` encodes each number provided while `RoPE` encodes the position of the vector so they are supposed to work differently.

For example given an input array of shape `BxNxD`, `RoPE` encodes positions 0 to N-1 by appropriately altering each `D`-dimensional vector. On the other hand `SinusoidalPositionalEncoding` encodes the value of each element in the array into a vector.

To get the same effect as in `RoPE` one would have to encode `mx.arange(x.shape[-2])` and then add it to `x` with appropriate broadcasting. Something like the following

```python
# x.shape == (B, N, D)
# pe is a SinusoidalPositionalEncoding that maps to D dimensions
x = x + pe(mx.arange(N))[None]
```

I will close the issue but feel free to reopen it if you still encounter issues.

**Comment by Jyun1998** [comment]
Yes, but still there's problem since you are concatenating not doing +.

```python 
class TransformerLM(nn.Module):
    def __init__(self, vocab_size: int, num_layers: int, dims: int, num_heads: int):
        super().__init__()
        self.my_encoder = transformer.MyPosEncoding(dims)
        self.your_encoder = nn.SinusoidalPositionalEncoding(dims)
        self.pos_encoder = self.my_encoder
        
        self.embedding = nn.Embedding(vocab_size, dims)
        self.transformer = transformer.TransformerEncoderWithDropout(num_layers, dims, num_heads)
        self.out_proj = nn.Linear(dims, vocab_size)
        self.dropout = nn.Dropout(0.1)
        
    def __call__(self, x):
        mask = nn.MultiHeadAttention.create_additive_causal_mask(x.shape[1])
        x = self.embedding(x)
        print(x.shape)
        x = self.pos_encoder(x)
        print(x.shape)
        x = self.transformer(x, mask)
        x = self.dropout(x)
        return self.out_proj(x)

    def loss(self, x, y, reduce=True):
        logits = self(x)
        losses = nn.losses.cross_entropy(logits, y)
        mx.simplify(losses)

        return mx.mean(losses) if reduce else mx.mean(losses, axis=(-1, -2))
```

I tried to use mlx-examples/transformer_lm.py as above and shown below results.

Thsi is from exactly same approach as pytorch document [link](https://pytorch.org/tutorials/beginner/transformer_tutorial.html) which seems more appropraite! What's different from pytorch encoding is I added self.cos_first and *self.scale since it was included in your code.

Please review and let's discuss what is more appropriate. 

```python
# original shape (x): [2, 1024, 1024]
# shape after SinusoidalPositionalEncoding (x) : [2, 1024, 1024, 1024]
# shape after my changed encoding (x) :  [2, 1024, 1024]

class MyPosEncoding(SinusoidalPositionalEncoding):
    def __init__(
        self,
        dims: int,
        min_freq: float = 0.0001,
        max_freq: float = 1,
        scale: Optional[float] = None,
        cos_first: bool = False,
        full_turns: bool = False,
    ):
        super().__init__(
            dims,
            min_freq=min_freq,
            max_freq=max_freq,
            scale=scale,
            cos_first=cos_first,
            full_turns=full_turns
        )
        self.dims = dims
    
    def __call__(self, x):
        seq_length = x.shape[1]  # Assuming x.shape [batch_size, sequence_length, embedding_dim]
        position = mx.arange(seq_length)[..., None] * self._sigmas
        
        # Generate positional encodings
        div_term = mx.exp(mx.arange(0, self.dims, 2) * -(math.log(10000.0) / self.dims))
        sinusoid_inp = position * div_term
        
        y = mx.zeros((seq_length, self.dims))
        if self.cos_first:
            y[:, 0::2] = mx.cos(sinusoid_inp) 
            y[:, 1::2] = mx.sin(sinusoid_inp) 
        else:
            y[:, 0::2] = mx.sin(sinusoid_inp) 
            y[:, 1::2] = mx.cos(sinusoid_inp) 
                    
        if self.scale != 1:
            y = y * self.scale

        return x + y

```

**Comment by Jyun1998** [comment]
@angeloskath Thanks for the review :)
