### ISSUE TITLE
[BUG] mlx.metal.capture is not supported

### ISSUE THREAD

**Issue by alexlatif** [ml-explore/mlx#1474]
**Description**
RuntimeError: [metal::start_capture] Failed to start: Capturing is not supported.

**Reproduce**
```python
mx.metal.start_capture("/tmp/mlx-metal-capture")
```

**Environment*
- MacOS 14.4.1 
- Xcode 15.4
- mlx 0.18.2

**Comment by awni** [comment]
You probably did not run with `MTL_CAPTURE_ENABLED=1`.

As in run `MTL_CAPTURE_ENABLED=1 python my_program.py`

Check [the docs](https://ml-explore.github.io/mlx/build/html/dev/metal_debugger.html) for more information.

Let me know if that's not the issue and we can re-open.

**Comment by alexlatif** [comment]
Understood, thank you, will try and lyk. Didn't see this in the docs.

**Comment by alexlatif** [comment]
Understood, thank you, will try and lyk. Didn't see this in the docs.
