### ISSUE TITLE
[Feature] Missing complex ops 

### ISSUE THREAD

**Issue by Leikoe** [ml-explore/mlx#1484]
**The problem**
Mlx supports complex number datatypes but almost none of the convinience ops to create them / destructure them.

**The proposed ops**
- mlx.core.polar(abs, angle) -> mx.array # creates an array of complex numbers given their respective abs and angle (like torch.polar)
- mlx.core.array.real() -> mx.array # returns the real value of each complex number in the array
- mlx.core.array.imag() -> mx.array # returns the imaginary value of each complex number in the array
[- a way to create an array of complex numbers given their real & imaginary values. Torch has torch.view_as_complex(arr), jax has jax.lax.complex(real, imag)]

**Comment by Leikoe** [comment]
some workarounds are here https://github.com/ml-explore/mlx/discussions/1331

**Comment by Leikoe** [comment]
related to https://github.com/ml-explore/mlx/issues/361

**Comment by awni** [comment]
I don't think we will add polar since it's not part of the array API spec and it's pretty easy to roll your own:

```python
def polar(a, b):
  return a * mx.exp(1j * b)
```
