### ISSUE TITLE
Choosing values from an mlx array based on indices and booleans with different input and output sizes

### ISSUE THREAD

**Issue by kyrollosyanny** [ml-explore/mlx#1489]
Hello, 

I am trying to write a custom image resizing algorithm in MLX. For example, let's try to do bilinear interpolation. One problem I am running into is that MLX cannot use booleans to access array information. For example, after I figure out how the  output pixels map to the input pixels, we need to assign the output pixel to input pixel based on some indices. 

Here is an example with a simple case, last line gives an error. 

The main issue here is that based on a mask, we want to return a smaller array of indices that we then use to fill in our new resized image. As I understand ```mx.where``` returns an output of the same shape. I know we can cast to numpy, do the masking, then recast again but then we lose differentiability. Is there a way to perform this last operation and retain differentiability?

```
original_img=mx.array(I)  ## input image to resize
old_h, old_w, c = original_img.shape
###new image size
new_h=300
new_w=500
#create an array of the desired shape. 
resized = mx.zeros((new_h, new_w, c))
#Calculate width and height scaling factors
w_scale_factor = (old_w ) / (new_w )# if new_h != 0 else 0
h_scale_factor = (old_h ) / (new_h )# if new_w != 0 else 0
i_arr=mx.arange(0,new_h)
j_arr=mx.arange(0,new_w)

J_arr,I_arr=mx.meshgrid(j_arr,i_arr)
#map the coordinates back to the original image
x_arr=I_arr*h_scale_factor
y_arr=J_arr*w_scale_factor

#calculate the coordinate values for 4 surrounding pixels.
x_floor = mx.floor(x_arr).astype(mx.int32)
x_ceil = mx.minimum( old_h - 1, mx.ceil(x_arr)).astype(mx.int32) 
y_floor = mx.floor(y_arr).astype(mx.int32) 
y_ceil = mx.minimum(old_w - 1, mx.ceil(y_arr)).astype(mx.int32) 

x_arr_int=np.int32(x_arr)
y_arr_int=np.int32(y_arr)

# ### case 1: the pixel is an exact match
case1=(x_ceil==x_floor) & (y_ceil==y_floor)

resized[case1,:]= original_img[x_arr_int[case1], y_arr_int[case1], :]
```

_Originally posted by @kyrollosyanny in https://github.com/ml-explore/mlx/discussions/1487_

**Comment by kyrollosyanny** [comment]
Perfect that's exactly what I was looking for. Thank you.

**Comment by nassuphis** [comment]
this does it, but its silly. 

```

def mlx_which(x: mx.array,*,stream=mx.gpu):
     if x.size == 0:
        return mx.empty((0,), dtype=mx.int32, stream=stream)
     xb  = x.astype(mx.int64)
     xb[0] = 0
     ar = mx.arange(x.size, dtype=mx.int32, stream=stream)
     xi = mx.cummax(ar * xb)
     cum = mx.cumsum(xb, stream=stream)
     maxi = cum[-1].item() + 1
     idx = mx.zeros((maxi,), dtype=mx.int32, stream=stream)
     idx[cum]=xi
     if x[0]:
        return idx
     return idx[1:]
```
print(f" which: {mlx_which(mx.array([False, False, False], dtype=mx.bool_))}")
 which: array([], dtype=int32)
print(f" which: {mlx_which(mx.array([False, True, False, True], dtype=mx.bool_))}")
 which: array([1, 3], dtype=int32)
print(f" which: {mlx_which(mx.array([True, True, False, True], dtype=mx.bool_))}")
 which: array([0, 1, 3], dtype=int32)
