### ISSUE TITLE
Question: migrating existing projects that use NumPy to use MLX

### ISSUE THREAD

**Issue by Alino** [ml-explore/mlx#153]
Hi there, I was playing around with SDXL models via Fooocus and the performance there on m1 pro is terrible and I was trying to find a way to optimise that and found out this recently published library exists.

I was wondering if projects such as Fooocus that are using NumPy could use some kind of universal wrapper around NumPy and MLX which would be easily implementable.

Here is my naive idea pseudo code:

```python
import platform
import numpy as original_np

try:
    import mlx.core as ml_np
    mlx_available = True
except ImportError:
    mlx_available = False


def is_apple_silicon():
    return platform.machine() == 'arm64' and platform.system() == 'Darwin'


class NumpyMLXWrapper:
    def __init__(self):
        self.use_mlx = is_apple_silicon() and mlx_available

    def __getattr__(self, name):
        def method(*args, **kwargs):
            if self.use_mlx:
                # Try MLX first
                try:
                    return getattr(ml_np, name)(*args, **kwargs)
                except AttributeError:
                    pass
            # Fallback to NumPy
            return getattr(original_np, name)(*args, **kwargs)
        return method


np = NumpyMLXWrapper()
```

and then the projects would instead of this
```python
import numpy as np
```

do this
```python
import numpy_mlx_wrapper as np
```

Is this something that makes sense to do, and would likely gain a performance boost?

**Comment by awni** [comment]
That's cool. You could definitely try something like that. We try to keep the MLX API consistent with NumPy so ideally you one day you could do `import mlx as np`. But that likely won't work as we are still missing a lot of ops so your solution seems like a good workaround.

If the computation is FLOP-bound you will almost certainly see a performance boost using the GPU. Hard to say in the general case though.

The other thing to be cognizant of is that MLX is lazy and you need to have `mlx.eval` every now and then for really large compute graphs. Note this will implicitly be done whenever you print an array, or convert it to a list or a numpy array.

**Comment by awni** [comment]
Also, if you go that route, let us know how it works and what kind of performance you see. If there are some ops that are really slow that would be great to know about so we can optimize them.

**Comment by Alino** [comment]
Thank you for the answer, I will let you know potential results if I get my hands on this.

One follow up question:

> MLX has higher-level packages like mlx.nn and mlx.optimizers with APIs that closely follow PyTorch to simplify building more complex models.

Does this mean that you are also planning mimicking the API of PyTorch? Would we be able to use such wrapper as I shown for NumPy for PyTorch too?

**Comment by awni** [comment]
Our higher level `nn` and `optimizers` packages are mostly (but not quite) subsets of PyTorch.  You might be able to get away with `import mlx.nn as nn` instead of `torch.nn` in some cases. But in general it will be difficult to do a wrapper like that for PyTorch with MLX though as the array ops are NumPy style so any time you descend from `nn` to something a little lower level things likely will break.
