### ISSUE TITLE
[DOCS] Incomplete mlx.core.fast.metal_kernel

### ISSUE THREAD

**Issue by Leikoe** [ml-explore/mlx#1547]
**Describe the bug**

While writing a custom kernel using mlx.core.fast's metal_kernel() function, I found myself looking through mlx's source code multiple times. 
It wasn't clear that the grid argument to provide the created callable is for the `dispatchThreads` and not `dispatchThreadgroups` underlying call.

**Expected behavior**

The mlx.core.fast.metal_kernel's docs page should include info like the used attribute detection & other which are mentionned in the custom_metal_kernels guide OR a link to the custom_metal_kernels guide.
It should also be mentionned that the grid attribute is the grid size in Threads and not Threadgroups.

**Comment by awni** [comment]
We should include the docstring for the returned kernel in the documentation as well. It has a pretty comprehensive [docstring](https://github.com/ml-explore/mlx/blob/main/python/src/fast.cpp#L271-L292) (which we can clarify in cases that are unclear like the grid). But right now it's not in the docs.

**Comment by barronalex** [comment]
Thanks for pointing this out! I'll update the docs this afternoon.
