### ISSUE TITLE
[Question] Masked SDPA attention kernel?

### ISSUE THREAD

**Issue by EricLBuehler** [ml-explore/mlx#1582]
Hello MLX team!

Thank you for your excellent work here. We have been focusing on accelerating Candle performance on Metal and recently integrated [some fast SDPA kernels from MLX](https://github.com/huggingface/candle/pull/2584)!

I noticed that the [scaled_dot_product_attention.metal](https://github.com/ml-explore/mlx/blob/main/mlx/backend/metal/kernels/scaled_dot_product_attention.metal) file does not contain kernels for causal, non-decode step kernels. This seems to prohibit their usage in the prompt step for models such as Llama, and the fallback code for the SDPA op seems to indicate so.

Are there any plans to add masking support to the [full SDPA kernel](https://github.com/ml-explore/mlx/blob/dfa0b9aab427a28139c54ebeb9564ff35c35d758/mlx/backend/metal/kernels/scaled_dot_product_attention.metal#L648-L662) or current methods that have been taken to accelerate the prompt step?

**Comment by awni** [comment]
> Are there any plans to add masking support to the full SDPA kernel or current methods that have been taken to accelerate the prompt step?

This is a work in progress. @jagrit06 has been working on that. We're hoping to ship something soon, but I can't give you an exact timeline yet.

**Comment by awni** [comment]
Closing as a dup of https://github.com/ml-explore/mlx/issues/129
