### ISSUE TITLE
Follow vjp convention of Jax/Torch

### ISSUE THREAD

**Issue by PhilipVinc** [ml-explore/mlx#160]
Your `vjp` API definition is such that it takes as input the function, the primal and cotangents and returns the function evaluations and the evaluated vjp.

This API is different than that of Jax, later adopted by torch, of returning a function that takes the cotangents and can be evaluated multiple times.

This design is more flexible computationally speaking (I might want to pull back multiple cotangents vectors) and would allow easier interoperability of libraries wishing to support MLX as an alternative backend to Jax and torch.

Moreover, it would make it easier to just change the imports from Jax to mlx for relatively simple codes.

**Comment by awni** [comment]
We modified this intentionally from `Jax` as it makes sense for `vjp` and `jvp` to have a consistent API (which they do not in Jax).

If you need this behavior, you can do it with a simple wrapper:

```
def vjp_wrap(cotans):
  return mx.vjp(fun, primals, cotans)
```

**Comment by PhilipVinc** [comment]
The counterpart of `jax.vjp` is `jax.linearize`, not `jax.jvp`. 
It is common to find oneself has to pullback different co-vectors for the same primals. In code, 

```python
out, vjp_fun = jax.vjp(fun, primals)

grad_1 = vjp_fun(v1)
grad_2 = vjp_fun(v2)
```

(Same thing with `jax.linearize` and `jax.jvp`, where jax.linearize allows you to push forward multiple tangent vectors).

While I agree that from an API point of view that is not 100% consistent, I suspect that jax developers might have had an argument for this.

If you want this software to be recommended in classes, I'd invite you to consider interoperability like PyTorch did. 
if you want scientific users to play with your software I think there is value in accepting existing standards.
