### ISSUE TITLE
[Question] What should each dimension of the inputs to `mx.fast.rope` be?

### ISSUE THREAD

**Issue by dolphingarlic** [ml-explore/mlx#1621]
I'm trying to convert some Pytorch code into MLX, but I'm having trouble getting `mx.fast.rope` to play nicely. My current code uses the [`LlamaRotaryEmbedding` from HuggingFace's transformers](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L148-L168) and behaves as follows:
* First, it takes in a tensor of `position_ids` with shape `[batch_size, seq_len]`.
* Next, it multiplies `position_ids` with a stored `inv_freq` tensor to get `freqs` with shape `[batch_size, seq_len, head_size // 2]`.
* Next, it concatenates `freqs` with itself and takes the sin/cos to get two tensors with shape `[batch_size, seq_len, head_size]`.
* Finally, it applies the rotary position embedding to tensors `q` and `k` with shape `[batch_size, n_heads, seq_len, head_size]` and gets output tensors of the same shape.

I initially tried using `mx.fast.rope` with `a=q` and `freqs=freqs`, but MLX expects `freqs` to be a 1D array and `a` to have at least three dimensions. I tried playing around with transposing and flattening the input arrays, but nothing seemed to work.

Is there a way for me to use `mx.fast.rope` with this setup, or would I be better-off implementing RoPE manually?

**Comment by awni** [comment]
You shouldn't need to use `mx.fast.rope` directly. You can just use [`nn.RoPE`](https://ml-explore.github.io/mlx/build/html/python/nn/_autosummary/mlx.nn.RoPE.html). See the [Llama](https://github.com/ml-explore/mlx-examples/blob/main/llms/llama/llama.py#L47-L49) example.


You instantiate it like this:

```python
rope = nn.RoPE(head_dim, traditional=False, base=rope_theta)
```

And call it like this:
```python
queries = self.rope(queries, offset=offset)
keys = self.rope(keys, offset=offset)
```

The `offset` is used to apply rope starting at position `offset` instead of position 0, for example when doing autoregressive decoding with a cache.

**Comment by dolphingarlic** [comment]
How can I use `position_ids` or a custom list of frequencies with `nn.RoPE`?

**Comment by awni** [comment]
You can pass custom frequencies to `mx.fast.rope` using the [`freqs`](https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.core.fast.rope.html#mlx.core.fast.rope) parameter. You can't pass position ids to either `nn.RoPE` or `mx.fast.rope`.
