### ISSUE TITLE
[Features] adding nonzero | where with single input 

### ISSUE THREAD

**Issue by guillaume-osmo** [ml-explore/mlx#1641]
Can we add now numpy.nonzero and numpy.where with single input equivalents ?

**Comment by awni** [comment]
Check-out https://github.com/ml-explore/mlx/issues/860 and https://github.com/ml-explore/mlx/issues/568 and https://github.com/ml-explore/mlx/issues/246.

For more information on why we aren't planning to add this and possible work arounds check out [the docs](https://ml-explore.github.io/mlx/build/html/usage/indexing.html#differences-from-numpy) and [this gist](https://gist.github.com/awni/e20a288011adac0d0bdaf73e5296ca4f).
