### ISSUE TITLE
[Feature Request] Make the whole project work as a backend for pytorch

### ISSUE THREAD

**Issue by ytgui** [ml-explore/mlx#165]
It’s 2024, you guys should implement backends (Apple Silicon specific operators) for pytorch and onnxruntime instead of reinventing the wheel.

Example - Dead and unmaintained DL framework: https://github.com/apache/mxnet

**Comment by RahulBhalley** [comment]
They have `mps` backend for PyTorch already. Although I agree with you a little for having single library but the best optimization for Apple Silicon can only be done by Apple.

**Comment by awni** [comment]
See issues #12
