### ISSUE TITLE
Comparison with llama.cpp and GGML

### ISSUE THREAD

**Issue by staghado** [ml-explore/mlx#17]
I wonder how this compares to llama.cpp for example in terms of performance in the same settings?

**Comment by cyrusmsk** [comment]
On my tests GGML gemm is slower.
Like ggml ~ 1.5 TFlops, and mlx (quite close to PyTorch) ~ 3.5 TFlops on M1 Pro (32 Gb).
Of course llama is not only gemm, but you can estimate

**Comment by awni** [comment]
I think we can close this. MLX should be as fast or faster for most LLMs compared to llama.cpp.
