### ISSUE TITLE
regression test failure on macos intel runs

### ISSUE THREAD

**Issue by chenrui333** [ml-explore/mlx#1713]
👋 trying to build the latest release, but run into some regression test issue. The error log is as below:

<details>
<summary>regression test log</summary>

```
  ==> /usr/bin/clang++ test.cpp -std=c++17 -I/usr/local/Cellar/mlx/0.21.1/include -L/usr/local/Cellar/mlx/0.21.1/lib -lmlx -o test
  ==> ./test
  ==> python3.13 test.py
  Traceback (most recent call last):
    File "/private/tmp/mlx-test-20241207-14040-i4lr7y/test.py", line 3, in <module>
      assert mx.cos(x) == 1.0
             ^^^^^^^^^^^^^^^^
  AssertionError
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/12207413864/job/34063910203?pr=161270
relates to Homebrew/homebrew-core#200351

**Comment by awni** [comment]
This looks like a testing issue probably exposed by a recent switch to using accelerate for the intel back-end as well:

```python
>>> mx.cos(x, stream=mx.cpu).item()
0.9999999403953552
```

In general I would us `mx.allclose` rather than test exact match when dealing with floating point numbers. So change your test to:

```
assert mx.allclose(mx.cos(x), mx.array(1.0))
```
