### ISSUE TITLE
Support for einops

### ISSUE THREAD

**Issue by gboduljak** [ml-explore/mlx#172]
Hi :)

I am a big fan of **einops** and I believe that supporting it within the framework would be highly valuable, especially for quick prototyping and situations where performance isn't the primary focus. Are there any plans to implement a feature akin to **torch.einsum** within the framework? If there's a plan for something like mlx.einsum and contributions are welcome, I'd be eager to contribute.

**Comment by gboduljak** [comment]
It seems that Apple MLX support [was already proposed](https://github.com/arogozhnikov/einops/issues/295) within [einops](https://github.com/arogozhnikov/einops).

**Comment by sck-at-ucy** [comment]
I second that. einops saved me quite a few times where the logic was becoming a bit intractable.

**Comment by awni** [comment]
We'll definitely keep this on the feature roadmap. I think if we had an einsum like NumPY integration with einops is doable. (Contributions welcome!)

**Comment by dc-dc-dc** [comment]
Will also need a tile op to support einops

**Comment by dc-dc-dc** [comment]
After #278 and #240 get merged, that should be all thats needed to create a backend for einops

**Comment by arogozhnikov** [comment]
Einops maintainer here.

Simplest way to get einops functions for framework is to implement [array api](https://data-apis.org/array-api/2022.12/). 
`einops.array_api` works with all array-api compatible tensors (there is also support for `scikit-learn` and `eindex`).

It also simplifies prioritization of ops a lot for framework devs, as what's in the standard is a bare minimum.

**Comment by awni** [comment]
We can close this as the latest MLX works with `einops.array_api` back-end.

**Comment by ifsheldon** [comment]
Hi! I'm running this code, trying to use `einops.einsum` with `mx.array`, but it doesn't work. So, einsum is still not supported?

```python
a = mx.random.normal([2, 3])
b = mx.random.normal([4, 5])

kron1 = mx.kron(a, b)
kron2 = einsum(a, b, "a b, c d -> a c b d")
kron2 = rearrange(kron2, "a c b d -> (a c) (b d)")

```

**Comment by awni** [comment]
It looks like the `einops.array_api` package doesn't have einsm, so you'd need to use MLXs `einsum` and then the `rearrange` from `einops.array_api` that like so:

```python
import mlx.core as mx
from einops.array_api import rearrange
a = mx.random.normal([2, 3])
b = mx.random.normal([4, 5])

kron1 = mx.kron(a, b)
kron2 = mx.einsum("a b, c d -> a c b d", a, b)
kron2 = rearrange(kron2, "a c b d -> (a c) (b d)")
```

**Comment by ifsheldon** [comment]
OK, I filed a [PR](https://github.com/arogozhnikov/einops/pull/376) to that repo a few hours ago. Thanks!
