### ISSUE TITLE
make nn.Linear documentation less obtuse

### ISSUE THREAD

**Issue by wjessup** [ml-explore/mlx#180]
https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.nn.Linear.html
 "Applies an affine transformation to the input." 

An affine transformation doesn't tell me what this does. It could be a translation, rotation, scaling, etc.

What this actually does is matrix multiplication followed by bias addition. Can we just say it clearly?

**Comment by awni** [comment]
Adressed in #198
