### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by tmc** [ml-explore/mlx#19]
Is there aversion to including type annotations in the python implementation?

While the python interpreter doesn’t directly check/enforce type annotations it can have a non-trivial impact on developer experience to have well-typed libraries. 

https://typing.readthedocs.io/en/latest/

**Comment by awni** [comment]
Could you be more specific?

Most of the python API is built with pybind11 which includes types in the function signatures (`help(mx.add)` should show you the types.

The part that is written in python includes type annotations for the most part and we are happy to add / accept contributions where missing.

**Comment by danilopeixoto** [comment]
@awni While this problem might not be directly related to the issue, I wanted to share my following experience:

When installing the `mlx` package using `pip install mlx==0.0.10` and importing the `mlx.core` module in VSCode for MacOS, I cannot access type annotations. I had to manually generate the `mlx.core` stubs and then copy them to the `mlx` package folder. Unfortunately, the type annotations for the `mlx.core` module didn't seem to work out of the box for me.

Should we include the `*.pyi` files as `package_data`?

**Comment by awni** [comment]
Hmm that's a good point. We could potentially include them in the pypi wheels 🤔

**Comment by danilopeixoto** [comment]
@awni Would you provide recommendations for simplifying or updating the CI process to support stubs, in addition to the draft version specified below?

```yaml
  build_release:
    machine: true
    resource_class: ml-explore/m-builder
    parameters:
      python_version:
        type: string
        default: "3.9"
      macos_version:
        type: string
        default: "14"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            eval "$(conda shell.bash hook)"
            rm -r $CONDA_PREFIX/envs/runner-env
            conda create -y -n runner-env python=<< parameters.python_version >>
            conda activate runner-env
            pip install --upgrade cmake
            pip install --upgrade pybind11[global]
            pip install pybind11-stubgen
            pip install numpy
            pip install twine
      - run:
          name: Build python package
          command: |
            eval "$(conda shell.bash hook)"
            conda activate runner-env
            DEVELOPER_DIR=$(developer_dir_macos_<< parameters.macos_version >>) \
              PYPI_RELEASE=1 \
              CMAKE_BUILD_PARALLEL_LEVEL="" \
              python setup.py build_ext
            DEVELOPER_DIR=$(developer_dir_macos_<< parameters.macos_version >>) \
              PYPI_RELEASE=1 \
              CMAKE_BUILD_PARALLEL_LEVEL="" \
              python setup.py install
      - run:
          name: Generate stubs
          command: |
            eval "$(conda shell.bash hook)"
            conda activate runner-env
            python setup.py generate_stubs
      - run:
          name: Publish python package
          command: |
            eval "$(conda shell.bash hook)"
            conda activate runner-env
            DEVELOPER_DIR=$(developer_dir_macos_<< parameters.macos_version >>) \
              PYPI_RELEASE=1 \
              CMAKE_BUILD_PARALLEL_LEVEL="" \
              python setup.py bdist_wheel
            twine upload dist/* --repository mlx
      - store_artifacts:
          path: dist/
```

I would greatly appreciate any suggestions or insights you may have for simplifying or optimizing this CI configuration.
