### ISSUE TITLE
MLP example doc does not include custom mnist module

### ISSUE THREAD

**Issue by loboyd** [ml-explore/mlx#191]
The [MLP example documentation](https://ml-explore.github.io/mlx/build/html/examples/mlp.html) makes use of a custom MNIST loader (https://github.com/ml-explore/mlx-examples/blob/main/mnist/mnist.py), and does not run as written. This is not obvious from following along with the doc. It is particularly confusing because there is a PyPI package of the same name.

**Comment by awni** [comment]
Thanks for the input, will update it.

**Comment by awni** [comment]
Addressed in #198
