### ISSUE TITLE
Implement AdamW

### ISSUE THREAD

**Issue by gboduljak** [ml-explore/mlx#192]
I would like to implement AdamW. Any thoughts?

AdamW Paper: https://arxiv.org/abs/1711.05101

**Comment by awni** [comment]
It was added in #72 ! It might not have made it to the docs but it should be available in v0.0..5

**Comment by gboduljak** [comment]
Thanks for the explanation. I looked at the docs but was not able to find AdamW.

**Comment by awni** [comment]
It’s there now https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.optimizers.AdamW.html
