### ISSUE TITLE
Issue building and installing: "error:unable to find utility "metal", not a developer tool or in PATH"

### ISSUE THREAD

**Issue by ctrtrends** [ml-explore/mlx#193]
Hey, I have a problem 

I followed the steps in the documentation but I get these errors:
ERROR: Could not build wheels for mlx, which is required to install pyproject.toml-based projectscd .
error: unable to find utility "metal", not a developer tool or in PATH

What steps do I need to take to resolve it?

**Comment by ctrtrends** [comment]
<img width="574" alt="image" src="https://github.com/ml-explore/mlx/assets/149938201/d356e77a-d41f-485a-b26d-c30e7db25361">
this fixed it

**Comment by awni** [comment]
Could you share the link where you found that? I'd like to link to it in the docs :)

**Comment by ctrtrends** [comment]
Thats the ChatGPT interface. I just asked it about the errors
