### ISSUE TITLE
No sine and bessel functions in documentation? 

### ISSUE THREAD

**Issue by power9799** [ml-explore/mlx#21]
Can you add more mps accelerated functions to mlx like sine, cosine, bessel functions?

**Comment by awni** [comment]
We have sine, cosine etc

https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.core.sin.html#mlx.core.sin
https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.core.cos.html#mlx.core.cos

**Comment by benjaminpope** [comment]
If we had Bessels this would be a huge thing for physics applications. Bit of a hole in Jax for special functions that are essential in physics. https://github.com/google/jax/pull/17038#issuecomment-1773509565
