### ISSUE TITLE
`pip install mlx` not working

### ISSUE THREAD

**Issue by Lord-of-Bugs** [ml-explore/mlx#212]
This is what I did: `pip install mlx` 
And here is the error message I'm receiving:
```
ERROR: Could not find a version that satisfies the requirement mlx (from versions: none)
ERROR: No matching distribution found for mlx
```
I'm on the 2023 MacBook Pro with M2 Max. Is this a machine-issue?

**Comment by awni** [comment]
See top section of #200. Let us know if you are still having problems after that.
