### ISSUE TITLE
Stack function not available

### ISSUE THREAD

**Issue by BasBuller** [ml-explore/mlx#219]
When trying to call the following piece of code:

```
import mlx.core as mx

arrays = [mx.zeros(shape=(16,)), mx.zeros(shape=(16,))]
array = mx.stack(arrays)
```

I get the following error: `AttributeError: module 'mlx.core' has no attribute 'stack'`

My mlx is version is 0.0.5

**Comment by awni** [comment]
`mlx.stack` will be in `v0.0.6`. You could also use the pre-release distribution (I think stack is in there):
```
pip install mlx==0.0.5.dev20231217
```
