### ISSUE TITLE
Test passes from command line, but fails in Xcode

### ISSUE THREAD

**Issue by dougdew64** [ml-explore/mlx#220]
When I run tests from the command line with `make test` then I receive a report that all tests have passed.

However, when I attempt to run tests from within Xcode, the very first test fails due to the test's attempt to allocate a zero-length buffer. 

It seems surprising to me that the test's attempt to allocate a zero-length buffer would sometimes be acceptable and sometimes not be acceptable.

![image](https://github.com/ml-explore/mlx/assets/98898390/42b05639-d7f7-4fd6-90d5-6fc0912c8644)

**Comment by dougdew64** [comment]
Also, it seems that it's not possible to progress to the second test when the first test fails. Instead, every time that I press the Continue button, Xcode simply reports the same exception again. The exception seems not to be thrown up to the try/catch block in doctest.h.

**Comment by dougdew64** [comment]
The exception is being thrown by the debug MTL gpu device. I'd assume that the debug device would perform stricter error checking than the release device. Is it possible that when running `make test` the release device is used?

**Comment by dougdew64** [comment]
If I filter the tests to run only the argmin and argmax edge case tests which are in arg_reduce_tests.cpp, then I experience the same error which I had reported in my own code in a different issue.

![image](https://github.com/ml-explore/mlx/assets/98898390/71dc4222-b0c7-4255-b781-4a3f219fdbc4)

**Comment by dougdew64** [comment]
Debugging a bit more, it seems that the logic in primitives.cpp is requesting that MTL set a zero-length buffer: 
![image](https://github.com/ml-explore/mlx/assets/98898390/67d7d968-1c18-4470-a1be-38a3154dac16)

**Comment by dougdew64** [comment]
Although the MTL docs don't say so, I'm guessing that the debug MTL device performs extra validation which decides to not create a buffer when the request is for a zero-length buffer.

https://developer.apple.com/documentation/metal/mtlcomputecommandencoder/1443159-setbytes

**Comment by dougdew64** [comment]
My hunch about this being a difference in the MTL devices (debug versus release) is wrong. That `shape` buffer is being used in arg_reduce.metal, and in the elem_to_loc function which is ultimately called by the kernel.

![image](https://github.com/ml-explore/mlx/assets/98898390/e3f4f4fa-6bcd-4e71-9857-0bea098eccf0)

**Comment by dougdew64** [comment]
@awni I just noticed that `shape` never actually gets used in `elem_to_loc` for `argmax` or `argmin` because `ndim` is always zero for those two functions, so the loop condition in `elem_to_loc` never evaluates to true.

So, it actually is possible that the failures which I reported are due to verification of buffer arguments being performed by a debug MTL device that is not being performed by the MTL device which is being used when running `make test`.

![image](https://github.com/ml-explore/mlx/assets/98898390/9e450014-c631-4cc3-af91-72635fc2f36a)

**Comment by dougdew64** [comment]
I'm attempting a test with a release build now to confirm...

**Comment by dougdew64** [comment]
My hunch about MTL verification was correct. It turns out that there's a setting in Xcode to enable / disable MTL validation. If I have that setting enabled, then my code which calls MLX's argmax fails. If I disable that setting, then my code succeeds.

![image](https://github.com/ml-explore/mlx/assets/98898390/4419c93b-635b-4131-8c98-fca789f6fe71)

**Comment by awni** [comment]
@dougdew64 sorry I somehow missed this thread 😓 .  There is an issue filed #410 on this exact problem. I think the warnings in this case are about benign issues, but will still plan to get validation to pass for future Xcode users.

**Comment by awni** [comment]
This is fixed.
