### ISSUE TITLE
Implement tensor axes permutation/transposition

### ISSUE THREAD

**Issue by gboduljak** [ml-explore/mlx#223]
In many use cases, it is convenient to have a method to permute the axes of a tensor. For example, this is very useful for implementing ViT. Are there any plans to implement a method analogous to `torch.permute`? I would be willing to contribute to this implementation. I think it is appropriate to implement `permute` as a `primitive`.  However, I am not an expert in Metal GPU programming and I would need a bit of guidance on how to work with strides.

**Comment by gboduljak** [comment]
It is already implemented: `mlx.core.transpose`.

**Comment by awni** [comment]
You beat me to it, was just about to comment :)
