### ISSUE TITLE
Support for pooling layers for CNNs, e.g. MaxPool2d 

### ISSUE THREAD

**Issue by menzHSE** [ml-explore/mlx#25]
Thanks to the mlx team for creating and sharing mlx. 

I have managed to get a small CIFAR-10 image classification CNN up and running rather quickly in mlx (inspired by the PyTorch CIFAR-10 tutorial). I have found that pooling layers (e.g. MaxPool2D) are not available yet. I hope that they will be available in the next release(s). 

Code is here: https://github.com/menzHSE/mlx-cifar-10-cnn 
Heavily borrows from the mnist example in mlx (https://github.com/ml-explore/mlx-examples/tree/main/mnist)

**Comment by robertmccraith** [comment]
I have implemented some CNN layers here: [https://github.com/robertmccraith/mimm](https://github.com/robertmccraith/mimm)
More models to be implemented over time, feel free to contribute
