### ISSUE TITLE
linalg matrix norm

### ISSUE THREAD

**Issue by nullhook** [ml-explore/mlx#259]
need a function to compute matrix norm and by default it should be Frobenius norm.

does this exist? assuming not, because linalg namespace isn't available yet.

**Comment by awni** [comment]
Not yet. For a frobenius norm you can do:

`mx.sqrt(mx.sum(mx.square(matrix)))`

Other norms are more complicated.

Closing as dup of #24 which is being addressed in #187.  If there are specific norms you need other than Frobenius, feel free to file an issue for them.

**Comment by awni** [comment]
I think the way the [Mixtral model](https://github.com/ml-explore/mlx-examples/blob/main/llms/mixtral/convert.py#L48-L89) does quantization might solve this already. It operates only on shards (the non `eval`ed arrays are never materialized.

Take a look you might be able to mostly reuse that as is. If you are up for giving that a go, that woud be awesome! If not, maybe we can find a way to include your changes (when not quantizing) and o/w load the full model.
