### ISSUE TITLE
alternatives to `torch.gather` and `Tensor.scatter_` ?

### ISSUE THREAD

**Issue by mzbac** [ml-explore/mlx#265]
While I am trying to replicate  the repetition_penalty for mlx LLM example, I noticed that mlx does not have torch.gather and tensor.scatter. wondering if anyone has any clue about the alternatives to those PyTorch APIs.
FYI, I tried to replicate the repetition_penalty in transformers here: https://github.com/huggingface/transformers/blob/main/src/transformers/generation/logits_process.py#L331-L338

**Comment by awni** [comment]
For the most part you can use fancy indexing / take / take_along_axes for scatter and gather. 

So for a scatter `a[idx1, idx2] = b`, for a gather `a = b[idx1, idx2]`.

**Comment by awni** [comment]
I will add a page to the docs on this with more details as it is not covered in the docs at all. If that doesn't work for you ruse case lmk!

We also have `take` and `take_along_axis` which may be helpful for you (see the docs).

**Comment by mzbac** [comment]
Thanks for the advice, much appreciated.

**Comment by mzbac** [comment]
Close this for now. Since it's implemented using indexing as suggested, here is my implementation in case anyone else encounters the same issue. https://github.com/mzbac/mlx-examples/blob/deepseek-coder/llms/deepseek-coder/deepseek_coder.py#L217-L224

**Comment by llllvvuu** [comment]
Is there an example of how to scatter in this case?

```
>>> a = mx.array([[10,11,12,13],[20,21,22,23]])
>>> b = mx.array([[0,1],[2,3]])
>>> c = mx.array([[100,101],[200,201]])
>>> a[b] = c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Shapes (2,2) and (2,2,4) cannot be broadcast.
>>> # want: mx.array([[100,101,12,13],[20,21,200,201]])
```

**Comment by awni** [comment]
```python
a = mx.array([[10,11,12,13],[20,21,22,23]])
i = mx.array([0, 1])[:, None]
j = mx.array([[0, 1], [2, 3]])
c = mx.array([[100,101],[200,201]])
a[i, j] = c
```

The [numpy docs on fancy indexing](https://numpy.org/doc/stable/user/basics.indexing.html#) are good place to learn more about how this works (MLX follows that for get and set indexing). It's quite powerful but can be a bit subtle..
