### ISSUE TITLE
Examples don't exist, link forwards to wrong place

### ISSUE THREAD

**Issue by artificalaudio** [ml-explore/mlx#28]
See end of this tutorial:

https://ml-explore.github.io/mlx/build/html/examples/llama-inference.html

the link after "The full example code is available in" directs to the wrong place. (https://ml-explore.github.io/mlx/build/html/examples/code)

it should be directed to here https://github.com/ml-explore/mlx/tree/main/examples

There's also no examples of the transformer LLM/llama inference in either python or Cpp folders: https://github.com/ml-explore/mlx/tree/main/examples/python

Could you please add examples for both py + C++?

**Comment by jagrit06** [comment]
Yes, I'll add a fix for the links right away 
In the meantime, most of the python example code is in this repo https://github.com/ml-explore/mlx-examples

**Comment by awni** [comment]
Docs are updated. Thanks for catching this.
