### ISSUE TITLE
localfold(alphafold) huge swap

### ISSUE THREAD

**Issue by ChrisLou-bioinfo** [ml-explore/mlx#283]
Use Jax-mlx on M1max（64Gb），a 2000+ AA was predicted along with 70Gb swap and then Mac auto-shout down.
Maybe use more GPU threads?
How to control the thread of GPU in this case

**Comment by awni** [comment]
Could you say more about the use case? What is local fold? What is Jax-mlx?

**Comment by ChrisLou-bioinfo** [comment]
just following：

https://github.com/google-deepmind/alphafold/issues/604

**Comment by awni** [comment]
Got it. That’s an independent project, unrelated to MLX as far as I can tell.

(The Metal backend for Jax is unrelated to MLX)
