### ISSUE TITLE
MLX Stable Diffusion Encoding/Decoding Input Image

### ISSUE THREAD

**Issue by sck-at-ucy** [ml-explore/mlx#286]
This is a feature question, probably reflecting my limited experience on the subject rather than an MLX limitation.  I am trying to modify the MLX SD example to accept an input image, encode the image to generate its latent that will then be blended with the model generated latents. Basically, to do something like the Hugging Face image-to-image model. First of all, I am not sure if this makes sense (comments welcome). But the practical issue I am facing is that if I encode the image using the Autoencoder (imported from vae) and then decode the latent back to an image (without any steps), I get more or less that correct image but it looks washed out,  as if it were missing some channel information. I tried playing with various Autoenconder configuration parameters but I have not been able to converge. 

So two questions: 

1. Does what I am trying to do make sense? 
2. Where should I look for the Enconder options I should be using. The input image is a 512x512 RGB (png).

```
 #.... omitted inputs etc.
 
sd = StableDiffusion()
    
# Load the pre-trained autoencoder

config = AutoencoderConfig(
        in_channels=3,  # Number of input channels (e.g., 3 for RGB images)
        out_channels=3,  # Number of output channels
        latent_channels_in=4,  # Number of input channels for the latent space
        latent_channels_out=4,  # Number of output channels for the latent space
        block_out_channels=[224, 448, 672, 896],  # Example configuration
        layers_per_block=2,
        norm_num_groups=32,
        scaling_factor=1  # Example scaling factor
   )

   autoencoder = Autoencoder(config)
    
   image_path = './test.png'
   image = Image.open(image_path).convert('RGB')  # Convert to RGB if needed
   image = image.resize((512,512))  # Resize to match model input
   np_image = np.array(image).astype(np.float32) / 255.0  # Normalize
   tensor_image = mx.expand_dims(mx.array(np_image).transpose(0, 1, 2),0) # CHW format and add batch dimension
   mx.eval(tensor_image)
   input_image_latent_in = autoencoder.encoder(tensor_image)

   # Generate the latent vectors using diffusion
   latents = sd.generate_latents(
       args.prompt,
       input_image_latent=input_image_latent_in,
       n_images=args.n_images,
       cfg_weight=0.75,
       num_steps=1,
       negative_text=args.negative_prompt,
   )

```

**Comment by angeloskath** [comment]
Hi Stavro,

I added an example of image2image diffusion in the examples repo. https://github.com/ml-explore/mlx-examples/pull/198
It isn't merged yet but it will be shortly.

We had a tiny bug in the encoder part but likely your issues had to do with adding noise properly and scaling the latents properly which should be a bit more readable now. I will close this issue but feel free to reopen one in the examples repo if you are still experiencing problems.

Cheers and merry Christmas

**Comment by sck-at-ucy** [comment]
Thank you 😊 Angele this will help me a lot. 

I have this crazy idea of using Transformers for detecting correlations in fluid dynamics simulations, so before getting myself immersed in deep (and turbulent…) waters, I’m trying to improve my understanding of the basics. 

Merry Christmas and an MLX productive new year 🎁😄.
