### ISSUE TITLE
MLX C API

### ISSUE THREAD

**Issue by jvo203** [ml-explore/mlx#294]
MLX seems to lean heavily on C++ STL etc. How easy / difficult would it be to replace the C++ with pure C. Typically C++ heavy programs incur a significant performance penalty compared with pure C (absolutely zero C++ usage). I get it, C++ is very convenient to use but still, pure C is faster.

Since MLX is all about wringing out the best performance on Apple Silicon, completely re-writing MLX from scratch in pure C is not a far-fetched proposition.

**Comment by awni** [comment]
It's very unlikely we will rewrite the entire backend in pure C. We also use C++ wrappers around Metal  a lot of which is in Objective C. I also don't think for our common use cases we would see much benefit to moving to C as we are rarely overhead bound. There are many other higher level optimizations that would make a much bigger difference (graph optimization / kernel fusion / etc).
