### ISSUE TITLE
[Feature Request] Implement conv3d Functionality in mlx

### ISSUE THREAD

**Issue by NripeshN** [ml-explore/mlx#346]
I noticed that there's currently no direct support for 3D convolution (conv3d) which is a crucial feature for processing 3D data like medical images or video sequences.

I believe adding `conv3d` would be a valuable addition to mlx, allowing users to build more complex and varied models.

**Comment by awni** [comment]
Definitely! See #40 (closing this as duplicate)

**Comment by NripeshN** [comment]
Hi @awni
I tried implementing this myself but ran into several issues. I just tried editing the main C++ and python code but I guess i will have to edit/add support to the metal source code too.

**Comment by awni** [comment]
Yes implementiing this is non-trivial. It involves writing kernels for 3D conv / adapting our 2D conv to handle 3D inputs. If you aren't experienced with Metal then there will be a bit of a learning curve.
