### ISSUE TITLE
[BUG] mx.empty and mx.empty_like are missing

### ISSUE THREAD

**Issue by dionhaefner** [ml-explore/mlx#363]
```python
>>> mx.empty(1)
AttributeError: module 'mlx.core' has no attribute 'empty'

>>> mx.empty_like(mx.array([1]))
AttributeError: module 'mlx.core' has no attribute 'empty_like'
```

**Comment by angeloskath** [comment]
I don't think it makes sense to have empty arrays in MLX so I would suggest initializing with zeros. If, however, you have a good reason to have empty arrays I would love to know about it.

MLX doesn't provide direct access to the underlying data buffer, so setting into the uninitialized array would cause a `scatter` that does a full copy anyway. This is similar to Jax and dissimilar to Numpy and PyTorch.

I will close the issue but feel free to reopen if needed.

**Comment by dionhaefner** [comment]
> MLX doesn't provide direct access to the underlying data buffer, so setting into the uninitialized array would cause a scatter that does a full copy anyway. This is similar to Jax and dissimilar to Numpy and PyTorch.

So you're saying there are no in-place updates in MLX? (This may be similar to vanilla JAX, but gets optimized away under `jax.jit` so seems like a pretty unique restriction of MLX in this case.)

> If, however, you have a good reason to have empty arrays I would love to know about it.

Does ease of migration from NumPy / torch / JAX to MLX count? :)
Reading uninitialized memory is UB anyway so this could just be an alias for `mx.zeros`?

**Comment by angeloskath** [comment]
Yep in-place updates are not currently supported. It may be optimized away in MLX too in the future (no jit required) but even if it is it is not going to be visible to the user.

Regarding aliasing it to zeros, I think it is kind of weird but it is also what Jax is doing. Do you think lack of empty really hinders porting from numpy? In that case feel free to open an issue to discuss aliasing empty to zeros or if you want a PR.

**Comment by dionhaefner** [comment]
IMO introducing a new framework is all about reducing friction so you can reach critical mass of early adopters.

I'm sure I'm preaching to the choir here; but you're unlocking a huge pool of potential early users if `import numpy as np -> import mlx.core as np` is all you need. On top of that, you ease the creation of "duck backends" where `--backend mlx` resolves to `npx = mlx.core` and `--backend jax` sets `npx = jax.numpy`.

It's your package, so proceed as you see fit.
