### ISSUE TITLE
[Feature Request] Array pickle support

### ISSUE THREAD

**Issue by dc-dc-dc** [ml-explore/mlx#367]
Add pickle support to [array](https://github.com/ml-explore/mlx/blob/main/python/src/array.cpp) through pybind, docs can be viewed [here](https://pybind11.readthedocs.io/en/latest/advanced/classes.html#pickling-support). This is a pre-req for #300

**Comment by awni** [comment]
Thanks for making the issue!

I don't see any reason we shouldn't let an array be pickle-able, so I support adding this.

There may be some thorny issues in terms of managing the state of the array (a lot of it is not currently publicly accessible). If we want to keep it that way, we probably need to do a contiguous copy first.

Also it probably should not be ok to pickle an array used in tracing the graph in a function transform.

**Comment by awni** [comment]
Is anyone actively working on this?

**Comment by chunyang-wen** [comment]
If no one is working on it, I can give it a shot

**Comment by awni** [comment]
Sounds great!! I will assign to you!

**Comment by TristanBilot** [comment]
Anyone working on this?

**Comment by dc-dc-dc** [comment]
@chunyang-wen any progress?

**Comment by chunyang-wen** [comment]
@dc-dc-dc Sorry. I am on holidays. Will work on it.

**Comment by chunyang-wen** [comment]
I will remove myself as people are working on it. Sorry for the delay.
