### ISSUE TITLE
[BUG] mlx to pytorch conversion bytes-like object is required

### ISSUE THREAD

**Issue by LachlanGray** [ml-explore/mlx#403]
**Describe the bug**
The mlx -> pytorch example in the docs:
https://ml-explore.github.io/mlx/build/html/usage/numpy.html#pytorch

yields
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    b = torch.tensor(memoryview(a))
                     ^^^^^^^^^^^^^
TypeError: memoryview: a bytes-like object is required, not 'mlx.core.array'
```

**To Reproduce**

```python
import mlx.core as mx
import torch

a = mx.arange(3)
b = torch.tensor(memoryview(a))
c = mx.array(b.numpy())
```

**Expected behavior**
A torch tensor representation of `a`

**Desktop (please complete the following information):**
 - OS Version: MacOS 13.6.1
 - Version 0.7.0
 - torch version 2.1.2

**Comment by dastrobu** [comment]
@LachlanGray, have you considered testing with a build from the main branch? It appears that the feature you are seeking may not have been released yet; it was introduced in #320. Nonetheless, it's great to see your interest in utilizing this new feature I contributed.

**Comment by awni** [comment]
You can also pip install the dev distribution which should include @dastrobu additions to support the buffer protocol:

```
pip install mlx==0.0.7.dev202417
```

**Comment by LachlanGray** [comment]
Cool thanks! I missed that, I'll hop onto the latest version. Fantastic work btw, I love the design. Really excited to see where things go.
