### ISSUE TITLE
[Feature] Add mx.isnan, mx.isinf

### ISSUE THREAD

**Issue by awni** [ml-explore/mlx#404]
Title is pretty self-explanatory. Might also be worth lumping in `isfinite`, `isposinf`, `isneginf`.

**Comment by zuhorer** [comment]
Hi @awni long shot but I have been trying to get a hang of this repository for a while now, I believe it will be really helpful in me getting a more comprehensive understanding of ML frameworks, but I am not able to completely wrap my head around this, could you guide me through an issue, or give me some resources that would help understand that specific repository better, so that I can be of help and be an active contributor?? I have an understanding of tensorflow implementation. not a very deep understanding of pytorch, but I am ready to put in the effort.
thanks

**Comment by awni** [comment]
At this point the best way to learn the library to contribute is to get started with as simple contribution. I'm happy to answer questions as you go along!

If you are not familiar with the high level frameworks like NumPy/Jax/PyTorch there are tons of educational resources available and that would be an even better place to start.

Just FYI: for this issue some familiarity with C++ is useful.

**Comment by zuhorer** [comment]
sure, Awni, I do have an understanding of C++ I will take this up and post my questions as we go along.

**Comment by chunyang-wen** [comment]
@awni if someone is working on it, can you please assign this issue to him?

**Comment by awni** [comment]
@zuhorer are you planning to work on this? Shall I assign it to you?

**Comment by zuhorer** [comment]
yes please!!! much appreciated!

**Comment by zuhorer** [comment]
Hi @awni I believe we will also be implementing [isfinite] as well, right?

**Comment by zuhorer** [comment]
yes that makes sense, just to make sure, I will be implementing  isinf, isfinite, isposinf and isneginf as in np.

**Comment by zuhorer** [comment]
Hi, I am facing issues running the tests, is this a know error or am I missing something?

in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128.

**Comment by awni** [comment]
Share the build command?

**Comment by zuhorer** [comment]
```
pip install --user --upgrade build
pip install --user --upgrade twine
```

Generate the source distribution and wheel:

```
python -m build
```

**Comment by zuhorer** [comment]
I am gettting this error while executing this build command

**Comment by awni** [comment]
You are following the wrong docs for building, use:

https://ml-explore.github.io/mlx/build/html/install.html#python-api

(We should remove the stale pypi stuff it is not useful)

**Comment by zuhorer** [comment]
Thanks @awni for pointing in the correct direction! 
I have raise a PR for isneginf and added tests. If you could have a look would be great!

https://github.com/ml-explore/mlx/pull/448

**Comment by zuhorer** [comment]
hi, @awni I have raised a PR for isposinf and added tests,

https://github.com/ml-explore/mlx/pull/449

**Comment by zuhorer** [comment]
I believe there is an active PR for isinf so will wait on that. 
I had a doubt: 
- as per the numpy definition of isfinite (Test element-wise for finiteness (not infinity and not Not a Number)). we will need to wait for isinf to be implemented as well?

**Comment by awni** [comment]
All of these have been added. Thanks for the contributions @zuhorer !
