### ISSUE TITLE
Swift Frontend for iOS / iPadOS

### ISSUE THREAD

**Issue by mhconradt** [ml-explore/mlx#41]
Creating a meta issue for clarity / visibility so others can upvote / the team can prioritize.

It would be extremely useful to have a Swift ml-explore SDK that can:
- Be used in iOS / iPadOS applications
- Run using the A-series and A- or M-series hardware acceleration (GPU+ANE).

One might not even need to code the model in Python `mlx` in the first place: popular open source architectures could be written directly in Swift and used by many developers.

**Comment by mhconradt** [comment]
Getting models implemented in PyTorch to run on iOS using CoreML is a painful developer experience and it would be easier to just use a Swift `mlx` frontend for on-device training / inference.

**Comment by awni** [comment]
https://github.com/ml-explore/mlx/issues/15

**Comment by awni** [comment]
Closing this. Follow along #15 for progress updates.
