### ISSUE TITLE
[BUG] "could not determine the shape of object type 'memoryview'" when converting random generated & zero & ones array to PyTorch tensor

### ISSUE THREAD

**Issue by PRESIDENT810** [ml-explore/mlx#413]
**Describe the bug**
When a mlx.core.array is created by `random`, `zeros` or `ones`, using `torch.tensor(memoryview(a))` to convert it to PyTorch tensor will trigger this error

**To Reproduce**

Include code snippet
```python
import mlx.core as mx
import torch

a = mx.zeros([3, 5])
b = mx.ones([5, 10])
c = mx.random.normal([2, 4])

torch.tensor(memoryview(a))
torch.tensor(memoryview(b))
torch.tensor(memoryview(c))
```
<img width="1176" alt="image" src="https://github.com/ml-explore/mlx/assets/44538064/f73ec917-c2e1-40ab-9297-29007cbbab6e">

**Expected behavior**
Successfully convert to PyTorch tensors

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.1.2
 - Version 0.0.7.dev202417

I followed #403 and used the dev version, but the error is still there.

**Additional context**
I noticed if the array is one dimensional then the conversion won't fail.
<img width="1199" alt="image" src="https://github.com/ml-explore/mlx/assets/44538064/87dd198c-077f-476f-91d6-997f87636c1f">

**Comment by PRESIDENT810** [comment]
I think this is due to PyTorch doesn't support memoryview very well: https://github.com/pytorch/pytorch/issues/34651

I tried with numpy and it seems to be correct:
<img width="1177" alt="image" src="https://github.com/ml-explore/mlx/assets/44538064/837174a0-a1e1-4b78-896c-8d9a76346f58">
so I guess this is not mlx's problem.

Nonetheless maybe we should note this in "Conversion to NumPy and Other Frameworks" and wait for PyTorch to correctly implement this?

**Comment by awni** [comment]
I will add a warning about this in the docs!

**Comment by awni** [comment]
Docs are updated. Closing as this is a PyTorch issue.

**Comment by itsmedonttell** [comment]
I encountered this issue and resolved it as follows. Posting here in case it helps others:

```python
import mlx.core as mx
import torch

# MLX array 'tensors'
a_mlx = mx.zeros([3, 5])
b_mlx = mx.ones([5, 10])

# torch tensors
a_torch = torch.zeros([3, 5])
b_torch = torch.ones([5, 10])

# torch tensors from MLX arrays
a_mlx2torch = torch.reshape(torch.frombuffer(memoryview(a_mlx),
                            dtype=torch.float32),
                            torch.Size(a_mlx.shape))
b_mlx2torch = torch.reshape(torch.frombuffer(memoryview(b_mlx),
                            dtype=torch.float32),
                            torch.Size(b_mlx.shape))

# test for equality, prints `True True`
print(torch.equal(a_torch, a_mlx2torch), 
      torch.equal(b_torch, b_mlx2torch))
```
