### ISSUE TITLE
[Feature] Add initializers APIs for mlx.nn

### ISSUE THREAD

**Issue by PRESIDENT810** [ml-explore/mlx#436]
Both JAX and PyTorch have initializer classes to initialize weight and bias of a nn module:
https://jax.readthedocs.io/en/latest/jax.nn.initializers.html
https://pytorch.org/docs/stable/nn.init.html

If I am not mistaken, looks like in mlx we currently don't have such initializers, and we need to manually set weight and bias for a mlx.nn object. If we have APIs for some predefined initialization methods (Xavier, Kaiming, etc.) I think it will be easier for users to initialize their neural network modules.

**Comment by awni** [comment]
Related discussion #417 

I will mark this as an enhancement. Having a `nn.init` for common initializers seems sensible to me.

**Comment by LeonEricsson** [comment]
good suggestions, I'll try to start off a PR for this
