### ISSUE TITLE
Gather vmap is NYI, but `Slice` also is `TODO implement`

### ISSUE THREAD

**Issue by charlesincharge** [ml-explore/mlx#44]
Thanks for this library! It is very useful so far.

I am trying to use `vmap` with a function where argument 1 is the indices into argument 2 (effectively a boolean mask to sum over). However, when trying to use `vmap`, I get the runtime error [`Gather vmap is NYI, please change slices instead`](https://github.com/ml-explore/mlx/blob/v0.0.4/mlx/primitives.cpp#L964). However, when I look at the `Slice::vmap` function in `primitives.cpp`, I see that it is just a placeholder with `  // TODO implement`
https://github.com/ml-explore/mlx/blob/v0.0.4/mlx/primitives.cpp#L1907

**Comment by awni** [comment]
Fix coming in #158

**Comment by charlesincharge** [comment]
Thanks for the quick turnaround!
