### ISSUE TITLE
[Feature] Support vmap for reductions

### ISSUE THREAD

**Issue by NNSSA** [ml-explore/mlx#442]
Me and @tedwards2412 are trying to use vmap in conjunction with the summation operation mx.sum, but we're getting some results that we don't understand. We'd expect both the mx.sum() and sum() operations below to produce the same result, but for some reason mx.sum() only outputs one number. 

```python
import mlx.core as mx
x_array = mx.ones((5,10))

def test_func(x):
    return mx.sum(x), sum(x)

print(mx.vmap(test_func)(x_array), "\n")
print([test_func(x) for x in x_array])
```

The output of this is 

```python
(array(1, dtype=float32), array([10, 10, 10, 10, 10], dtype=float32)) 
[(array(10, dtype=float32), array(10, dtype=float32)), (array(10, dtype=float32), array(10, dtype=float32)), (array(10, dtype=float32), array(10, dtype=float32)), (array(10, dtype=float32), array(10, dtype=float32)), (array(10, dtype=float32), array(10, dtype=float32))]
```

while we would expect the vmap (first line of the output) to give

```python
(array([10, 10, 10, 10, 10], dtype=float32)), array([10, 10, 10, 10, 10], dtype=float32)) 
```

This is what we get with mlx v0.0.7. After upgrading to v0.0.9, vmap stopped working altogether:

```python
    print(mx.vmap(test_func)(x_array), "\n")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Reduce::vmap not yet implemented.
```

Any idea what's going on here?

**Comment by awni** [comment]
Yes, we haven't implemented vmap for reductions yet! I will mark this as an enhancement!

**Comment by tedwards2412** [comment]
Ok great thanks! Is there a reason then why it gives the correct behavior when using sum() instead of mx.sum()?

**Comment by awni** [comment]
> Ok great thanks! Is there a reason then why it gives the correct behavior when using sum() instead of mx.sum()?

That's quite a result! But I think it has a simple explanation: python `sum` is the equivalent to:

```
a = array[0]
for b in array[1:]
  a += b
```
