### ISSUE TITLE
crash with 'mlx.core.eye'

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#460]
**Describe the bug**
There is no problem with outputting array a, but there is an error in outputting array b. Should we add some range restrictions to parameters n and m?

**To Reproduce**

Include code snippet
```python
import mlx.core as mx

a = mx.eye(n=50000, m=10000)
print(a)

b = mx.eye(n=50000)
print(b)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/d731aa02-3a58-4e37-9eff-197cb41592ca)

**Expected behavior**
expect not crash

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.7.0

**Comment by angeloskath** [comment]
It is unfortunately an overflow bug. `50,000^2` is over 31 bits and a lot of our indexing operations are using `int32_t`.

Unfortunately, there is not gonna be an easy solution for this if you actually need the 50k by 50k array. If instead you want to do some operation on it then it is probably easier and faster to do it some other way.

**Comment by Redmept1on** [comment]
Thank you for your reply. I understand the problem and will close this issue @angeloskath

**Comment by angeloskath** [comment]
So I implemented the same this morning and for some reason it doesn't work on my M2 air. Hence I thought it may be some other underlying int32 issue  🤷

The reason I didn't do the PR is that the failure now is much more subtle as in on my M2 air it returns 0s ...

**Comment by awni** [comment]
> So I implemented the same this morning and for some reason it doesn't work on my M2 air. Hence I thought it may be some other underlying int32 issue 🤷

This PR (#463) fails for the 50kx50k case on your M2?? That seems like a bug to me though maybe it is overflow.

**Comment by angeloskath** [comment]
Yep it fails by returning all 0s.
