### ISSUE TITLE
'mlx.core.sqrt' dose not return an expected value

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#465]
**Describe the bug**
When I use 'mlx. core. sqrt' to process an array, I don't get the expected return value.

**To Reproduce**
Include code snippet
```python
import mlx.core as mx
a = mx.array([-2.5, -1.5, -0.5, 0.0, 0.5, 1.5, 2.5])
b = mx.sqrt(a)
print(b)

```
![image](https://github.com/ml-explore/mlx/assets/84373897/22e84273-f052-4c8c-b154-990da6080527)

**Expected behavior**
array([nan, nan, nan, 0.0, 0.707107, 1.22474, 1.58114], dtype=float32)

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.7.0

**Comment by Redmept1on** [comment]
It seems like it's just a display issue, sorry

**Comment by LeonEricsson** [comment]
I replicated your tests and as you can see the behaviour is consistent for numpy and MLX:

```
import mlx.core as mx
a = mx.array([-0,-0.0])
b = mx.sqrt(a)
print(b)
---
array([0, -0], dtype=float32)
```

```
import numpy as np
a = np.array([-0, -0.0])
b = np.sqrt(a)
print(b)
---
[ 0. -0.]
```

It seems that the output differs based on if the input element is `-0` or `-0.0`. 
Either way this doesn't matter, it's the same value

```
b == np.array([0, 0])
---
array([ True,  True])
```

**Comment by awni** [comment]
Thanks @LeonEricsson for the helpful response!

**Comment by Redmept1on** [comment]
Thank you for your explanation. I understand now and I'll close the issue.
