### ISSUE TITLE
'reshape' function copies data

### ISSUE THREAD

**Issue by alxndrTL** [ml-explore/mlx#466]
When using `mlx.core.array.reshape`, it returns a copy of the data rather than a view of the array.

For example, if I have
```python
X = mx.arange(8)
Y = X
Y = Y.reshape(4, 2)
Y[0,0] = 33
```
then `Y` will be 

```python
array([[33, 1],
       [2, 3],
       [4, 5],
       [6, 7]], dtype=int32)
```

but `X` will stay `array([0, 1, 2, ..., 5, 6, 7], dtype=int32)`

In NumPy, `X` is updated.
I don't know if it's intented or not. If so, what are the workarounds ?
Thank you

**Comment by LeonEricsson** [comment]
This is intended. I'm pretty sure there _views_ aren't implemented as part of mlx.core yet

**Comment by awni** [comment]
@LeonEricsson is right, this is expected behavior. Under the hood we may re-use data buffers, but from a user perspective this is a full copy.

As for a workaround, why don't you do?
```python
X = mx.arange(8)
X[0] = 33
Y = X.reshape(4, 2)
Y[0,0] = 33
```

**Comment by alxndrTL** [comment]
Thanks, now I understand.
The manipulation of `Y` was based on its shape (this was a simple example), so that's why I had to reshape first. But I found a workaround for my situation.
