### ISSUE TITLE
[BUG] 'mlx.core.floor_divide' crashes unexpectedly

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#469]
**Describe the bug**
when I use 'mlx.core.floor_divide' API, it did not run as expected, and the error message returned showed that a and b can be integer values.

**To Reproduce**

Include code snippet
```python
import mlx.core as mx
x=9
y=1
mx.floor_divide(a=x, b=y)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/d5c7cacd-4cb9-4a3c-ba1f-cee99448f98a)

**Expected behavior**
mx.floor_divide(a=x, b=y) = 9

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.7.0

**Comment by Redmept1on** [comment]
When I set x and y as arrays, I still cannot run successfully
![image](https://github.com/ml-explore/mlx/assets/84373897/15ba72d5-a02c-4f1a-9bb3-8421839ea17a)
![image](https://github.com/ml-explore/mlx/assets/84373897/52faf9e3-6ccb-451d-8e89-702d458f04c5)

**Comment by awni** [comment]
That is expected behavior, the first two arguments to floor divide are positional only, you cannot name them. There we are following the numpy API so the same would not work in numpy.

It should work if you do:

```
mx.floor_divide(1, 2)
```

**Comment by awni** [comment]
Note almost all of our ops have the input array (or arrays) as positional only and the remaining arguments as optionally named arguments. 

We are trying to follow numpy in that convention, if you encounter any discrepancy, please file an issue!
