### ISSUE TITLE
[BUG] Round op on certain negative numbers is off

### ISSUE THREAD

**Issue by dc-dc-dc** [ml-explore/mlx#474]
**Describe the bug**
Rounding certain negative numbers differs from python / numpy

**To Reproduce**

Include code snippet
```python
import mlx.core as mx
import numpy as np
mx.round(mx.array([-2.5]))
# array([-3], dtype=float32)
round(-2.5)
# -2
np.round(np.array([-2.5])
# array([-2.])
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.1.2
 - Version 0.0.9

**Comment by awni** [comment]
Right, we should probably follow the same convention as numpy and round towards +infinity
