### ISSUE TITLE
ValueError invoked by mlx.core.grad

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#487]
**Describe the bug**
When I tried to calculate the gradient of x * * 2 at x=3 using mlx.core.grad, I encountered this problem and wanted to know if it was my method of using the function that was problematic because I saw the document saying, 'Returns: A function which has the same input arguments as fun and returns the gradient (s).' According to the document, there seems to be no problem with my usage method.

**To Reproduce**

Include code snippet
```python
import mlx.core as mx

def square(x):
    return x ** 2
    
print(square((mx.array([3], dtype=mx.float32))))
grad_square = mx.grad(square)

gradient_at_3 = grad_square(mx.array([3], dtype=mx.float32))

print(gradient_at_3)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/5b5ddcff-b3c7-4e3f-a348-302f203d2d3c)

**Expected behavior**
The result is array ([6], dtype=float32)

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.7.0

**Comment by awni** [comment]
I'm sorry that error message is totally useless, I will look to making it better! You need to pass a scalar to `mx.grad`. Arrays with 1 dimension won't work and I don't think we will change that.

The followings should fix it

```python
gradient_at_3 = grad_square(mx.array(3, dtype=mx.float32))
```

**Comment by awni** [comment]
Fwiw `mx.grad` by definition only takes gradients for functions which output a scalar value. If you need more sophisticated functionality you can use `vjp` directly.

**Comment by Redmept1on** [comment]
Thx for your explanation!
