### ISSUE TITLE
'mlx.core.isneginf' has wrong output when input is mlx.core.uint dtype

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#495]
**Describe the bug**
Same as https://github.com/ml-explore/mlx/issues/493, this is also a boundary value issue, but after testing, it only occurs on the 'mlx.core.isneginf' API, but for all uint data types(mx.uint8/uint16/uint32/uint64).

**To Reproduce**

Include code snippet
```python
import mlx.core as mx
import numpy as np


x = np.array([0,20], dtype=np.uint64)
print("numpy:", np.isneginf(x))

x = mx.array([0,20], dtype=mx.uint64)
result = mx.isneginf(x)
print("mlx:", result)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/594d3f5e-a76f-454e-b6d7-09c4fa86d3ff)

**Expected behavior**
mlx: array([False, False], dtype=bool)

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.10.0

**Comment by awni** [comment]
Also fixed in #494

**Comment by Redmept1on** [comment]
sorry! It was my negligence

**Comment by awni** [comment]
No prob! Thanks for finding all of these edge case issues, helps make our code better!

**Comment by Redmept1on** [comment]
Fuzzing may involve many edge cases of apis, so I may new many issues that seem meaningless or completely wrong. If I new some very low-quality issues, I'm very sorry to bother you guys.🙏🏻
