### ISSUE TITLE
[Question] Equivalent of torch's `batch_first` parameter for MultiheadAttention

### ISSUE THREAD

**Issue by a1eaiactaest** [ml-explore/mlx#499]
In PyTorch's [MultiheadAttention](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html) `batch_first` parameter is described as:
> **batch_first** – If True, then the input and output tensors are provided as (batch, seq, feature). Default: False (seq, batch, feature).

Not sure if I understand it correctly but could this parameter be bypassed by just inversing the dims with the provided [`value_output_dims`](https://ml-explore.github.io/mlx/build/html/python/nn/_autosummary/mlx.nn.MultiHeadAttention.html) parameter?

**Comment by awni** [comment]
Our Transformer is different than PyTorch in that regard as it expects by default the input to be `batch x seq x feature`. We don't have an option to have `seq` and `batch` flipped. The easiest workaround if you want to flip them is to swap the dims before and after the call to the transformer (`mx.swapaxes(0, 1)`)

**Comment by a1eaiactaest** [comment]
Thank you @awni!
