### ISSUE TITLE
[BUG] mx.allclose fails for inf == inf.

### ISSUE THREAD

**Issue by awni** [ml-explore/mlx#522]
**Describe the bug**

`mx.allclose` always fails when `inf` is in the inputs but it should pass if the `inf`s are the same sign.

**To Reproduce**

Include code snippet:

```shell
>>> import mlx.core as mx
>>> a = mx.array(float("inf"))
>>> mx.allclose(a, a)
array(False, dtype=bool)
>>> import numpy as np
>>> np.allclose(a, a)
True
```

This occasionally causes some of our float16 tests to fail when an inf pops up (even if it's expected).

**Comment by Rifur13** [comment]
Hi, I can pick this up

**Comment by awni** [comment]
Nice, thanks! Assigned to you!
