### ISSUE TITLE
'mlx.core.array.astype' output different results from tensorflow and numpy when targeting nan

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#528]
**Describe the bug**
When I tried to use 'mlx.core.array. astype' to process an array containing nan, I found that its output result was different from that of tensorflow and numpy.

**To Reproduce**

Include code snippet
```python
import mlx.core as mx

x = mx.array([1.0, 2.0, 3.0,float('nan')])
x_cast = x.astype(mx.int32)
print(x_cast)
```
```python
import numpy as np
import tensorflow as tf

x = np.array([1.0, 2.0, 3.0, float('nan')])
x_cast = x.astype(np.int32)
print(x_cast)

y = tf.constant([1.0, 2.0, 3.0, float('nan')])
y_cast = tf.cast(y, tf.int32)
print(y_cast)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/6599d254-55ba-4b1e-9654-475c4e082bce)
![image](https://github.com/ml-explore/mlx/assets/84373897/d3bcfb9f-6305-42af-a4dc-6991fbabcab0)
![image](https://github.com/ml-explore/mlx/assets/84373897/9e14ac6b-04d0-44c2-a52f-f3c70507ac88)

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.10.0

**Additional context**
Also an edge case.

**Comment by Redmept1on** [comment]
sorry for missing some information！
numpy 1.24.3
tensorflow 2.13.0

**Comment by Redmept1on** [comment]
After some experiments, I found that when mlx converts nan from float32 to int, it will convert it to 0, while numpy will throw a crash (cannot convert float NaN to integer) or convert it to a boundary value (such as -2147483648 in the previous example). I would like to know if it is possible to add a warning here.

**Comment by awni** [comment]
Indeed, we  could either warn/crash/do a boundary value in these cases. I think it makes sense to follow the NumPy behavior there.

**Comment by awni** [comment]
Hmm, I can't repro the behavior you are seeing in NumPy:

```
import numpy as np
x = np.array([1.0, 2.0, 3.0, float('nan')])
x_cast = x.astype(np.int32)
print(x_cast)
```

Prints 
```
[1 2 3 0]
```

NumPy version is '1.23.4'

Could you share a code snippet that reproduces the crash or the boundary value? Did you run the NumPy code in MacOS? The cast could indeed be platform specific.

I'm tentatively closing this, but if there is something here to follow up on I will gladly re-open.
