### ISSUE TITLE
[BUG] Build from source is failing

### ISSUE THREAD

**Issue by vatsaldin** [ml-explore/mlx#532]
**Describe the bug**

Build from source is failing

<img width="1451" alt="Screenshot 2024-01-23 at 9 29 33 PM" src="https://github.com/ml-explore/mlx/assets/1464312/cfcc150e-b64b-4c2a-8a80-e63ccd06646a">

<img width="1491" alt="Screenshot 2024-01-23 at 9 29 57 PM" src="https://github.com/ml-explore/mlx/assets/1464312/f4189af0-0115-4e45-8e60-f604f14f19ed">

**To Reproduce**

Include code snippet
```python

```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 14.1.2]
 - Version [e.g. 0.7.0]

![image](https://github.com/ml-explore/mlx/assets/1464312/55fb0cc1-13f4-48a0-a819-2fb4c0b57337)
**Additional context**

**Comment by awni** [comment]
Could you check the build troubleshooting section. It has exactly that problem with steps to fix. Let me know if you have issues after.

https://ml-explore.github.io/mlx/build/html/install.html#id2

**Comment by vatsaldin** [comment]
Yes, I checked it today and tried the steps still I get other error as below

<img width="1486" alt="Screenshot 2024-01-24 at 7 02 45 PM" src="https://github.com/ml-explore/mlx/assets/1464312/8ac4aec6-96b7-48d3-b176-30b766c9de61">

Also, I did not want to perform build from source however the direct package installation did not work out of the box hence going thru the route of building from source.


`pip install mlx`
