### ISSUE TITLE
Different results were obtained from numpy using mlx.core.argmax/argmin

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#535]
**Describe the bug**
When I added nan to the array, using 'mlx.core.argmax/argmin' resulted in a different result from numpy. Although comparing nan and real numbers does not have much practical significance, I think it is possible to add some conditional restrictions on comparing nan and real numbers here to avoid amplifying the difference in this result during certain subsequent operations.

**To Reproduce**

Include code snippet
```python
import mlx.core as mx
import numpy as np


print('-'*20,'argmax','-'*20)

print('mlx.core.argmax')
array = mx.array([[1, 2, 3], [float('nan'), 5, 6]],dtype=mx.float32)
mlx_argmax = mx.argmax(array, axis=0)
print(mlx_argmax)

print('numpy')
np_array = np.array([[1, 2, 3], [float('nan'), 5, 6]],dtype=np.float32)
np_argmax = np.argmax(np_array, axis=0)
print(np_argmax)


print('-'*20,'argmin','-'*20)

print('mlx.core.argmin')
mlx_argmin = mx.argmin(array, axis=0)
print(mlx_argmin)

print('numpy')
np_argmin = np.argmin(np_array, axis=0)
print(np_argmin)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/cdfedf2f-febb-464a-a433-176006f79717)

**Expected behavior**
maybe follow numpy here.

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.10.0

**Comment by awni** [comment]
This difference is unfortunate but we will probably not change the way we handle nans since it would involve special casing `isnan` in all of our reduction kernels. 

It's not unreasonable in my opinion that the behavior with `NaN` in these kernels is implementation specific since `1<float("nan")` and `1>float("nan")`.
