### ISSUE TITLE
error message is useless when using 'mlx.core.concatenate'

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#542]
**Describe the bug**
After the test at https://github.com/ml-explore/mlx/issues/540, I tried to change axis to 1 to see if the code would work, but I found that the crash error message was useless. And I can make the code work properly with the reshape operation, where I think the error messages can be a little clearer.

**To Reproduce**

Include code snippet
```python
import mlx.core as mx

array1 = mx.array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])
array2 = mx.array([4, 5, 6])
axis = 1
concatenated = mx.concatenate([array1, array2], axis=axis)
print(concatenated)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/53854c0b-b3e1-4f49-8b28-da0f08eba43d)

```python
import mlx.core as mx

array1 = mx.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
array2 = mx.array([4, 5, 6])
array2_reshaped = mx.reshape(array2, (3, 1))
axis = 1
concatenated = mx.concatenate([array1, array2_reshaped], axis=axis)
print(concatenated)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/931925c3-324a-4f9e-bbf4-d6814873523d)

**Expected behavior**
A clear error message

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.10.0

**Comment by awni** [comment]
Thanks! Fixed in #543
