### ISSUE TITLE
[Feature] load/save safetensor in bfloat16 

### ISSUE THREAD

**Issue by mzbac** [ml-explore/mlx#546]
Currently, there are some issues with fine-tuning and training using float16. We need to convert some weights to float32 during the forward pass and then convert them back to float16 when saving the weight. Since the latest Apple Silicon already supports bfloat16, would it be possible to load/save safetensor in bfloat16 for supported devices? This way, we wouldn't have to convert the weights from float32 back to float16 during or after training and fine-tuning.

**Comment by awni** [comment]
@mzbac can you be more specific with the issues you are describing? We already allow bfloat16 to be loaded directly from safetensors, so I am not sure exactly what you are asking for?

```shell
>>> a = mx.array([1.0], mx.bfloat16)
>>> mx.save_safetensors("a.safetensors", {"a": a})
>>> mx.load("a.safetensors")
{'a': array([1], dtype=bfloat16)}
```

**Comment by mzbac** [comment]
> @mzbac can you be more specific with the issues you are describing? We already allow bfloat16 to be loaded directly from safetensors, so I am not sure exactly what you are asking for?
> 
> ```shell
> >>> a = mx.array([1.0], mx.bfloat16)
> >>> mx.save_safetensors("a.safetensors", {"a": a})
> >>> mx.load("a.safetensors")
> {'a': array([1], dtype=bfloat16)}
> ```

Hi @awni, I will double-check because I checked a few models and it seems that they have float16 weight after being loaded. In Lora, we use fp32 weight. We have to cast it back to float16 during the merge of Lora. So, I was thinking of enabling bfloat16 for Lora training to avoid the casting. I thought load safetensors doesn't support float16, which is why I am getting model weight as fp16.

**Comment by awni** [comment]
So our `load_safetensors` will load the type unchanged. Different models come with different types out of the box, we'll just use the given type. I don't think we do anything in `mlx-lm` to change the loaded type (but we should verify).

One thing to keep in mind is that even though MacOS supports `bfloat16` it is a lot slower than `fp16`. It is purely a memory saving device not speed. That why I usually default to `float16` when it makes sense to explicitly specify a default.

**Comment by mzbac** [comment]
> So our `load_safetensors` will load the type unchanged. Different models come with different types out of the box, we'll just use the given type. I don't think we do anything in `mlx-lm` to change the loaded type (but we should verify).
> 
> One thing to keep in mind is that even though MacOS supports `bfloat16` it is a lot slower than `fp16`. It is purely a memory saving device not for speed. That why I usually default to `float16` when it makes sense to explicitly specify a default.

Thanks for the detailed explanation. I will investigate further. The only thing that brought me this issue was the weight of Lora using fp32, and during merge we cast it to fp16. I am not 100% sure if this is causing the issue, but sometimes when  fusing Lora for a non-quantized model, there is some performance degradation.

**Comment by awni** [comment]
> The only thing that brought me this issue was the weight of Lora using fp32, and during merge we cast it to fp16.

Interesting. I think it's more likely the degradation comes from the fusion itself rather than casting the adapters. I noticed this in the past. One thing to check is: cast but no fuse vs cast + fuse.

When i was encountering this, it was because the adapters were small which especially when you add them to the large weight matrix values you lose precision. Using them outside the matrix can be numerically more stable in that case since you get the reduction first. In that case increasing the scale during training helped.

**Comment by mzbac** [comment]
> 

Thanks for the suggestion, I will check them out.

**Comment by awni** [comment]
@mzbac let me know if we can close this. It sounds like if there may be something to fix but it is likely specific to LoRA / mlx-lm
