### ISSUE TITLE
The error message should be more explicit when the empty array is input to mlx.core.convolve

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#547]
**Describe the bug**
The error message should be more explicit when the empty array is input to mlx.core.convolve, where slice's role in convolve operations is not well known. Also, what the i in error message refers to is not explicitly stated in the convolve operation documentation, so following numpy's error message may be more intuitive.

Here, the reason numpy outputs' ValueError: v cannot be empty 'when setting a to an empty array is that numpy interchanges a and v when len(v) > len(a) same as mlx.

**To Reproduce**

Include code snippet
```python
import mlx.core as mx

a = mx.array([])
v = mx.array([1., 0, 0])
mode = 'full' 

convolved = mx.convolve(a, v, mode=mode)
print(convolved)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/b884016b-8c0f-486b-a111-74d5e821e5e6)

```python
import numpy as np

np_a = np.array([])
np_v = np.array([1., 0, 0])
mode = 'full' 

np_convolved = np.convolve(np_a, np_v, mode=mode)
print(np_convolved)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/d5fd0d13-dcc9-47de-b200-c4c6f964b884)

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.10.0
 - numpy 1.24.3

**Additional context**
maybe an enhancement

**Comment by jagrit06** [comment]
Thanks for taking the time to bring this to our attention. I will be closing the issue for now.
