### ISSUE TITLE
[Feature] Support for `unsqueeze()`

### ISSUE THREAD

**Issue by RahulBhalley** [ml-explore/mlx#549]
Hi,
I couldn't find `mlx.core.unsqueeze()` in documentation. Are there any plans to implement it or have there been any reasons already discussed to not implement it?

**Comment by RahulBhalley** [comment]
Okay. Thanks.

**Comment by RahulBhalley** [comment]
@awni sorry to ping. Idk but these syntaxes feel weird to use. My preference would still be PyTorch's functions instead of NumPy for this task.

Please discuss with the internal team if they agree to use PyTorch syntax at least for this.

**Comment by awni** [comment]
Hi Rahul we aren't going to change that sorry. I would suggest you adapt to the NumPy style syntax as it is quite common.

**Comment by RahulBhalley** [comment]
Hmm, okay.
