### ISSUE TITLE
[Doc] mlx.core.erf has a problem with the formula in the documentation

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#556]
**Describe the bug**
mlx.core.erf's formula has a problem in the documentation, where x and t should be interchangeable, and the x in erf(x) should be the upper limit of the integration, not the variable being integrated.

![image](https://github.com/ml-explore/mlx/assets/84373897/44710e91-450c-4d5c-9326-1eeca7090421)

**Comment by awni** [comment]
Good catch, will fix.
