### ISSUE TITLE
[BUG] malloc error "Unable to allocate" 8446744063349813240 bytes

### ISSUE THREAD

**Issue by ivanfioravanti** [ml-explore/mlx#566]
I get malloc error "Unable to allocate" 8446744063349813240 bytes when passing from numpy array to mx.array with intermediate range of items. smaller works, larger works, mid fails

Include code snippet
```python
import numpy as np
import mlx.core as mx

test_ok_1 = mx.array(np.arange(1, 20 * 10**8))
test_ok_2 = mx.array(np.arange(1, 50 * 10**8))
test_ko_3 = mx.array(np.arange(1, 30 * 10**8))

```

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.3
 - Version 0.11
 - M3 Max 40GPU 128GB

**Comment by awni** [comment]
It looks like the index shape is overflowing `int32`. I would use 2D or 3D if you can for now. The fix (if we do it) for this is a bit involved..

**Comment by ivanfioravanti** [comment]
Thanks @awni it was just to raise the flag.

**Comment by awni** [comment]
I will add a useful error message at least until we fix this

**Comment by jmousseau** [comment]
Taking a crack at improving the error message ([early WIP](https://github.com/ml-explore/mlx/compare/main...jmousseau:mlx:check-shape-wip)).
