### ISSUE TITLE
mlx.core.floor got the wrong outputs on some edge cases

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#567]
**Describe the bug**
This is very interesting, when dealing with -1.0000001 with mlx.core.floor, the result is correct, when dealing with -2.0000001, the result is wrong, and when dealing with all negative numbers smaller than -2, the result of x.0000001 seems to be wrong. But when dealing with -2.0000002 the result turns out to be correct again.

**To Reproduce**

**mlx**
```python
import mlx.core as mx

#correct
array_a = mx.array([-1.0000001])
result = mx.floor(array_a)
print(result) #array([-2], dtype=float32)

array_b = mx.array([-2.0000002])
result = mx.floor(array_b)
print(result) #array([-3], dtype=float32)

#wrong
array_c = mx.array([-2.0000001])
result = mx.floor(array_c)
print(result) #array([-2], dtype=float32)

array_c = mx.array([-100.0000001])
result = mx.floor(array_c)
print(result) #array([-100], dtype=float32)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/14c89e23-640a-4969-a9d8-3fe132cfb735)

**numpy**
```python
import numpy as np

#wrong
array_c = np.array([-2.0000001])
result = np.floor(array_c)
print(result) #[-3.]

array_c = np.array([-100.0000001])
result = np.floor(array_c)
print(result) #[-101.]
```
![image](https://github.com/ml-explore/mlx/assets/84373897/8e7acfcd-d499-4e6d-b3bb-18520ba63cb2)

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.10.0

**Comment by angeloskath** [comment]
Nice but this is not a bug actually. It is just that these numbers are not representable in float32. The reason that the numpy results are correct is that the default floating point type in numpy is float64.

```python
import numpy as np

#wrong
array_c = np.array([-2.0000001], dtype=np.float32)
result = np.floor(array_c)
print(result) #[-2.]

array_c = np.array([-100.0000001], dtype=np.float32)
result = np.floor(array_c)
print(result) #[-100.]
```

Setting for instance the dtype to float16 would give the "wrong" result for all these numbers.

**Comment by Redmept1on** [comment]
Thanks for your quick reply and explanation! I will close this issue. @angeloskath
