### ISSUE TITLE
Wrong output was obtained when the num parameter of 'mlx.core.linspace' was set to 1.

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#573]
**Describe the bug**
An error output nan was obtained when the num parameter of mlx.core.linspace was set to 1.

**To Reproduce**

```python
import mlx.core as mx
import numpy as np

start = 1
stop = 10
num = 1

linspace_mlx = mx.linspace(start, stop, num, dtype=mx.float32)
print("Linspace using mlx:", linspace_mlx)

linspace_np = np.linspace(start, stop, num, dtype=np.float32)
print("Linspace using NumPy:", linspace_np)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/aad92347-fc52-497f-9a1f-b14fd6ce6e67)

**Expected behavior**
maybe same as numpy

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.10.0

**Comment by AvikantSrivastava** [comment]
@Redmept1on @awni can I work on this?

**Comment by awni** [comment]
That would be awesome, thank you @AvikantSrivastava

**Comment by AvikantSrivastava** [comment]
@awni can you take at look at the PR #602

**Comment by AvikantSrivastava** [comment]
@Redmept1on I guess we can close this issue
