### ISSUE TITLE
mlx.core.logaddexp got an wrong output on the gpu when dealing with nan

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#575]
**Describe the bug**
mlx.core.logaddexp got an wrong output on the gpu when dealing with nan, the output should be nan.

**To Reproduce**
```python
import mlx.core as mx

a_mx = mx.array([float('nan'), 0.2, 0.3], dtype=mx.float32)
b_mx = mx.array([1, 2, 3], dtype=mx.float32)

logaddexp_gpu = mx.logaddexp(a_mx, b_mx)
print("logaddexp on GPU:", logaddexp_gpu)

mx.set_default_device(mx.cpu)
logaddexp_cpu = mx.logaddexp(a_mx, b_mx)
print("logaddexp on CPU:", logaddexp_cpu)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/d1384cea-c95e-4710-b4b2-79f38ec0a254)

**Expected behavior**
array([nan, 2.15298, 3.06504], dtype=float32)

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.0.10

**Comment by awni** [comment]
I can't conceive as to how that is not getting a NaN through. The kernel does this:


```cpp
    constexpr T inf = metal::numeric_limits<T>::infinity();
    T maxval = metal::max(x, y);
    T minval = metal::min(x, y);
    return (minval == -inf || maxval == inf) ? maxval :
      (maxval + log1p(metal::exp(minval - maxval)));
```

Both `maxval` and `minval` should be `NaN`. The output of `maxval + log1p(metal::exp(minval - maxval)))` should also be `NaN` unless Metal is doing something fishy.

**Comment by awni** [comment]
Evidently the output of `metal::max(nan, a)` is not `nan`... that seems like a metal bug to me unless I'm missing something.

Nevertheless I will make a patch for this.

**Comment by awni** [comment]
This issue is actually a problem anywhere we use `metal::max` and `metal::min`:

```
>>> mx.maximum(0, float("nan"))
array(0, dtype=float32) 
```

**Comment by angeloskath** [comment]
Well actually both `maxval` and `minval` are not nan. It is an implementation detail of `metal::max`. The following

```
x > y ? x : y;
```

would always return `y` if either `x` or `y` are `nan`. However, `metal::max` (and `metal::min` for that matter) seems to always return the finite number. You can check by doing `mx.maximum(a, b)` and `mx.maximum(b, a)`...

**Comment by awni** [comment]
Should we switch to the ternary then?

**Comment by Redmept1on** [comment]
A new issue has been found and I submit it on https://github.com/ml-explore/mlx/issues/577. I wonder if it has anything to do with this issue.

**Comment by Redmept1on** [comment]
Perhaps this is also the reason why mlx.core.maximum and mlx.core.maximum have different output on the cpu and gpu when dealing with nan.
```python
import mlx.core as mx

a_mx = mx.array([float('nan'), 4, 6], dtype=mx.float32)
b_mx = mx.array([3, 2, 5], dtype=mx.float32)

maximum_gpu = mx.maximum(a_mx, b_mx)
print("Element-wise maximum on GPU:", maximum_gpu)

mx.set_default_device(mx.cpu)
maximum_cpu = mx.maximum(a_mx, b_mx)
print("Element-wise maximum on CPU:", maximum_cpu)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/e2d39507-7d83-45f6-afa9-3c9de2a4bc5c)

**Comment by awni** [comment]
> A new issue has been found and I submit it on #577. I wonder if it has anything to do with this issue.

Related I think. If you do `a > b ? a : b` you will always get `b` if either `a` or `b` is `NaN`. So if `a` is `NaN` we will suppress it.
