### ISSUE TITLE
mlx.core.logsumexp got an wrong output when dealing with inf

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#576]
**Describe the bug**
mlx.core.logsumexp got an wrong output when dealing with inf

**To Reproduce**
```python
import mlx.core as mx

a_mx = mx.array([[float('inf'), 2, 3], [4, 5, 6]], dtype=mx.float32)

logsumexp_gpu = mx.logsumexp(a_mx, axis=1)
print("logsumexp on GPU:", logsumexp_gpu)

mx.set_default_device(mx.cpu)
logsumexp_cpu = mx.logsumexp(a_mx, axis=1)
print("logsumexp on CPU:", logsumexp_cpu)

```
![image](https://github.com/ml-explore/mlx/assets/84373897/77cc4ce3-392b-4bb7-ae81-105fdfbae7ae)

```python
import numpy as np

a_np = np.array([[float('inf'), 2, 3], [4, 5, 6]],dtype =np.float32)

from scipy.special import logsumexp as logsumexp_np
logsumexp_result_np = logsumexp_np(a_np, axis=1)
print("logsumexp using NumPy:", logsumexp_result_np)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/f5b4b272-c526-441e-b80a-b39bfe69bf29)

**Expected behavior**
array([inf, 6.40761], dtype=float32)

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.0.10

**Comment by awni** [comment]
Indeed, this is a known issue. We haven't fixed it as it's tedious to fix (likely requires a custom primitive) and very much an edge case.
