### ISSUE TITLE
An enhancement of the error message for mlx.core.mean

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#578]
**To Reproduce**

```python
import mlx.core as mx

a_mx = mx.array([[1, 2, 3], [4, 5, 6]], dtype=mx.float32)

mean_gpu = mx.mean(a_mx, axis=3)
print("Mean on GPU:", mean_gpu)

mx.set_default_device(mx.cpu)
mean_cpu = mx.mean(a_mx, axis=3)
print("Mean on CPU:", mean_cpu)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/e86a2334-f133-4336-a7bb-ffd29529b5d7)

```python
import numpy as np

a_np = np.array([[1, 2, 3], [4, 5, 6]])

mean_np = np.mean(a_np, axis=3)
print("Mean using NumPy:", mean_np)

```
![image](https://github.com/ml-explore/mlx/assets/84373897/fc0e0673-4035-48e6-9e3d-3da4eb2ad270)

**Expected behavior**
When axis exceeds array dimensions, there should be a more explicit error message

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.0.10

**Comment by AvikantSrivastava** [comment]
@Redmept1on @awni 
can I pick this one up?

**Comment by awni** [comment]
That would be great! Assigned to you.

**Comment by AvikantSrivastava** [comment]
@awni is there an error class that I can use? or do I need to create one myself?
I am referring to equivalent of  `numpy.AxisError`

**Comment by AvikantSrivastava** [comment]
@awni or should I throw something like this
```
std::ostringstream msg;
msg << "axis " << AXIS
<< " is out of bounds for array of dimension " << DIMS;
throw std::invalid_argument(msg.str())
```

**Comment by AvikantSrivastava** [comment]
could you also tell me the wordings of the error message?

**Comment by awni** [comment]
Yes, `std::invalid_argument` is fine with a useful error message:

`msg << "[mean] axis " << axis << " is out of bounds for array with " << a.ndim() << " dimensions.";`

**Comment by AvikantSrivastava** [comment]
PR link: https://github.com/ml-explore/mlx/pull/608
