### ISSUE TITLE
Different result from Numpy in simple add operator

### ISSUE THREAD

**Issue by abdussamettrkr** [ml-explore/mlx#583]
**Describe the bug**
I'm trying to add two differently shaped arrays, but the results are unexpected. To confirm the discrepancy in the output, I compared the results with NumPy.

**To Reproduce**

Include code snippet
```
import mlx.core as mx
import numpy as np

left_shape = [1, 1, 2, 1, 1, 2]
right_shape = [2, 1]

mlx_left = mx.ones(left_shape)
mlx_right = mx.ones(right_shape)

np_left = np.ones(left_shape)
np_right = np.ones(right_shape)

mlx_result = mlx_left + mlx_right
np_result = np_left + np_right

print("Shapes same:", list(mlx_result.shape) == list(np_result.shape))
print("Result diff:",(np_result - mlx_result).max())
```
Prints:
Shapes same: True
Result diff: 1.0

**Desktop (please complete the following information):**
 - OS Version:  MacOS 14.2.1
 - Version 0.0.11

**Comment by angeloskath** [comment]
Hmm I just ran that and it produces `True` and `0.0`...

Can you provide the result by printing `mlx_result`? Can you also `pip install` the latest version or build from `main`?

**Comment by beratuna** [comment]
I tried setting Left shape: [1, 1, 2, 1, 1, 6] and Right shape:  [1, 6, 1]
I get `Result diff: 2.0`
When I print mlx_result and np_result I get the following:

mlx_result:

    array([[[[[[2, 2, 2, 2, 2, 2],
           [2, 2, 2, 2, 2, 1],
           [1, 1, 1, 1, 0, 0],
           [1, 1, 1, 0, 0, 0],
           [1, 1, 0, 0, 0, 0],
           [1, 0, 0, 0, 0, 0]]],
         [[[2, 2, 2, 2, 2, 2],
           [2, 2, 2, 2, 2, 1],
           [1, 1, 1, 1, 0, 0],
           [1, 1, 1, 0, 0, 0],
           [1, 1, 0, 0, 0, 0],
           [1, 0, 0, 0, 0, 0]]]]]], dtype=float32)

np_result:

    array([[[[[[2., 2., 2., 2., 2., 2.],
           [2., 2., 2., 2., 2., 2.],
           [2., 2., 2., 2., 2., 2.],
           [2., 2., 2., 2., 2., 2.],
           [2., 2., 2., 2., 2., 2.],
           [2., 2., 2., 2., 2., 2.]]],
         [[[2., 2., 2., 2., 2., 2.],
           [2., 2., 2., 2., 2., 2.],
           [2., 2., 2., 2., 2., 2.],
           [2., 2., 2., 2., 2., 2.],
           [2., 2., 2., 2., 2., 2.],
           [2., 2., 2., 2., 2., 2.]]]]]])

Then, I tried left and right shapes with random ints as follows;

```
import random

import mlx.core as mx
import numpy as np

def test_add(trial_amount: int = 10):
    for _ in range(trial_amount):
        left_shape = [1, 1, random.randint(1, 10), 1, 1, random.randint(1, 10)]
        right_shape = [1, random.randint(1, 10), 1]
        
        mlx_left = mx.ones(left_shape)
        mlx_right = mx.ones(right_shape)
        
        np_left = np.ones(left_shape)
        np_right = np.ones(right_shape)
        
        mlx_result = mlx_left + mlx_right
        np_result = np_left + np_right
        
        print("\nShapes same:", list(mlx_result.shape) == list(np_result.shape))
        print("Left shape: ", left_shape)
        print("Right shape: ", right_shape)
        print("Result diff:",(np_result - mlx_result).max())
```

> Shapes same: True
Left shape:  [1, 1, 6, 1, 1, 4]
Right shape:  [1, 5, 1]
Result diff: 1.0

> Shapes same: True
Left shape:  [1, 1, 5, 1, 1, 9]
Right shape:  [1, 8, 1]
Result diff: 2.0

> Shapes same: True
Left shape:  [1, 1, 1, 1, 1, 9]
Right shape:  [1, 5, 1]
Result diff: 0.0

> Shapes same: True
Left shape:  [1, 1, 3, 1, 1, 10]
Right shape:  [1, 2, 1]
Result diff: 1.0

> Shapes same: True
Left shape:  [1, 1, 2, 1, 1, 7]
Right shape:  [1, 6, 1]
Result diff: 2.0

For some shapes I got `Result diff: 0.0`, 
for some shapes I got `Result diff: 1.0` 
and for some shapes I got `Result diff: 2.0`

Macbook Air (m1)
macOS: 13.4
mlx: 0.0.11 (just installed from pip)

**Comment by angeloskath** [comment]
Nice find! It is indeed a bug that has to do with an optimization that collapses contiguous dimensions and mistakenly treating singleton dimensions.

I am gonna PR a fix shortly just making sure I got all cases.
