### ISSUE TITLE
Checks are only performed in operator overloads but not their underlying equivalent

### ISSUE THREAD

**Issue by minghuaw** [ml-explore/mlx#585]
Operator overload `operator&&` checks if both arrays are Boolean valued but `logical_and` does not. Similar behavior is found with `operator||` and `logical_or`. Shouldn't both `operator&&` and `logical_and` perform the check?

Version: 0.0.11

**Comment by awni** [comment]
Yea it's a good point, I don't think that check has a useful purpose... I think `operator&&` should be the same as `logical_and` and for bitwise and we should use `operator&` which only allows certain types.
