### ISSUE TITLE
An enhancement of mlx.core.partition

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#586]
**Describe the bug**
According to my tests, mlx.core.partition seems to simply sort the array sequently, no matter how it adjusts the value of kth, It is not as stated in The document 'The ordering of the elements in partitions is undefined.' Although the result does meet the requirements of partition.

**To Reproduce**
```python
import mlx.core as mx

a_mx = mx.array([2.5, 1, 8, 5, 3, 4], dtype=mx.float32)

partition_kth1 = mx.partition(a_mx, kth=1)
print(partition_kth1)

partition_kth2 = mx.partition(a_mx, kth=2)
print(partition_kth2)

partition_kth3 = mx.partition(a_mx, kth=3)
print(partition_kth3)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/28f984b6-5c8c-486a-8b27-2b5182336ef8)

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.0.10

**Comment by awni** [comment]
This is an implementation detail. In general the ordering of the topk is undefined and should not be relied on to be sorted.
