### ISSUE TITLE
An empty array should be output when the repeats parameter of mlx.core.repeat is 0

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#587]
**Describe the bug**
mlx's API usually outputs an empty array as array([], dtype=float32), but when I set the repeats parameter of mlx.core.repeat to 0, it outputs array(0, dtype=float32). I don't know if this is an equivalent output or if there's something wrong with the current output.

**To Reproduce**

```python
import mlx.core as mx

array_mx = mx.array([1, 2, 3], dtype=mx.float32)
repeats = 0
axis = 0 
repeated = mx.repeat(array_mx, repeats, axis)
print(repeated)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/157e982a-c75d-42c5-90a9-d8851a520a54)

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.0.10

**Comment by AvikantSrivastava** [comment]
@Redmept1on @awni can I pick this one up?

**Comment by awni** [comment]
Of course, that would be awesome!!

**Comment by awni** [comment]
@AvikantSrivastava are you working on this?

**Comment by noahfarr** [comment]
If not, I’d like to give it a shot.

**Comment by noahfarr** [comment]
@awni Can you tell me whats the correct way to create an empty array in the C++ code? I looked around in the code but it wasn't quite clear to me and I don't want to end up using some incorrect workaround.

**Comment by awni** [comment]
`auto a = array({});`

**Comment by noahfarr** [comment]
Oh, interesting. The current code does array({}, arr.dtype()) which returns array(0, dtype=int32) but without dtype it works. I guess its due to the constructor overloading, right?

**Comment by awni** [comment]
> The current code does array({}, arr.dtype()) which returns array(0, dtype=int32)
😮  really? That seems like a bug to me.

**Comment by awni** [comment]
So you are saying it is calling the wrong function. It's probably calling this with a default int which is `0`: https://github.com/ml-explore/mlx/blob/main/mlx/array.h#L428-L436

That's not great as it is clearly quite easy to mess up :(.  A workaround would be to explicitly mark it is as an initializer list:

```
auto a = array(std::initializer_list<int>{}, arr.dtype())
```

Not sure if there is a clean way to disambiguate those constructors. If you think of something feel free to try it out.

**Comment by noahfarr** [comment]
Yeah that was my solution before asking for the correct way because it seemed like a weird workaround

**Comment by noahfarr** [comment]
What do you think of adding a constructor that only takes dtype as parameter and returns an empty array with that type?

**Comment by noahfarr** [comment]
Or one could implement a my.empty method like [numpy](https://numpy.org/doc/stable/reference/generated/numpy.empty.html#numpy.empty) that hides this workaround.

**Comment by awni** [comment]
Is it possible to get the compiler to choose the right function by adding specializations? A new constructor may help a bit but it also doesn't solve the problem that `array({}, int32)` is not an empty array! I expect people will stumble on that in the future.
