### ISSUE TITLE
An enhancement of the error message for mlx.core.split

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#593]
**Describe the bug**
When axis exceeds array dimensions, there should be a more explicit error message.

**To Reproduce**
```python
import mlx.core as mx

a_mx = mx.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=mx.float32)

indices_or_sections = 3
split = mx.split(a_mx, indices_or_sections, axis=2)
print([arr for arr in split])
```
![image](https://github.com/ml-explore/mlx/assets/84373897/f316a5ba-7ef2-48c4-be7b-2f3e7ac4c26b)

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.0.10

**Comment by AvikantSrivastava** [comment]
@Redmept1on @awni can I work on this?

**Comment by awni** [comment]
Wonderful, thanks!
