### ISSUE TITLE
mlx.core.take should have crashed, but printed the wrong array instead

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#594]
**Describe the bug**
For my test code, when axis is set to 0 and -2, it should trigger a crash instead of getting an error output.

**To Reproduce**

Include code snippet
```python
import mlx.core as mx

a_mx = mx.array([[1, 2, 3], [4, 5, 6]], dtype=mx.float32)
indices_mx = mx.array([0, 2], dtype=mx.int32)

axis = 0
taken = mx.take(a_mx, indices_mx, axis)
print(taken)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/34a67205-3102-40be-b445-8abf349a4500)

```python
import mlx.core as mx

a_mx = mx.array([[1, 2, 3], [4, 5, 6]], dtype=mx.float32)
indices_mx = mx.array([0, 2], dtype=mx.int32)

axis = -2
taken = mx.take(a_mx, indices_mx, axis)
print(taken)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/b8b3b050-958a-4e71-9d72-b1360bb119eb)
```python
import numpy as np

a_np = np.array([[1, 2, 3], [4, 5, 6]])

axis = -2
indices_np = np.array([0, 2])
taken_np = np.take(a_np, indices_np, axis)
print(taken_np)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/03a6c44e-25d1-49e5-9c1e-5846246ea51b)

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.0.10

**Comment by Redmept1on** [comment]
mlx.core.take_along_axis does not appear to have this issue

**Comment by awni** [comment]
This one is expected and we will probably not fix it in general, though we may provide helpful options for debugging. Indexing out of bounds in MLX is different from NumPy for important reasons. You can read more about it in the [docs](https://ml-explore.github.io/mlx/build/html/usage/indexing.html#differences-from-numpy)
