### ISSUE TITLE
mx.where primitive cannot handle nan/inf elements

### ISSUE THREAD

**Issue by abdussamettrkr** [ml-explore/mlx#606]
**Describe the bug**

I am attempting to write an operation that utilizes the mx.where function. However, I have noticed that the function cannot handle NaN and Inf elements. Based on my understanding, the current operation types (unary_op and binary_op) do not cover this specific operation type (array cond, array a, array b), therefore the current implementation is incomplete. I think adding a ternary_op (which would be very similar to binary_op) to enable a more robust implementation of mx.where that can handle NaN and Inf elements, but this case my result lots of code duplication with binary_op. If you have any design choice, I would like to enhance the mx.where implementation. Thank you.

**To Reproduce**

```
import mlx.core as mx
import numpy as np
import jax.numpy as jnp


print("MLX:",mx.where(True, 3, mx.nan))
print("Jax:",jnp.where(True, 3, jnp.nan))
print("Numpy:",np.where(True, 3, np.nan))
```

Prints
MLX: array(nan, dtype=float32)
Jax: 3.0
Numpy: 3.0

**Expected behavior**
Similar result with Jax and Numpy

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version: 0.0.11

**Comment by awni** [comment]
Yes this is a known issue and I believe currently being worked on. Closing this as a dup of #598

**Comment by abdussamettrkr** [comment]
> Yes this is a known issue and I believe currently being worked on. Closing this as a dup of #598 

Yes, i see. Thank you
