### ISSUE TITLE
[BUG] Failure during test_step_activation unit test

### ISSUE THREAD

**Issue by BoilerToad** [ml-explore/mlx#611]
**Describe the bug**
When running the provided unit test cases, I am getting a failed test.

FAIL: test_step_activation (test_nn.TestNN.test_step_activation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/xxxxxxx/working/mlx/python/tests/test_nn.py", line 456, in test_step_activation
    self.assertTrue(mx.array_equal(y, expected))
AssertionError: array(false, dtype=bool) is not true

----------------------------------------------------------------------
Ran 172 tests in 10.101s

FAILED (failures=1)

**To Reproduce**

Include code snippet
```python

python3 -m unittest discover python/test

```

**Expected behavior**
Expect to complete all unit tests without error.

**Desktop (please complete the following information):**
Apple M3 Pro
 - OS Version: [e.g. MacOS 14.2.1]
 - python version 3.11.6
 - PyTorch 2.2.0

**Additional context**

**Comment by awni** [comment]
Which MLX version are you using?

**Comment by awni** [comment]
I am not able to reproduce this on an M1 with 14.2. Could be an M3 thing. @jagrit06 would you mind trying that?

**Comment by awni** [comment]
Actually I don't even see this test: `test_nn.TestNN.test_step_activation`. Looks like you might be using a pretty out of date MLX. I would recommend updating. If you still see an issue, I will reopen this.
