### ISSUE TITLE
Question: Add mean and std parameters to normal distribution

### ISSUE THREAD

**Issue by noahfarr** [ml-explore/mlx#618]
Hello,

I've observed that in core.random, when generating a normal distribution, we're limited to specifying just the shape, dtype, and PRNG key, without the option to set the mean and variance directly. While I understand we can adjust the generated samples by rescaling to achieve the desired mean and standard deviation, it seems it could be more convenient to include mean and std as optional parameters. Is there a specific reason for not incorporating these options?

**Comment by awni** [comment]
I see [np.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html) has `loc` and `scale` parameters.

On the other hand, Jax [random.normal](https://jax.readthedocs.io/en/latest/_autosummary/jax.random.normal.html) does not.

I don't feel too strongly about it one way or the other. You can see from the two styles below including the params really doesn't save that much from a syntax standpoint:

`std * mx.random.normal(shape=shape) + mean` and `mx.random.normal(shape=shape, mean=mean, std=std)`

But the former might not be as clear to everyone, so from that perspective including the mean and std params seems reasonable..

If no-one comments here that we shouldn't do it, I would say feel free to send a PR.

**Comment by noahfarr** [comment]
Okay, thank you for the quick response. [torch.normal](https://pytorch.org/docs/stable/generated/torch.normal.html) and [tf.random.normal](https://www.tensorflow.org/api_docs/python/tf/random/normal) also accept a mean/loc and std parameter so I think for most people it would be expected to be able to do this.

**Comment by noahfarr** [comment]
FYI: I created a pull request

**Comment by angeloskath** [comment]
I am closing this issue since the PR is merged
