### ISSUE TITLE
When I run the demo I get the following error（ mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')）

### ISSUE THREAD

**Issue by SUPRyu** [ml-explore/mlx#621]
My DEMO:
`from mlx_lm import load, generate

model, tokenizer = load("mlx-community/deepseek-coder-1.3b-instruct-mlx")
response = generate(model, tokenizer, prompt="hello", verbose=True)
`

ERROR:
`Traceback (most recent call last):
  File "/Users/11103926/PycharmProjects/pythonProject/main.py", line 1, in <module>
    from mlx_lm import load, generate
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mlx_lm/__init__.py", line 1, in <module>
    from .convert import convert
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mlx_lm/convert.py", line 9, in <module>
    import mlx.core as mx
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mlx/core.cpython-311-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mlx/core.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mlx/core.cpython-311-darwin.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mlx/core.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
`
MY ENVIRONMENT：
Apple M2

**Comment by awni** [comment]
It looks like you're environment wants `x86` which means some critical part of your setup is not native.

Could you check `python -c "import platform; print(platform.processor())"`?

Also how did you install mlx? What version? `python -c "import mlx.core; print(mlx.core.__version__)"`

What MacOS are you on?

**Comment by SUPRyu** [comment]
I think I know the reason, because my pycharm does not use native python. 
Thank you very much！
![image](https://github.com/ml-explore/mlx/assets/34652607/2cd84bed-3767-4ec0-bafe-2bf3b8d2be82)
