### ISSUE TITLE
[Feature request] Add metadata to safetensors saving and loading

### ISSUE THREAD

**Issue by mzbac** [ml-explore/mlx#633]
Just found the model weight saved in SafeTensor by mlx cannot be loaded by Transformers. An error is thrown, stating that the format is not supported. This issue seems to caused from the metadata format being saved as `mlx` (https://github.com/ml-explore/mlx/blob/main/mlx/io/safetensor.cpp#L165). However, mlx has no trouble loading HF model weights. so, I'm curious about the differences in the saved weights between them. 
Thanks in advance.

**Comment by mzbac** [comment]
FYI, there is the code where the transformers throw an error -> https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_utils.py#L507

**Comment by awni** [comment]
Ah I see. That is actually expected. The `metadata` can contain anything. So the caller is just using the metadata there as a way to determine when it's safe to continue with the file they are loading. It's on the saver to put the right field in the `metadata`.

I'm curious, how did this come up? Were you trying to load a MLX saved model via Transformers?

**Comment by mzbac** [comment]
Yeah, I try to load the mlx fine-tuned model via transformer, so I can do some advanced quantization using gptq/awq. also, currently, mlx-lm lacks support for loading and sharing custom models., loading mlx from transformer is the easiest way to share custom models at the moment.

**Comment by awni** [comment]
Got it. 
- I think I will change this to a feature request for metadata in `save_safetensors`. That's what we'd need for the current path to work
- 
- In the interim, you should be able to use the safetensors package directly to save the MLX weights:

```shell
>>> from safetensors.mlx import save_file
>>> import mlx.core as mx
>>> params = {"weight": mx.array([1.0, 2.0])}
>>> save_file(params, "model.safetensors", metadata={"format": "pt"})
>>> f = safe_open("model.safetensors", framework="pt")
>>> print(f.metadata())
{'format': 'pt'}
>>> f.get_tensor("weight")
tensor([1., 2.])
```

**Comment by mzbac** [comment]
Thanks, @awni. I will try the safetensors package for now

**Comment by dc-dc-dc** [comment]
I can add metadata support to our implementation. 

I think that the temporary workaround should be used with caution as there are some slight differences in how we store data in comparison with torch. For example Convolutions are stored as `BCHW` in torch vs `BHWC` in mlx. 

We might want to open a pr with transformers to handle mlx properly?  Also this might impact us as well. Thoughts on this @awni

**Comment by awni** [comment]
1. Adding metadata for MLX would be awesome!

2. It's a great point re convolutions / caution with loading into a model from a different framework. But I don't think they will want to change it at the array i/o level which is quite unopinionated regarding how tensors are stored. My thought is that is better handled by reading metadata at the NN level.

**Comment by vincentdsf** [comment]
Would this enable to convert custom models not supported right now? I tried to convert a CodeT5 Transformer Model, but it doesnt seem supported yet so I figured I´d have to wait.

**Comment by awni** [comment]
Hmm, that is not an MLX bug but an issue with `bfloat16` in `safetensors`.

**Comment by awni** [comment]
I filed an issue with safetensors: https://github.com/huggingface/safetensors/issues/436

**Comment by dc-dc-dc** [comment]
Looks like they are trying to convert to numpy before saving so bfloat wont work
