### ISSUE TITLE
[BUG] Int mod mismatch

### ISSUE THREAD

**Issue by dc-dc-dc** [ml-explore/mlx#650]
**Describe the bug**

Results from mod on ints differs from numpy
Data types affected
- int8
- int16
- int32
- int64

**To Reproduce**

Include code snippet
```python
import mlx.core as mx
mx.array([-4, 7, 5, 4, -7, 8], dtype=mx.int8) % mx.array([2, -3, 8, -2, 3, 5], dtype=mx.int8)
# array([0, 1, 5, 0, -1, 3], dtype=int8)

import numpy as np
np.array([-4, 7, 5, 4, -7, 8], dtype=np.int8) % np.array([2, -3, 8, -2, 3, 5], dtype=np.int8)
# array([ 0, -2,  5,  0,  2,  3], dtype=int8)
```

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.1.2
 - Version latest

**Comment by awni** [comment]
Closed in #641
