### ISSUE TITLE
[Question] Freezing a module from within a method

### ISSUE THREAD

**Issue by a1eaiactaest** [ml-explore/mlx#655]
I have read #127 and #141, but can't come up with a solution to my problem.
Having this PyTorch code:
```python3
class MyModule(nn.Module):
  def __init__(self, x: int, y: int):
    super().__init__()

    self.tensor1 = torch.randn(5,5,5) # want only this one in the buffer
    self.tensor2 = torch.randn(5,5,5)
    self.register_buffer('tensor1', tensor1)
```
Would the MLX equivalent look like the following?
```python3
class MyModule(mlx.nn.Module):
  def __init__(self, x: int, y: int):
    super().__init__()

    self.tensor1 = mx.random.normal([5,5,5]) # want only this one frozen
    self.tensor2 = mx.random.normal([5,5,5])

    # freezing the module, is this form possible?
    self.freeze()
    # now unfreeze only the ones that meet some conditions
    self.apply_to_modules(lambda k, v: v.unfreeze() if ...) # some condition
```
Is there a more efficient way especially if I want to freeze only *one* parameter? In this case there are only 2 parameters, hence running `apply_to_modules` isn't that unefficient, but suppose there are 10 parameters and only one has to be frozen. Is there a way to do that without iterating over all of the paramters?

**Comment by awni** [comment]
`freeze` takes optional `keys` for parameters you want to freeze. To do what you want you can do:

```python
self.freeze(keys=["tensor1"], recurse=False)
```

**Comment by awni** [comment]
Probably the above is right for your use case. But for constants that you don't want in `Module.parameters()` you can also do `self._tensor1 = mx.array(...)`. Then it will be frozen (and it won't even be in the model's parameters, so it's effectively a hardcoded constant.

**Comment by a1eaiactaest** [comment]
> Probably the above is right for your use case. But for constants that you don't want in `Module.parameters()` you can also do `self._tensor1 = mx.array(...)` (i.e. start the name with an `_`). Then it will be frozen (and it won't even be in the model's parameters, so it's effectively a hardcoded constant.

Ohh this is smart. Thank you for your reply!
