### ISSUE TITLE
[Feature request]  Add support atleast_1d,2d and 3d

### ISSUE THREAD

**Issue by abdussamettrkr** [ml-explore/mlx#668]
Add support atleast1d,2d and 3d primitives

**Comment by awni** [comment]
I didn't know about those but I do see they are in NumPy, are they used much?  They are pretty easy to implement using existing ops:

```
def atleast_1d(a):
  return a[None] if a.ndim == 0 else a
```

**Comment by abdussamettrkr** [comment]
I am using these functions in my projects, but I suppose they're not as crucial. As you mentioned, it's easy to implement. If anyone thinks it's necessary, I can work on it.

**Comment by hinriksnaer** [comment]
I added a [push request](https://github.com/ml-explore/mlx/pull/689) for the feature request.

**Comment by hinriksnaer** [comment]
I think it's safe to close this one.
