### ISSUE TITLE
[BUG] Compilation error with space character in path

### ISSUE THREAD

**Issue by TristanBilot** [ml-explore/mlx#669]
**Describe the bug**
This issue originally comes from https://github.com/ml-explore/mlx/pull/662#issuecomment-1937059692
I've found the origin of the compilation error: when building mlx from a path comprising a space character, it fails.

**To Reproduce**

Include code snippet
```python
git clone https://github.com/ml-explore/mlx.git
mkdir "a folder"
mv mlx "a folder" && cd "a folder"
cd mlx && mkdir build && cd build
cmake .. && make -j
```

**Desktop (please complete the following information):**
 - MacOS 14.2
 - cmake version 3.28.2
 - GNU Make 3.81

**Comment by awni** [comment]
Thanks for debugging this! Easy fix when we know the exact problem 😄
