### ISSUE TITLE
[Feature] Support cumsum (and other scans) on 64-bit types

### ISSUE THREAD

**Issue by TristanBilot** [ml-explore/mlx#673]
**Describe the bug**
When applying cumsum to an int64 array, there's a kernel error.

**To Reproduce**

```python
import mlx.core as mx

a = mx.array([0, 1, 2], dtype=mx.int64)
mx.cumsum(a)

>>> libc++abi: terminating due to uncaught exception of type std::runtime_error: [metal::Device] Unable to load kernel contiguous_scan_inclusive_sum_int64_int64

[1]    48047 abort      python
```

**Desktop (please complete the following information):**
 - macOS 14.2
 - branch: main

**Comment by awni** [comment]
This is expected in as much as we don't have implementations of these for `int64`. Are you able to use a 32 bit type as a workaround?

**Comment by TristanBilot** [comment]
Ok, just wanted to open an issue in case. Yes I can work with int32 here.
