### ISSUE TITLE
iteration over array significantly slower than numpy

### ISSUE THREAD

**Issue by francescofarina** [ml-explore/mlx#680]
It seems that iterating over the rows of a mlx array is significantly slower than doing the same operation in numpy. 

For an array with 1 million rows it's about 20 times slower than numpy on my M3 Pro.

**To reproduce**

```python
import timeit

import mlx.core as mx
import numpy as np


def iterate_np(x):
    for el in np.array(x):
        pass


def iterate_mlx(x):
    for el in x:
        pass

x = mx.ones((1_000_000, 2))
times = timeit.Timer(lambda: iterate_np(x)).repeat(repeat=10, number=1)
print(min(times))
>>> 0.027s

times = timeit.Timer(lambda: iterate_mlx(x)).repeat(repeat=10, number=1)
print(min(times))
>>> 0.55s

```

**Additional details**
Related to https://github.com/mlx-graphs/mlx-graphs/pull/87

My setup:
- M3 Pro
- MacOS 14.2
- branch: main

**Comment by francescofarina** [comment]
Converting each row to a list during the iteration increases the gap further and exponentially as the dimension grows.

```python
import timeit

import mlx.core as mx
import numpy as np


def iterate_np(x):
    for el in np.array(x):
        el.tolist()


def iterate_mlx(x):
    for el in x:
        el.tolist()


x = mx.ones((1_000, 2))
times = timeit.Timer(lambda: iterate_np(x)).repeat(repeat=10, number=1)
print(min(times))
>>> 0.00015s

times = timeit.Timer(lambda: iterate_mlx(x)).repeat(repeat=10, number=1)
print(min(times))
>>> 0.015s

x = mx.ones((10_000, 2))
times = timeit.Timer(lambda: iterate_np(x)).repeat(repeat=10, number=1)
print(min(times))
>>> 0.00061s

times = timeit.Timer(lambda: iterate_mlx(x)).repeat(repeat=10, number=1)
print(min(times))
>>> 0.21s

x = mx.ones((100_000, 2))
times = timeit.Timer(lambda: iterate_np(x)).repeat(repeat=10, number=1)
print(min(times))
>>> 0.0057s

times = timeit.Timer(lambda: iterate_mlx(x)).repeat(repeat=10, number=1)
print(min(times))
>>> 2.15s
```

However, the `tolist()` seems not to be a major bottleneck especially as the size of the array grows (see below)
```python
import timeit

import mlx.core as mx
import numpy as np


def iterate_np(x):
    np.array(x).tolist()


def iterate_mlx(x):
    x.tolist()


x = mx.ones((1_000))
times = timeit.Timer(lambda: iterate_np(x)).repeat(repeat=100, number=100)
print(min(times))
>>> 0.0007s

times = timeit.Timer(lambda: iterate_mlx(x)).repeat(repeat=100, number=100)
print(min(times))
>>> 0.0025s

x = mx.ones((10_000))
times = timeit.Timer(lambda: iterate_np(x)).repeat(repeat=100, number=100)
print(min(times))
>>> 0.0068s

times = timeit.Timer(lambda: iterate_mlx(x)).repeat(repeat=100, number=100)
print(min(times))
>>> 0.0095s

x = mx.ones((100_000))
times = timeit.Timer(lambda: iterate_np(x)).repeat(repeat=100, number=100)
print(min(times))
>>> 0.069s

times = timeit.Timer(lambda: iterate_mlx(x)).repeat(repeat=100, number=100)
print(min(times))
>>> 0.071s

```

**Comment by awni** [comment]
Oh yes, that is not surprising at all, you are launching 1M GPU kernels there to slice out each `2D` bit of the array. Every GPU kernel comes with substantial overhead compared to a CPU function and as such I would strongly encourage you not to use a pattern like that, it will be very difficult to make it fast in the near future.

May I ask why are you doing that? Almost always there a vectorizable alternative, especially with VMAP.

**Comment by francescofarina** [comment]
Ah yes, right - I should have thought about that, apologies!

The reason why I'm doing that is because, given two arrays representing the edge index of a graph, we need to check which edge of one graphs (hence cols or rows of the array) are also edges of the other one.

I'll look into vectorize it via VMAP or stick with cpu ops.
