### ISSUE TITLE
Chat with Apple silicon

### ISSUE THREAD

**Issue by Isaina** [ml-explore/mlx#695]
Hi, can you make new GitHub project with simple application and model optimized for Apple silicon  mod with futures like Chat with RTX, pdf word document summarization, xls and data summarization etc.

**Comment by awni** [comment]
Hi! This is outside the scope of the core MLX library. Feel free to start a discussion about working on something that suits your needs with the community!

**Comment by Isaina** [comment]
If there someone who have knowledge to build some thing like this for Apple silicon https://github.com/NVIDIA/trt-llm-rag-windows
