### ISSUE TITLE
Add INT4 quantized GEMV metal kernel

### ISSUE THREAD

**Issue by casper-hansen** [ml-explore/mlx#71]
For running on-device, it would be hugely beneficial if `mlx` could support quantized kernels. I am the author of [AutoAWQ](https://github.com/casper-hansen/AutoAWQ) which is a framework that allows users to quantize all the new large language models with minimal loss in performance.

When developing AutoAWQ, I always have to SSH into a machine with a CUDA device since it is not adapted to Metal kernels. If `mlx` adds support for a quantized GEMV kernel, that could change, and it would mean users could run inference on-device.

- Support GEMV
- Support for zero point
- Support for grouped channel-wise scales
- Unpacking weights and running matrix multiplication over a certain number of groups

Reference to CUDA kernel: https://github.com/casper-hansen/AutoAWQ/blob/main/awq_cuda/quantization/gemv_cuda.cu
Other Metal kernels that are related to AWQ: https://github.com/mit-han-lab/TinyChatEngine/tree/main/kernels/metal

**Comment by angeloskath** [comment]
This is on main now (will be on PyPI soon) so we can close the issue. Feel free to reopen if needed.

**Comment by casper-hansen** [comment]
> This is on main now (will be on PyPI soon) so we can close the issue. Feel free to reopen if needed.

That's amazing to see! A few question.
- Will there be any usage guide for these kernels? 
- It looks like we have to implement the dequantization separately, is that correct? If yes, are there any plans to add dequantization methods?

**Comment by angeloskath** [comment]
There is an example already merged in `mlx-examples`. TL;DR is that you can use `QuantizedLinear` as a module or `mx.quantized_matmul` as an op.

For quantizing and dequantizing, there are already `mx.quantize` and `mx.dequantize` operations and a helper in `nn.QuantizedLinear.from_linear` or `nn.QuantizedLinear.quantize_module`.
