### ISSUE TITLE
Upsample support

### ISSUE THREAD

**Issue by Dam930** [ml-explore/mlx#73]
I would like to request the addition of native support for the Upsample operation in MLX. Currently, the absence of Upsample functionality limits the flexibility of certain tasks that require resizing or upsampling of data (like UNet definition).

In the meanwhile, does someone have alternative methods for emulating the upsample functionality?

Thank you!

**Comment by StanislavNikolov** [comment]
See the upsample_nearest function the [Stable Diffusion example](https://github.com/ml-explore/mlx-examples/blob/main/stable_diffusion/stable_diffusion/unet.py#L126):

```python
def upsample_nearest(x, scale: int = 2):
    B, H, W, C = x.shape
    x = mx.broadcast_to(x[:, :, None, :, None, :], (B, H, scale, W, scale, C))
    x = x.reshape(B, H * scale, W * scale, C)

    return x
```

**Comment by Dam930** [comment]
Thank you very much! If you do not plan to implement a standalone class, it is possible for me to close the issue.
