### ISSUE TITLE
Publish sdist into pypi

### ISSUE THREAD

**Issue by chenrui333** [ml-explore/mlx#736]
👋 looks like sdist is missing on pypi, so raise this issue to get sdist published there. Thanks!

**Comment by awni** [comment]
Just curious why do you want that?

**Comment by chenrui333** [comment]
@awni there are many reasons:

- homebrew can use pypi sdist to do the dependency resolution
- pypi artifact has better source tarball stability than github one (there are some recent issues with the default github source tarballs)

Let me know if that makes sense. Thanks!

**Comment by awni** [comment]
Makes sense. I'd need to check if there is a way to control what platforms the sdist is compatible with. We don't want to allow any platform (e.g. old OS's and x86) because MLX is not really compatible with them. It's better that it fails to find the dist rather than try to build from source.

Do you happen to know if that's possible?

**Comment by chenrui333** [comment]
maybe you can do something like this? 

https://github.com/wbond/package_control/blob/master/package_control/deps/oscrypto/_mac/_security_ctypes.py#L31-L35

```
version = platform.mac_ver()[0]
version_info = tuple(map(int,  platform.mac_ver()[0].split('.')))

if version_info < (10, 7):
    raise OSError('Only OS X 10.7 and newer are supported, not %s.%s' % (version_info[0], version_info[1]))
```

**Comment by awni** [comment]
I appreciate the rational but I don't think it's strong enough to support publishing an sdist to pypi. Since MLX is primarily intended for Apple silicon, we will publish wheels for all supported platforms. For unsupported platforms (which should be rare), using GitHub is sufficient for now..
