### ISSUE TITLE
[Question] torch's `Tensor.contiguous` equivalent

### ISSUE THREAD

**Issue by a1eaiactaest** [ml-explore/mlx#750]
`Tensor.contiguous` reference [here](https://pytorch.org/docs/stable/generated/torch.Tensor.contiguous.html).

Code I would like to rewrite in mlx:
```python3
attended_values = (
  attended_values.transpose(1, 2)
  .contiguous()
  .view(x.size(0), -1, self.hidden_size)
)
```

**Comment by awni** [comment]
There is no `contiguous`. The layout is an implementation detail in MLX.

You can do something like: `attended_values.swapaxes(1, 2).reshape(x.shape[0], -1, self.hidden_size)`

**Comment by a1eaiactaest** [comment]
Thank you @awni!
