### ISSUE TITLE
libc++abi: terminating due to uncaught exception of type std::runtime_error: [Matmul::eval_cpu] Currently only supports float32

### ISSUE THREAD

**Issue by nxphi47** [ml-explore/mlx#753]
**Describe the bug**

I got libc++abi: terminating due to uncaught exception of type std::runtime_error: [Matmul::eval_cpu] Currently only supports float32 when trying to run mlx-lm on any model

**To Reproduce**

Include code snippet
```python
from mlx_lm import load, generate

model, tokenizer = load("mlx-community/Qwen1.5-0.5B-Chat-4bit")
prompt = "hello"

messages = [
{"role": "system", "content": "You are a helpful assistant."},
{"role": "user", "content": prompt}
]

text = tokenizer.apply_chat_template(
messages, tokenize=False, add_generation_prompt=True)

response = generate(model, tokenizer, prompt=text, verbose=True, max_tokens=200)

```

**Output**
```
==========
Prompt: <|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
hello<|im_end|>
<|im_start|>assistant

libc++abi: terminating due to uncaught exception of type std::runtime_error: [Matmul::eval_cpu] Currently only supports float32.
zsh: abort      python

```

**Expected behavior**
model should generate as normal

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 14.3.]
 - Apple M1 Pro 16GB RAM

**Comment by awni** [comment]
Looks like it's running on the cpu 🤔 . I have no idea why that is the case.. 

How did you install MLX? Could you share the output of:

```shell
python -c "import mlx.core as mx; print(mx.metal.is_available())" 
```

**Comment by nxphi47** [comment]
> Looks like it's running on the cpu 🤔 . I have no idea why that is the case..
> 
> How did you install MLX? Could you share the output of:
> 
> ```shell
> python -c "import mlx.core as mx; print(mx.metal.is_available())" 
> ```

It's False. Seems metal is not working.

I install it with pip install --upgrade mlx , mx.__version__== 0.4.0

**Comment by nxphi47** [comment]
@awni 
Actually, pip install didn't work,

```
pip install mlx
ERROR: Could not find a version that satisfies the requirement mlx (from versions: none)
ERROR: No matching distribution found for mlx
```

So I changed to `conda install -c conda-forge mlx`, then I got that error.

**Comment by awni** [comment]
Oh shoot, so the conda install does not have the Metal back-end built... that is not good.

**Comment by awni** [comment]
Also why did the pip install not work for you, that is very strange.. and suggests something is off with your environment.

Can you check the [install docs](https://ml-explore.github.io/mlx/build/html/install.html#troubleshooting). Probably you are using a non-native Python.

**Comment by awni** [comment]
Interesting, so if I install with conda it works fine. So conda must have a distribution which does not require metal.. that's a bit of a trap unfortunately.

**Comment by nxphi47** [comment]
> Also why did the pip install not work for you, that is very strange.. and suggests something is off with your environment.
> 
> Can you check the [install docs](https://ml-explore.github.io/mlx/build/html/install.html#troubleshooting). Probably you are using a non-native Python.

You're right. `python -c "import platform; print(platform.processor())"` give i386. I will try installing the native python and update with you. Thanks!
