### ISSUE TITLE
Repo for MLX Models and pre-trained weights

### ISSUE THREAD

**Issue by NripeshN** [ml-explore/mlx#754]
How about we set up a simple, easy-to-navigate repo dedicated to MLX models and their pre-trained weights? It could be a go-to spot for everyone looking to find popular machine learning models crafted in MLX.

**Comment by awni** [comment]
I think something like a model zoo is a great idea! There is an open discussion about it #242 maybe you can comment there. I will close this in favor of the discussion.

We will probably not do this ourselves in the very near future as we are still prioritizing perf + features. But I would be very glad to see a community lead project there!
