### ISSUE TITLE
Memory leak in MLX / Metal / MPS

### ISSUE THREAD

**Issue by geraltFromRivia** [ml-explore/mlx#755]
**Bug / issue description**
I am currently running into an issue of MLX / PyTorch MPS taking up too much memory during text generation. Even if I run a smaller model, e.g. a quantized Mistral-7B-Instruct, but the end of text generation my M3 Max MBP with 64GB of RAM is pretty much out of memory (see memory usage in attached images. I was wondering if there is a memory leak in MLX / MPS, as I am getting the same issue when running text generation using either MLX or PyTorch with MPS backend. Or is this an issue of Python no de-allocating memory? I do not get the same issue with LMStudio or if I generate text using PyTorch with CPU back-end (painfully slow).

**To Reproduce**
Create a conda environment with python=3.11 and install the following packages:
```python
   conda install pytorch::pytorch torchvision torchaudio -c pytorch
   conda install -c conda-forge mlx mlx-lm
```

Include code snippet
```python
python -m mlx_lm.generate \
    --model /path/to/checkpoint/mlx-community/Mistral-7B-Instruct-v0.2-8-bit-mlx  \
    --prompt "Write a short essay about the first generation of Pokemon games (Pokemon Red and Blue in EU /US) and their impacts on the world." \
    --max-tokens 1024
```

![01_memory_usage_before_model_loading](https://github.com/ml-explore/mlx/assets/31942567/61f52fad-1e0e-40e2-ab5b-9c238709ab50)
![02_memory_usage_after_model_loading](https://github.com/ml-explore/mlx/assets/31942567/38cef454-8229-4c36-b1ac-0b6b6d0a7578)
![03_memory_after text_generation](https://github.com/ml-explore/mlx/assets/31942567/97d1beb1-aca5-49b2-9d56-cf664a21d819)

**Comment by awni** [comment]
This is not a leak, it's a combination of the MLX memory cache and the fact that we don't preallocate all used memory which is causing this.

We have a working issue #742 to address memory management in MLX with precisely the goal to fix this.

In the meantime you could see reduced memory use by disabling the cache (at the cost of some generation speed):

E.g. put `mx.disable_cache()` in the code before you start generating text.

**Comment by awni** [comment]
I'm closing this as a dup of #742. We'll use that issue to track memory use issues.
