### ISSUE TITLE
More losses!

### ISSUE THREAD

**Issue by h-0-0** [ml-explore/mlx#76]
Hi, I thought it could be nice if there were a few more losses ready to go in mlx. To start with I was thinking:
- L1_loss (L1 loss)
- mse_loss (mean squared error)

Maybe also:
- nll_loss (negative log likelihood loss)
- kl_div_loss (KL-divergence loss)

Think this should pretty straightforward to do? Simply a case of adding them to python/mlx/nn/losses.py

Any thoughts? And I am happy to work on this issue.

**Comment by h-0-0** [comment]
Hi, I'll implement the L1 and MSE losses in that case, and you are correct about the negative log likelihood! I was just going through the pytorch losses and thinking about which would be the most helpful to add. Of course I'll add docs and testing aswell.

**Comment by awni** [comment]
All the losses in this issue have been pushed to main so I will close it. Feel free to open a new issue for new losses.
