### ISSUE TITLE
[Question] Dilation in `core.conv1d`, but not in `nn.Conv1d`

### ISSUE THREAD

**Issue by a1eaiactaest** [ml-explore/mlx#765]
Since `0.5.0` release there has been a dilation available for convolutions. According to the API reference `dilation` parameter is only available for `mlx.core` convolutions and not for the convolutional layers in `mlx.nn`. Is the implementation of this predicted in the near future?
From what I've seen in source code the `nn.Conv1d` layer is just a call to the `mx.conv1d` function. Would adding the `dilation` parameter to the `Conv1d` layer work? 
If so I can create a PR to implement this.

**Comment by awni** [comment]
Yes, please finish your PR. There is no reason not to make that an option as far as I know (CC @jagrit06 )


If you don't mind:
- Add the option for Conv2D as well
-  Add a couple small tests for the dilation parameter

Otherwise I think that is all you need to have that.

**Comment by a1eaiactaest** [comment]
just added tests in https://github.com/ml-explore/mlx/pull/766/commits/87dc8cd8f5b60c70f732b6326a1f641589fd81b2.
As far as my setup goes all tests for `Conv1d` pass, so please let me know if this test case is sufficient.
I will add dilations to `Conv2d` as well.

**Comment by a1eaiactaest** [comment]
Thanks @awni for feedback, I will close this issue as all the further discussion can be conducted under the #766.
