### ISSUE TITLE
Help adding mlx support for BatchEncoding in transformers

### ISSUE THREAD

**Issue by Y4hL** [ml-explore/mlx#769]
I'm currently trying to get mlx support for batch encoding in the transformers library in this [Pull Request](https://github.com/huggingface/transformers/pull/29406).

However I'm not the most experienced with mlx yet, and would like someone to take a look at it as well. Particularly determining if an array is an mx array, and converting existing arrays to mlx.

**Comment by awni** [comment]
It looks ok to me :). Did you test it?

I will follow the issue you opened in the Transformers repo. You can tag me there or in the PR itself if you have questions.

**Comment by Y4hL** [comment]
> It looks ok to me :). Did you test it?

I tried the mlx_lm server using transformers with my changes, and it worked flawlessly.
