### ISSUE TITLE
[BUG probably?] ValueError: Slice indices must be integers or None

### ISSUE THREAD

**Issue by adhulipa** [ml-explore/mlx#772]
**Describe the bug**
Slice indices seem to require using ints but compared to PyTorch (or event Matlab and other common array processing libs) slice indexing using arrays is supported.  

**To Reproduce**

```python
from mlx.core import *
x = array([18, 47, 56, 57, 58], dtype=int64)
i = array(2)
x[i:i+2]
"""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Slice indices must be integers or None.
"""
```

**Expected behavior**

```python
.... 
array([56, 57])
```

Something similar to PyTorch for example:

```python
from torch import *
t = tensor([18, 47, 56, 57, 58])
j = tensor(2)
print(t[j:j+2])
"""
# should print out
tensor([56, 57])
"""
```

**Desktop (please complete the following information):**
 - OS Version: 14.1 (23B73)
 - MLX Version: 0.5.0 I think. Prior version was 0.0.10

```
↪ pip install -U mlx
Looking in indexes: https://pypi.python.org/simple, https://pypi.apple.com/simple
Requirement already satisfied: mlx in /Users/adi/miniconda3/envs/mlx-examples/lib/python3.11/site-packages (0.0.10)
Collecting mlx
  Downloading mlx-0.5.0-cp311-cp311-macosx_14_0_arm64.whl.metadata (5.0 kB)
Downloading mlx-0.5.0-cp311-cp311-macosx_14_0_arm64.whl (32.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.9/32.9 MB 38.7 MB/s eta 0:00:00
Installing collected packages: mlx
  Attempting uninstall: mlx
    Found existing installation: mlx 0.0.10
    Uninstalling mlx-0.0.10:
      Successfully uninstalled mlx-0.0.10
Successfully installed mlx-0.5.0
```

**Additional context**
I'm not entirely sure how to validate the mlx version im running from within the python kernel.
I suspect the above report is using 0.5.0 but it may be on 0.0.10
Any way I can confirm?  I tried `import mlx; mlx.__version__` as is common with _some_ python packages; but no luck here. Perhaps mlx publishes version via some other attribute?

**Comment by awni** [comment]
This is not a bug... it's expected it doesn't work. In MLX any operation where the output shape is dependent on input array data in not currently supported. (Other examples include boolean masks and the unary `where`).

For this, we could have a version where if the slice arrays are already evaluated then it is ok, otherwise it throws (I don't think it would ever make sense to implicitly eval the array). For now though I think it's simpler to stick to integers (you can always get the item from a scalar array and use that).

**Comment by adhulipa** [comment]
Yup, makes sense. `i.item()` is good enough workaround

**Comment by y8** [comment]
Hi! Indirect indexing using value if `array.item()` doesn't work either:


```python
def indirect(array):
  start = array[0:1].item()
  end = array[1:2].item()

  return array[start:end]

input = mx.arange(10)
input[0] = mx.array([5])
input[1] = mx.array([9])
print(indirect(input))

compiled = mx.compile(indirect)
print(compiled(input))

# → ValueError: [eval] Attempting to eval an array without a primitive.
```

From what you've said, `item()` should evaluate array, return scalar value and after that this scalar value could be used as array index. Or I'm not getting this right?

Thanks!

**Comment by awni** [comment]
You can't compile through an `eval`. 

`.item()` is an implicit `eval` so you cannot compile a function that uses that.

**Comment by y8** [comment]
Aha, that's what I've missing. So code that is supposed to be compiled can't trigger evaluation, and right now, any indexing indirection using values from another `mlx.array` is not possible in compiled code?

With MoE this kind of indirect indexing becomes quite important for expert selection. Maybe there is some hacky workaround?

**Comment by awni** [comment]
> With MoE this kind of indirect indexing becomes quite important for expert selection. Maybe there is some hacky workaround?

It works fine in uncompiled code so just don't compile the parts of the code that need to use an eval.

**Comment by awni** [comment]
> any indexing indirection using values from another mlx.array is not possible in compiled code?

You can always use an `array` to index another `array` even in compiled code. What you are doing is evaluating an array and getting a Python object out of it and using that. The evaluation is the problem for the compiled code.

**Comment by y8** [comment]
> You can always use an `array` to index another `array` (except for boolean indices)

Oh, [right](https://ml-explore.github.io/mlx/build/html/usage/indexing.html#indexing-arrays)! Is it possible to use another array as range slice, not list of indexes? 

```python
import mlx.core as mx

print(mx.__version__)
# → 0.8.0

def indirect(array):
  addr = array[0:2]

  return array[addr]

input = mx.arange(10)
input[0] = mx.array([5])
input[1] = mx.array([9])

compiled = mx.compile(indirect)
print(compiled(input))
# → array([5, 9], dtype=int32) 
# expected: [5, 6, 7, 8])
```

**Comment by y8** [comment]
Oops, you told that `In MLX any operation where the output shape is dependent on input array data in not currently supported`, so we can't. 

But that's possible for multi-dimensional arrays, because single index will resolve first dimension:

```python
import mlx.core as mx

print(mx.__version__)
# → 0.8.0

def indirect(array):
  addr = array[0][0]

  return array[addr]

input = mx.array([mx.arange(10), mx.arange(10, 20), mx.arange(20, 30)])
input[0, 0] = 2

compiled = mx.compile(indirect)
print(compiled(input))
# → array([20, 21, 22, ..., 27, 28, 29], dtype=int32)
```

But can it be done for 1d array, if I know the final shape, but want to use another array as starting offset? Seems to satisfy abler requirement, but I can't find operation to do that.

**Comment by awni** [comment]
> But can this be done for a 1d array if I know the final shape but want to use another array as the starting offset?

I'm not 100 % sure I understand your question. But I think you are trying to do something like the following (which does not work):

```python
a = mx.zeros((100,))
a[mx.array(50):]
```

I'm not entirely sure why you want to use an array as the starting offset if you always know the final shape (just use an integer in that case). But one slightly ineffecient workaround would be:

```
```python
a = mx.zeros((100,))
a[mx.arange(50, 100)]
```
