### ISSUE TITLE
[Feature Request] Empty support

### ISSUE THREAD

**Issue by dc-dc-dc** [ml-explore/mlx#781]
Similar to `zeros` except this wouldn't initialize to anything, useful for when you have a temporary buffer that will be overridden later.

**Comment by awni** [comment]
Can you check the response here: https://github.com/ml-explore/mlx/issues/363

And maybe share the use case you were thinking on so we can understand it better.

**Comment by awni** [comment]
Right but maybe you can say more about this future usage. How do you intend to use an empty array? There aren't really in place ops in MLX, so I'm wondering what you want it for?

**Comment by dc-dc-dc** [comment]
Right without in-place the benefit wouldn't be huge but essentially it would be used as a verification for shape / type correctness. As you would be able to compare before accepting an array as the override for the temporary allocation

**Comment by awni** [comment]
> Right without in-place the benefit wouldn't be huge but essentially it would be used as a verification for shape / type correctness

If you don't eval the graph then using zeros vs empty doesn't make any difference there. You can just use zeros

**Comment by awni** [comment]
@dc-dc-dc closing this for now as will not add. If it comes up as more useful in future use cases.. feel free to comment here .. we can always reconsider / reopen this.

**Comment by Lemonade1227** [comment]
I want to use Japanese GPT2 in mlx and am creating a GPT2 module in mlx.nn for that purpose, but I found a tensor with shape [] in the safetensors of the model I plan to use. 
<img width="673" alt="スクリーンショット 2024-03-29 21 47 12" src="https://github.com/ml-explore/mlx/assets/130896166/607d9718-6e27-43b4-9cc9-53be4ae1e163">


 this one —> https://huggingface.co/rinna/japanese-gpt2-small?show_tensors=model.safetensors
 I need Empty in the form of
`    self.masked_bias = mx.empty()`
(I am a beginner, so this could be speculation).

**Comment by awni** [comment]
A tensor without a shape is just a scalar `mx.array(1.0)` (should have an empty shape).

**Comment by Lemonade1227** [comment]
It worked. Thanks awni !
