### ISSUE TITLE
Ability to replace NAN values with zeros in mlx arrays using indices

### ISSUE THREAD

**Issue by kyrollosyanny** [ml-explore/mlx#798]
I have an array that I would like to filter based on its values. The array size does not need to change (i.e. we don't need to remove nan values) but we would like to replace the nan values with zeros or any other number. 

**To Reproduce**

Include code snippet
```
x = mx.array([[1,2,3,4],
              [2,3,np.nan,5],
              [np.nan,5,2,3]])
idx=np.nonzero(np.isnan(x))

x[idx]=0
print(x)

```

**Expected behavior**
Ideally, it would replace the np.nans with zeros. But currently, we get the following error message: ```Cannot index mlx array using the given type yet```

**Comment by awni** [comment]
```bash
>>> x = mx.array([[1,2,3,4],
...               [2,3,np.nan,5],
...               [np.nan,5,2,3]])
>>> mx.where(mx.isnan(x), 0, x)
array([[1, 2, 3, 4],
       [2, 3, 0, 5],
       [0, 5, 2, 3]], dtype=float32)
```
