### ISSUE TITLE
[BUG] Support for Linux Aarch64/Arm 64

### ISSUE THREAD

**Issue by kenmoini** [ml-explore/mlx#808]
**Describe the bug**
Installing on Linux x86_64 works for packages that require MLX as a dependent on Apple Silicon platforms.

However, when running the same installation on Linux Arm 64/Aarch64, the install fails due to a lack of an arm64 package.

**To Reproduce**

On Linux x86_64/Apple Silicon it works as intended - breaks on Linux aarch64:

```bash
pip install mlx
```

**Expected behavior**

The python pip module should install on Linux aarch64.

**Desktop (please complete the following information):**
 - OS Version: RHEL 9.3
 - Version 0.6.0

**Additional context**

There is a released (but old) `mlx-0.2.0-cp311-cp311-manylinux_2_31_x86_64.whl` file, but not one matching aarch64/arm64.

**Comment by awni** [comment]
MLX is designed primarily for Apple silicon so we don't intend to work on support for other platforms! The Linux distribution we have is mostly for testing purposes.
