### ISSUE TITLE
[BUG] Cannot compile training graph

### ISSUE THREAD

**Issue by georgeherbert** [ml-explore/mlx#815]
**Describe the bug**
I cannot compile my training graph. I have followed the documentation on [this](https://ml-explore.github.io/mlx/build/html/usage/compile.html) page to compile the graph. Since I have dropout, I have additionally included `mx.random.state` in my `state` variable. However, when I try to run my code I get the following error:

```
    loss = step(x, y)
           ^^^^^^^^^^
IndexError: unordered_map::at: key not found
```

Any help or guidance on this issue would be much appreciated. I may be doing something wrong here.

**To Reproduce**

Clone my repo https://github.com/georgeherbert/gpt-mlx/ and run `train.py`.

**Expected behavior**

The training graph to compile and training to commence.

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version: 0.6.0

**Comment by awni** [comment]
Looks like a bug in compile, not sure what the issue is yet.

**Comment by awni** [comment]
Fix is in #816 .. should be in the next release this week. Thanks for reporting the issue!

**Comment by soumya-batra** [comment]
Looks like the issue has re-occured on the latest versions (0.29.4 and 0.30.0). When i updated mlx, I started getting this error again when compiling the training graph,  but it works on version 0.29.3. @awni

**Comment by awni** [comment]
@soumya-batra could you please open a a new issue with steps on how to reproduce the error your are seeing?

**Comment by soumya-batra** [comment]
created the new issue here @awni : https://github.com/ml-explore/mlx/issues/2864
