### ISSUE TITLE
[Feature] Support mx.flip

### ISSUE THREAD

**Issue by Rifur13** [ml-explore/mlx#832]
I'm implementing a bidirectional LSTM and need to flip the inputs for the reverse call.

Could it be as simple as reversing the sign of the strides? What edge cases am I missing?

**Comment by awni** [comment]
Yes you can flip an array like:
```
>>> a = mx.arange(4).reshape(2, 2)
>>> a
array([[0, 1],
       [2, 3]], dtype=int32)
>>> a[:, ::-1]
array([[1, 0],
       [3, 2]], dtype=int32)
```

Having a `flip` could be useful though. You could indeed implement it with a slice and negative stride. I don't know of any edge cases that wouldn't work for..

**Comment by Rifur13** [comment]
Thanks! Exactly what I needed.
