### ISSUE TITLE
libc++abi: terminating due to uncaught exception of type std::runtime_error: [Matmul::eval_cpu] Currently only supports float32.

### ISSUE THREAD

**Issue by sajinpgupta** [ml-explore/mlx#851]
Description:
I created a conda instance and installed MLX using conda install -c conda-forge mlx. Following this, I installed the required dependencies using pip install -r requirements.txt. However, during training, I encountered the error "std::runtime_error: [Matmul::eval_cpu] Currently only supports float32".

Environment:

Operating System: macOS (MacBookPro16,1 - 2019)
GPU: Intel UHD Graphics (Model may not have NVIDIA GPUs)
MLX Version: Not specified
Python Version: Not specified
Steps to Reproduce:

Created a conda instance.
Installed MLX using conda (conda install -c conda-forge mlx).
Installed requirements using pip (pip install -r requirements.txt).
Ran 4-bit quantisation using python convert.py --hf-path mistralai/Mistral-7B-v0.1 -q first.
Attempted to train using python lora.py --model mlx_model --train --iters 600.
Additional Information:

The MacBook Pro model may not have NVIDIA GPUs, only Intel UHD Graphics GPU.
Running python -c "import mlx.core as mx; print(mx.metal.is_available())" returned False.
Request:
Can you please provide guidance on resolving this issue and ensuring compatibility with the given hardware environment?

**Comment by awni** [comment]
Yes the problem is you are not using an M-series chip and MLX does not support the non-Apple silicon hardware.

**Comment by sajinpgupta** [comment]
Got it thanks for the speedy response and guidance!! Let me try this on M1 8GB next
