### ISSUE TITLE
Miscalculations in Reduction Operations

### ISSUE THREAD

**Issue by abdussamettrkr** [ml-explore/mlx#855]
There are miscalculations in reduction operations on the GPU. This error occurred with version 0.6.0. Everything works as expected on the CPU.

**To Reproduce**
```python
import mlx.core as mx
arr_r = mx.random.normal((3,2,3,3,3,3))
print(arr_r.sum(axis=[0,1,3,4,5]).sum() - arr_r.sum())
```
Prints a big number ~1.

**Expected behavior**
Should print near to zero.

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.3.1
 - Version:0.7.0

**Comment by awni** [comment]
Interesting.. looks like this is wrong:

```
print(arr_r.sum(axis=[0,1,3,4,5]))
```

**Comment by awni** [comment]
Worked in 0.5.0, so probably related to @jagrit06 reduce update https://github.com/ml-explore/mlx/pull/783

@jagrit06 do you mind taking a look? And we can add this as a test case as well.

**Comment by angeloskath** [comment]
I think this is fine it is just missing the 2nd axis. ie it should be

```python
import mlx.core as mx
arr_r = mx.random.normal((3,2,3,3,3,3))
print(arr_r.sum(axis=[0,1,
                      2,  # <---- this was missing
                      3,4,5]).sum() - arr_r.sum())
```

**Comment by angeloskath** [comment]
@abdussamettrkr I will close the issue but feel free to reopen if you still think there is a bug.

**Comment by awni** [comment]
It's not missing the `2`, that's intentional. There is a sum after the first sum

**Comment by awni** [comment]
The following gives wildly different results on the CPU and the GPU:
```python
arr_r = mx.arange(3*2*3*3*3*3).reshape(3,2,3,3,3,3).astype(mx.float32)
print(arr_r.sum(axis=[0,1,3,4,5]))
```

**Comment by angeloskath** [comment]
> It's not missing the `2`, that's intentional. There is a sum after the first sum

Oops. Sorry about that...
