### ISSUE TITLE
[BUG] Boolean Indices not supported

### ISSUE THREAD

**Issue by NullBy1e** [ml-explore/mlx#860]
**Describe the bug**
When executing the code snippet provided below, I encounter a ``ValueError: boolean indices are not yet supported``.
Is there a workaround available, or is this functionality planned for inclusion in an upcoming release?

**To Reproduce:**
You can one-hot-encode y and generate x from a normal dist for simplicity.
```python
import mlx
import mlx.core as mx

x = mx.random.normal((32,4))
y = mx.round(mx.softmax(mx.random.normal((32,4)), axis=-1))

row_contains_zero = mlx.core.any(y == 0, axis=1)
divergence = mx.zeros_like(x)
divergence[row_contains_zero] = -y[row_contains_zero] * mx.log(
    x[row_contains_zero]
 )  # * Cross Entropy
    ...
```

**Desktop:**
 - OS Version: macOS Sonoma 14.4
 - Version: 0.7.0

**Additional context**
The boolean mask ``row_contains_zero`` is crucial for a loss selection function in my implementation.
I'm adapting this code from PyTorch, so any insights on a possible workaround would be greatly appreciated.

**Comment by awni** [comment]
It's not a bug, here's the [docs](https://ml-explore.github.io/mlx/build/html/usage/indexing.html#differences-from-numpy)

You can probably do a workaround with `mx.where`:

```
divergence = mx.where(row_contains_zero, -y * mx.log(x), mx.zeros_like(x))
```

**Comment by amirhossein-razlighi** [comment]
@awni 
Hi. Isn't it necessary for having a wrapper on calling `mx.where` even if we're using indices? Here's an example that throws exception right now:
```
import mlx.core as mx

a = mx.array([1, 2, 3])
a[mx.greater(a, 2)] = 2 # ValueError: boolean indices are not yet supported
```

**Comment by amirhossein-razlighi** [comment]
Although, here's PyTorch result on the same example:
```
import torch

a = torch.tensor([1, 2, 3])
a[a.gt(2)] = 2 # tensor([1, 2, 2])
```

**Comment by awni** [comment]
No we don't do unary where for the same reason as boolean masking. But you can do that like this:

```python
import mlx.core as mx

a = mx.array([1, 2, 3])
a = mx.where(mx.greater(a, 2),  2, a)
```
