### ISSUE TITLE
requirement for implementing boolean indices for `mx.array`

### ISSUE THREAD

**Issue by amirhossein-razlighi** [ml-explore/mlx#865]
Hi.
There's a need for boolean indexing for a `mx.array`. E.g:
```
arr[mx.greater(arr,-1).all()]
```
But right now, there's this error: "ValueError: boolean indices are not yet supported". If this is a valid requirement, please let me know. I'd be happy to contribute to solve this.
Thanks!

**Comment by awni** [comment]
See https://github.com/ml-explore/mlx/issues/860

**Comment by awni** [comment]
If you have a specific case that you can't come up with a workaround, I'd love to see the example.
