### ISSUE TITLE
comparing python list with `mx.array`

### ISSUE THREAD

**Issue by amirhossein-razlighi** [ml-explore/mlx#866]
Right now, comparing an `mx.array` instance with a python list, encounters error. There's a need for fixing this to pursue the common convention of numpy and PyTorch, so converting from list to `mx.array` is done implicitly (and is not needed to be done explicitly each time).
If this is a valid requirement, please let me know. I'd be happy to help fix this and make a contribution.
Thanks!

**Comment by awni** [comment]
In general NumPy let's you use lists in many places which implicitly convert to `np.ndarray`.

```
>>> np.array([1, 2]) == [1,3]
array([ True, False])
```

In Torch that's more like an object comparison:

```
>>> torch.tensor([1, 2]) == [1,3]
False
```

And in MLX it just throws. I don't think we are going to implicitly convert from list to `mx.array` in our ops. Given that, the `torch` version probably makes the most sense: `__eq__` should not crash if it receives a non`mx.array` it should just return `False`.
