### ISSUE TITLE
[BUG] mlx 0.8.0 indexing seems broken

### ISSUE THREAD

**Issue by mzbac** [ml-explore/mlx#873]
**Describe the bug**

The latest version of MLX 0.8.0 is somehow causing an error with array indexing, but downgrading to 0.7.0 resolves the issue.

**To Reproduce**

Include code snippet
```python
import mlx.core as mx

indices = mx.array([0, 1])

logits = mx.array([[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]])

selected = logits[:, indices]

selected = 0 * selected

logits[:, indices] = selected

```

**Expected behavior**
it shouldn't throw the error `ValueError: Cannot broadcast array of shape (2) into shape (2,1).`

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 14.1.2]
 - Version [0.8.0]

**Additional context**
This is causing the mlx_lm.server to break on https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/utils.py#L114, as the repetition penalty is enabled by default.

**Comment by awni** [comment]
Does look like a bug, here's a simpler repro:

```python
indices = mx.array([0, 1])
logits = mx.array([[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]])
logits[:, indices] = mx.zeros((1, 2))
```

**Comment by awni** [comment]
@jagrit06 most likely related to https://github.com/ml-explore/mlx/pull/861, would you mind checking and adding as a test case if it makes sense?

**Comment by jagrit06** [comment]
Looking into it

**Comment by awni** [comment]
This closed right?
