### ISSUE TITLE
[BUG] No auto-generated stub files for `mlx.core` for `0.8.0`

### ISSUE THREAD

**Issue by gau-nernst** [ml-explore/mlx#884]
**Describe the bug**
When I install mlx from pip, the latest version `0.8.0` does not have auto-generated stub files for `mlx.core`, thus there is no type hint in VSCode. When I install version `0.7.0`, there are stub files. It's probably a bug introduced when mlx switched to nanobind.

A quick GitHub search shows that there is indeed a command that generates stub files, but perhaps there is a bug in the config somewhere that the stub files are not included in the pip package.

https://github.com/ml-explore/mlx/blob/be98f4ab6be2e466e2ebf59622e5f4866b6527e2/setup.py#L136-L139
https://github.com/ml-explore/mlx/blob/be98f4ab6be2e466e2ebf59622e5f4866b6527e2/.circleci/config.yml#L43-L47

**To Reproduce**
NA

**Expected behavior**
There are stub files.

**Desktop (please complete the following information):**
 - OS Version: 14.2
 - Version 0.8.0

**Additional context**
NA

**Comment by awni** [comment]
Thanks for flagging, I will check!

**Comment by awni** [comment]
Should be fixed in `0.8.1` if you `pip install -U mlx` you will get that.
