### ISSUE TITLE
[FEATURE] `mlx.nn.Module` to return `self` in some methods to support chaining

### ISSUE THREAD

**Issue by gau-nernst** [ml-explore/mlx#885]
Currently many "self-modification" methods of `mlx.nn.Module` return None. If we return `self` instead, we can do chaining to improve user experience.

Some methods that would be useful to return self
- `.freeze()`, `.unfreeze()`
- `.train()`, `.eval()`

Some examples of better UX

```python
# create a model and put it in eval mode
model = nn.Transformer().eval()

# only train biases (example from MLX doc)
model.freeze().unfreeze(keys="bias")
```

**Comment by awni** [comment]
This seems like a simple and nice usage improvement to me. I will mark it as an enhancement.

**Comment by gau-nernst** [comment]
I can submit a PR for this if that's ok with you.
