### ISSUE TITLE
Not able to convert quantized Mistral 7B to GGUF

### ISSUE THREAD

**Issue by rshah918** [ml-explore/mlx#887]
**Describe the bug**
I fine-tuned Mistral 7B, quantized, using Lora. I then tried using llama.cpp to convert the lora_fused_model to gguf format, but receive an error. Seems like the only way to achieve this conversion is to first dequantize, then convert to GGUF in llama.cpp, and then re-quantize. Unfortunately, dequantizing and requantizing seems to lobotomize the model.

**To Reproduce**

1) Download quantized base model: `python3 convert.py --hf-path mistralai/Mistral-7B-Instruct-v0.2 -q --q-bits 8`

2) Fine tune: `python3 lora.py --model ./mlx_model --train --iters 700 --batch-size 1 --lora-layers 8`

3) Fuse Lora layers to the model: `python3 fuse.py --model mlx_model \
 --adapter-file ./adapters.npz`

4) Switch to Llama.cpp and run: `python3 convert.py ./lora_fused_model`

You will see the following error message:

`
 874, in convert
    data_type = SAFETENSORS_DATA_TYPES[info['dtype']]
                ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'U32'
`

**Expected behavior**
Ideally, I would be able to convert the quantized fused model into GGUF format WITHOUT first de-quantizing. 

**Desktop (please complete the following information):**
 - OS Version: macOS Sonoma
 - Version 14.4 (23E214)

**Additional context**

I can't fine tune Mistral 7B on my machine (M2 MacBook Air, 16GB) without quantization, so not being able to convert this to GGUF is a big blocker. Is there any suggested workaround? Is there a framework to run fast inference on the .safetensors thats not specific to apple silicon?

**Comment by awni** [comment]
Just curious, why do you want to convert to GGUF?

**Comment by rshah918** [comment]
@awni I use a llama.cpp server for inference, and im under the impressing that I need to use gguf format for that. (please correct me if Im wrong!).

Is there another framework you'd recommend that can run the .safetensors directly?

**Comment by awni** [comment]
Do you serve on Mac or on a different machine?

For Apple silicon, yes.. MLX LM can in fact do some of that directly, see the [docs on serving](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/SERVER.md)

For non-Apple silicon machines, not really, GGUF is a good bet.

**Comment by rshah918** [comment]
Ah yea thats the problem, I will be deploying this to a non apple silicon machine

**Comment by awni** [comment]
Makes sense.. good to know, thanks!

> dequantizing and requantizing seems to lobotomize the model.

I assume you mean it makes the performance bad? That's one thing we should look into.. it shouldn't be that bad.

As for supporting saving directly to quantized GGUF.. it's a possibility. We haven't decided yet if we will support that in core but it's good to know of your use case!

**Comment by rshah918** [comment]
#I assume you mean it makes the performance bad? That's one thing we should look into.. it shouldn't be that bad.

Correct, as if a lot of my fine tuning got erased in the process. 

Is dequantizing mainly just padding on zeros at the end of the weights? And if so, then shouldn't dequantizing back to the original size result in no change in performance (in theory)? Or is some performance degradation inevitable during this process?

**Comment by rshah918** [comment]
@awni Hey I don't think there's an issue with de-quantizing. I noticed that the model starts acting goofy after fusing. I didn't realize this before as I wouldn't test the model until after converting to GGUF. See my comment: https://github.com/ml-explore/mlx-examples/issues/507#issuecomment-2017123532

**Comment by awni** [comment]
Right right yea that agrees with my own experience. Fusing the adapters can cause issues if the adapter values are very small compared to the base weights. You can play around with the scale parameter (increase it) to see if that helps get bigger adapters that don't get erased during fusion.

**Comment by rshah918** [comment]
Where is the scale parameter?

Also I notice that server.py doesn't seem to use the adapter file even when passing it in as a parameter. Maybe it's fusing before running?

**Comment by awni** [comment]
> Where is the scale parameter?

[This one](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/examples/lora_config.yaml#L61)

> Also I notice that server.py doesn't seem to use the adapter file even when passing it in as a parameter. Maybe it's fusing before running?

Looks to me like it's [being used](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/server.py#L448), what make you say that?

**Comment by rshah918** [comment]
Gotcha thanks!

Because running the model and adapter using lora.py results in intended model behavior. But passing in the model and adapter to server.py results in my fine-tuning disappearing from the model.

**Comment by awni** [comment]
> But passing in the model and adapter to server.py results in my fine-tuning disappearing from the model.

That's very odd 🤔 . The server.py is using the same `load` and `generate_step` function so it should be doing more or less the exact same thing. One thing to check would be to make sure you are setting the same arguments (temperature, prompt, etc). It's certainly possible there is a bug somewhere.. they should behave the same way assuming you are giving them the same inputs.

**Comment by awni** [comment]
Closing this as a dup of #814. Regarding possible issues with server.py feel free to post here or make a new issue in mlx-examples!
