### ISSUE TITLE
Unsqueeze with None not working

### ISSUE THREAD

**Issue by abdussamettrkr** [ml-explore/mlx#898]
Unsqueeze array with None is not working in some conditions.

**To Reproduce**

```python
import mlx.core as mx
print(mx.ones((5,5,5))[:,None].shape)
```
prints: (5, 5, 5)

In Numpy

```python
import numpy as np
print(np.ones((5,5,5))[:, None].shape)
```
prints: (5, 1, 5, 5)

**Expected behavior**
Same shape with Numpy.

 - OS Version: MacOS 14.3.1
 - Version: 0.8.1

**Comment by awni** [comment]
Looks like a bug. @jagrit06 can you check it? I guess related to https://github.com/ml-explore/mlx/pull/879 as it was working in 0.8.0 but broken on main. Probably good to add a test case as well.

**Comment by abdussamettrkr** [comment]
Can I solve this bug? I found the problem, and solved. Pushing the code

**Comment by awni** [comment]
Of course!
