### ISSUE TITLE
implementation of bool -> int cast for `mx.array`

### ISSUE THREAD

**Issue by a1eaiactaest** [ml-explore/mlx#900]
As far as I know currently if someone would want to convert the array full of bools to an array full of ints (`True` ->`1` and `False` -> `0`) the way to do it is:
```python3
x = mx.random.normal((32,4))
y = (x >= 1)
print(y)
'''
array([[False, False, False, False],
       [True, False, False, False],
       [False, False, True, False],
       ...,
       [True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]], dtype=bool)
'''
z = y*1
print(z)
'''
array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       ...,
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)
'''
```
How about implementing something like torch's `tensor.int()` or `tensor.long()`?

**Comment by awni** [comment]
You can use `astype`, e.g. `x.astype(mx.int32)`

We follow NumPy API there.. so we won't add `int` or `long` on the `array`.
