### ISSUE TITLE
Implement VMAP for Scatter

### ISSUE THREAD

**Issue by awni** [ml-explore/mlx#909]
As title.

**Comment by amirhossein-razlighi** [comment]
I am willing to look into that and start working on it. Can you give a littlebit more info on what is needed and where to get started please?

**Comment by pharringtonp19** [comment]
@awni Is this something I could help implement?

**Comment by awni** [comment]
Yes.. @amirhossein-razlighi let us know if you are working on it already.

**Comment by amirhossein-razlighi** [comment]
No I have not started it yet.

**Comment by pharringtonp19** [comment]
@awni I can dive into this at the end of the week. What's the background needed to develop for this library? Python & C++?
