### ISSUE TITLE
Better Exceptions in case of invalid operations on `mlx.core.array`

### ISSUE THREAD

**Issue by amirhossein-razlighi** [ml-explore/mlx#910]
Regarding a conversation on [this PR](https://github.com/ml-explore/mlx/pull/886#issue-2204299594), there is a requirement for better exception (and error messages) in case of invalid operations on mlx array. For example:
```
import mlx.core as mx

mx.array([1, 2]) > [1,2] # ValueError: Invalid type  list received in array initialization.

# same thing for '<', '<=', '>=', '%', '*', etc.
```

while we are not actually initialising anything here! So, the error message should somehow represent that this operation is not valid. I think this will help for better debugging and more meaningful error messages.
Any suggestions?

**Comment by amirhossein-razlighi** [comment]
@awni 
Any suggestions on what we throw in these cases? Maybe something like:
```
Value Error: You should convert operands to mlx.core.array before comparing to (or operating on) an array.
```

**Comment by awni** [comment]
Maybe something like:

```
Value Error: Cannot <op_name> on an mlx.core.array and <type>.
```

I don't think we should suggest to cast to array because it's not essential.
