### ISSUE TITLE
[BUG] Possible access of freed memory in compile_tests.cpp

### ISSUE THREAD

**Issue by zcbenz** [ml-explore/mlx#918]
**Describe the bug**

The `compile_tests.cpp` test passes but it is actually accessing freed memory.

**To Reproduce**

Add `CHECK_EQ(e.inputs().size(), 4);` to:

https://github.com/ml-explore/mlx/blob/d6112515024f930131134d0c0e91d50493349a0e/tests/compile_tests.cpp#L215-L220

Or just change `e.inputs()[0]` to `e.inputs().at(0)`.

And the test fails.

**Desktop (please complete the following information):**

Crashes on macOS 14, both intel and apple silicon. And also Linux.

**Additional context**

It happens on latest main, and also 16546c70d8983e9860f7456c0dfc63176fc95568, didn't test further.

I'm not familiar with this part of code so I can't say whether it is a bug of the test or the library.

**Comment by awni** [comment]
Ah that looks like a bug in the test. Once you evaluate an array it is detached from the graph, so `e` will no longer have any inputs. We should move this line:
```
   CHECK(array_equal(e, array({0.0f, 1.0f, 0.0f, 1.0f})).item<bool>()); 
```

Below the check on the inputs.

**Comment by awni** [comment]
Thanks for spotting that!

**Comment by angeloskath** [comment]
Thanks for finding this. This is 100% a bug of the tests. The `array_equal` check is evaluating `e` so there are no inputs anymore. The `array_equal` check should be after the inputs checks. I 'll submit a quick PR.
