### ISSUE TITLE
[Feature] Support for operations where output shape depends on input shape

### ISSUE THREAD

**Issue by amirhossein-razlighi** [ml-explore/mlx#927]
Hi. 
I think many of recent issues are related to this issue that MLX currently can not handle operations in which, output shape depends on the input shape. I know this may require a lot of additions and is a big task, but I think this should be resolved in order to be able to resolve a lot of issues (like boolean masking or etc.).

Any ideas?

**Comment by awni** [comment]
No we aren't planning to add it. If there are use cases that don't work please share and we can investigate on a case-by-case basis.

Relevant open issues:
Boolean mask #246 
Nonzero #568 

If you like, you can open a discussion on this subject for people to post other examples.
