### ISSUE TITLE
[QUESTION] Do the M1/M2/M3 GPUs or the ANEs support FP8 operations?

### ISSUE THREAD

**Issue by geraltFromRivia** [ml-explore/mlx#928]
I have hard time finding an answer to this: does the GPU are the ANE support FP8 operations?

**Comment by awni** [comment]
FP8 is not in the [Metal specification](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf)

**Comment by geraltFromRivia** [comment]
Thank you for letting me know!
