### ISSUE TITLE
[Question] loading state dictionary

### ISSUE THREAD

**Issue by a1eaiactaest** [ml-explore/mlx#930]
This code fragment loads torch's `nn.Module` state from saved state:
```python3
[...]
self.model.load_state_dict(torch.load(path))
self.model.eval()
[...]
```
How to achieve the same thing with mlx given the `path` argument? Should this work?
```python3
import mlx
import mlx.core as mx

[...]
checkpoint_state = mx.load(path)
self.model.state = checkpoint_state
self.model.eval()
[...]

**Comment by awni** [comment]
```python
self.model.load_weights(path)
self.model.eval()
```

More in the [docs](https://ml-explore.github.io/mlx/build/html/python/nn/module.html#mlx.nn.Module)

**Comment by a1eaiactaest** [comment]
Even if the file in the `path` is state dict and not only weights?

**Comment by awni** [comment]
There is no state dict for MLX
