### ISSUE TITLE
[Feature] add a in-place arg.  for apply

### ISSUE THREAD

**Issue by 0x1orz** [ml-explore/mlx#931]
In-place argument in `apply` and `apply_to_modules` could  be more flexible and pythonic.

**Comment by awni** [comment]
They are already in place. Do you mean something different?

**Comment by 0x1orz** [comment]
I means that,  to  expose an argument  like `inplace=False` to return a new module instance.

**Comment by awni** [comment]
You can use copy.deep copy

**Comment by 0x1orz** [comment]
Yeah. I did as you said. But like pandas,  the `apply` method always is pure-functional, without inplace operation, instead of the `update` method.

**Comment by awni** [comment]
I'm not sure i follow. Maybe you can explain what you are trying to accomplish in more detail with an example.

**Comment by 0x1orz** [comment]
Sorry, as my fault. I am just a bit not used to use  `apply`  in place.

**Comment by awni** [comment]
No problem at all :). Yes all of the Module methods are in place (I don't think we will change it). You can alwasy get the model dict and do stuff in a pure style if that's helpful (it's a lot more Jaxy if that's where you are coming from):

`params = tree_map(fn, model.parameters())`
