### ISSUE TITLE
[Feature] Implementation of `mx.meshgrid`

### ISSUE THREAD

**Issue by amirhossein-razlighi** [ml-explore/mlx#935]
The equivalent of `torch.meshgrid` is needed in mlx for easier and more convenient way of creating 2D maps from 1D tensors. Please refer to [here](https://pytorch.org/docs/stable/generated/torch.meshgrid.html) for Pytorch's documentation on `torch.meshgrid`

**Comment by amirhossein-razlighi** [comment]
Sure! I will start working on that

**Comment by abeleinin** [comment]
@awni Feature merged. This issue can be closed.
