### ISSUE TITLE
`a[..., 0] = 1` does not assign the entire column

### ISSUE THREAD

**Issue by davidkoski** [ml-explore/mlx#936]
**Describe the bug**
`a[..., 0] = 1` does not assign the entire column, see below

**To Reproduce**

Here is a correct numpy version:

```python
>>> b = np.arange(18).reshape(3, 2, 3)
>>> b[..., 0] = 1
>>> b
array([[[ 1,  1,  2],
        [ 1,  4,  5]],

       [[ 1,  7,  8],
        [ 1, 10, 11]],

       [[ 1, 13, 14],
        [ 1, 16, 17]]])
>>> b.sum()
114
```

and an incorrect mlx version:

```python
>>> a = mx.arange(18).reshape(3, 2, 3)
>>> a[..., 0] = 1
>>> a
array([[[1, 1, 2],
        [1, 4, 5]],
       [[1, 7, 8],
        [1, 10, 11]],
       [[1, 13, 14],
        [15, 16, 17]]], dtype=int32)
>>> a.sum()
array(128, dtype=int32)
```

**Expected behavior**
The 15 should be a 1

**Desktop (please complete the following information):**
 - hash f30b659291b1d279034c77891a2c700e50d7a6f3

**Comment by angeloskath** [comment]
I don't seem to be able to reproduce it on `main`. Checking on the commit you mentioned.

**Comment by davidkoski** [comment]
Or not?  I rebuilt (`pip install .`) with some `cout` and now it looks fine.  It must have been an older hash that I had installed

**Comment by davidkoski** [comment]
Recommend closing, I can't repro now either.
