### ISSUE TITLE
[Feature] Array to allow images as parameters

### ISSUE THREAD

**Issue by suvan-kumar** [ml-explore/mlx#938]
Similar to how NumPy allows for `np.array(image)`, the MLX array framework could use the enhancement of `mx.array(image)` as opposed to needing `mx.array(np.array(image))`.

If this is a valid enhancement that is of interest, I would be happy to get to work on it.

**Comment by angeloskath** [comment]
Assuming that `image` refers to a Pillow/PIL image then I think it is not worth adding special consideration for handling that. Pillow exposes the `__array_interface__` protocol which is supported by numpy https://numpy.org/doc/stable/reference/arrays.interface.html . Maybe we could support that, I am not too sure.

A quick work around for `uint8` images is the following snippet.

```
x = mx.array(im.tobytes())
x = x.reshape(im.height, im.width, -1)
```

**Comment by awni** [comment]
I wonder why they don't support the buffer protocol for export that would be the simplest.. 

@suvan-kumar maybe you could [ask them](https://github.com/python-pillow/Pillow/pulls) if they would consider supporting the buffer protocol .. I think it would be great to have some standardization there.

**Comment by awni** [comment]
Closing for now as not going to implement.
