### ISSUE TITLE
[Feature] BFloat16 SDPA

### ISSUE THREAD

**Issue by peterjc123** [ml-explore/mlx#945]
The training with bfloat16 gets extremely slow if the input length is long enough (e.g. 256/512). Hopefully, we can have BF16 SDPA to enjoy faster training experience.

**Comment by awni** [comment]
BF16 is likely because it's not a native type. A BF16 SDPA wouldn't help with that specifically.

Can you share the benchmark you are running?

**Comment by peterjc123** [comment]
@awni I have M3 Pro. I guess it is a native type for me, no?

**Comment by peterjc123** [comment]
model: Qwen2 1.8B 
batch size: 2
input length: 256
training speed: 12s/Iter

**Comment by awni** [comment]
What were you running? LoRA/ QLoRA? Maybe just share the command?

**Comment by peterjc123** [comment]
> What were you running? LoRA/ QLoRA? Maybe just share the command?

I was trying to run LoRA with my training framework which has data packing enabled. But to my surprise, it is actually slower with MLX.

Code for monkey patching to enable data packing:
```py
            def patched_call(self, inputs, cache=None):
                h = self.embed_tokens(inputs)

                ## Using cache for attention mask, since cache is not used in training
                mask = cache
                if mask is None:
                    if h.shape[1] > 1:
                        mask = nn.MultiHeadAttention.create_additive_causal_mask(h.shape[1])
                        mask = mask.astype(h.dtype)
                else:
                    slices = [mask[i] for i in range(mask.shape[0])]
                    masks = [(~mx.triu(m[:, None] == m[None])) * -1e9 for m in slices]
                    mask = mx.expand_dims(mx.stack(masks, 0), 1)
                    mask = mask.astype(h.dtype)

                cache = [None] * len(self.layers)

                for e, layer in enumerate(self.layers):
                    h, cache[e] = layer(h, mask, cache[e])

                return self.norm(h), cache

            model.model.__call__ = patched_call.__get__(model.model, type(model.model))
```

> Also did you try in fp16? Was it much faster?

Yeah, I just tried fp16. It yields 10.6s/Iter, which is 10% faster. This is still below my expectations.

**Comment by awni** [comment]
How fast is it without your batch packing?

Also you might want to check that your packing is actually being uses. Does not look like you are overriding `__call__` properly there (though I can't be sure given I don't know what else is going on in your code).

E.g. see the following:

```
class M:
    def __call__(self):
        print("hi")

def patch(self):
    print("bye")

m = M()
m.__call__ = patch
m() # prints hi
type(m).__call__ = patch
m() # prints bye
```
