### ISSUE TITLE
[BUG] cumsum doesn't work with bfloat16

### ISSUE THREAD

**Issue by abdulfatir** [ml-explore/mlx#959]
**Describe the bug**
`mx.cumsum` does not work with `bfloat16` dtype. It looks like there is no cumsum kernel for `bfloat16`.

**To Reproduce**

Include code snippet
```python
import mlx.core as mx

arr = mx.random.uniform(shape=(2, 3))
print(mx.cumsum(arr, axis=-1))
print(mx.cumsum(arr.astype(mx.bfloat16), axis=-1))
```

Output:
```
array([[0.21565, 1.02534, 1.45524],
       [0.89461, 1.02131, 1.5572]], dtype=float32)
libc++abi: terminating due to uncaught exception of type std::runtime_error: [metal::Device] Unable to load kernel contiguous_scan_inclusive_sum_bfloat16_bfloat16
```

**Expected behavior**
Expected `cumsum` to work with `bfloat16` dtype.

**Desktop (please complete the following information):**
 - OS Version: MacOS 13.6.4
 - Version 0.9.0

**Additional context**
N/A

**Comment by awni** [comment]
Indeed we know about this one. Thanks for filing the issue. I'm not yet sure how difficult it would be to fix, might be pretty straightforward.
