### ISSUE TITLE
add topic tag `machine-learning`

### ISSUE THREAD

**Issue by Beliavsky** [ml-explore/mlx#965]
I suggest adding the topic `machine-learning` in the About section of the Readme.

**Comment by awni** [comment]
Thanks for the suggestion.

**Comment by Beliavsky** [comment]
It's not added yet. Please see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics for how to add topics.
